
// Auto-generated by scripts/translate-content.mjs at 2026-05-03T08:35:29.303Z.
// Slovak localization. UI label: Prevencia.
export const bestPractices: Record<string, string[]> = {
  "prompt-injection": [
    "Udržujte privilegované pokyny oddelene od načítaného obsahu, e-mailov, webových stránok, tiketov a výstupov nástrojov.",
    "Predvolene odmietať volania nástrojov spustené nedôveryhodným obsahom; vyžadovať štruktúrované plány pre akékoľvek externé odosielanie alebo zápis.",
    "Označte kontext podľa zdroja a úrovne dôveryhodnosti, aby recenzenti videli, čo ovplyvnilo danú akciu.",
    "Pred každým vydaním produkčnej verzie vykonajte testovanie pomocou prípravkov na nepriame podnety."
  ],
  "excessive-agency": [
    "Nahraďte široké nástroje úzkymi nástrojmi špecifickými pre jednotlivé úlohy, ktoré kódujú obchodné pravidlá v kóde.",
    "Vyžadujte ľudské schválenie pre akcie odstraňovania, nasadzovania, prenosu, externého odosielania a zmeny oprávnení.",
    "Mint krátkodobé poverenia na jeden beh namiesto toho, aby agenti dedili široké používateľské rozsahy.",
    "Zaznamenávajte každé volanie nástroja s aktérom, rozsahom, vstupom, výstupom a pôvodnou správou."
  ],
  "data-exfiltration": [
    "Zablokujte neschválené odchádzajúce destinácie z agentových runtime a kódových sandboxov.",
    "Zakážte automatické vykresľovanie alebo načítavanie adries URL ovládaných útočníkom vo výstupe modelu.",
    "Vykonávajte kontroly DLP predtým, ako sa obsah dostane do e-mailu, webového háku, prehliadača, tiketu alebo nástrojov na zasielanie správ.",
    "Rozdeľte pamäť a vyhľadávanie podľa nájomcu, používateľa, označenia údajov a aktuálnej úlohy."
  ],
  "supply-chain": [
    "Pripínajte rámce agentov, servery MCP, výzvy a verzie modelov; pred zavedením preskúmajte zmeny.",
    "Spúšťajte nástroje tretích strán v izolovaných prostrediach s minimálnym prístupom k súborovému systému a sieti.",
    "Pred prijatím overte pôvod balíka, podpisy, vlastníkov a históriu vydania.",
    "Sledujte opisy nástrojov a odpovede na neočakávané zmeny pokynov."
  ],
  "identity-and-authorization": [
    "Autorizujte každé volanie nástroja voči aktuálnemu používateľovi, nájomcovi, úlohe a požadovanej činnosti.",
    "Používajte rozsahové delegované tokeny namiesto zdieľaných účtov služieb pre agentov prichádzajúcich k používateľom.",
    "Urobte citlivé rozsahy stupňovitých oprávnení, nie jednorazové paušálne udelenia.",
    "Testujte prípady cross-tenant, confused-deputy a stale-session ako prvotriedne bezpečnostné testy."
  ],
  "hallucination-and-reliability": [
    "Overujte skutočnosti s vysokým vplyvom na zdrojové systémy predtým, ako na nich agent môže konať.",
    "Používajte schémy, invarianty a deterministické kontroly okolo vstupov a výstupov nástrojov.",
    "Udržiavajte pripravené cesty vrátenia pre každú akciu zápisu, ktorú môže agent vykonať.",
    "Uprednostňujte menšie overiteľné kroky pred dlhými autonómnymi reťazcami."
  ],
  "multi-agent-coordination": [
    "Správy od iných agentov považujte za nedôveryhodný vstup, pokiaľ nie je explicitne uvedený pôvod a oprávnenia.",
    "Definujte jasné vlastníctvo stavu, nástrojov a konečných rozhodnutí v rámci agentových rolí.",
    "Pridajte arbitráž a prerušovače pre konfliktné alebo opakujúce sa činnosti agenta.",
    "Sledujte vzájomné odovzdávanie agentov, aby bolo možné rekonštruovať zlyhania."
  ],
  "privacy-and-compliance": [
    "Minimalizujte osobné údaje predtým, ako sa dostanú do modelu alebo dlhodobej pamäte.",
    "Vykonávajte obmedzenia týkajúce sa pobytu, uchovávania, súhlasu a účelu v čase vyhľadávania.",
    "Citlivé polia štandardne redaktúrujte alebo tokenifikujte; odhaľujte ich len vtedy, keď si to úloha vyžaduje.",
    "Uchovávajte auditné záznamy, ktoré ukazujú, aké údaje boli spracované, prečo a akou cestou agenta."
  ],
  "denial-of-service-and-cost": [
    "Nastavte pevné rozpočty pre tokeny, volania nástrojov, opakované pokusy, akcie prehliadača a výdavky na infraštruktúru.",
    "Používajte prerušovače obvodov pre slučky, opakované zlyhania a neočakávané vyvetrávanie.",
    "Nákladné akcie zaraďte do fronty za limity rýchlosti a upozornenia na anomálie.",
    "Pri dosiahnutí limitov zlyhávať uzavreté namiesto toho, aby ste model požiadali o samoreguláciu."
  ],
  "insecure-output-handling": [
    "Zaobchádzajte s výstupom modelu ako s používateľským vstupom: uniknite, sanitizujte, validujte a parametrizujte ho.",
    "Nikdy nespúšťajte vygenerovaný kód, SQL, shell, HTML alebo markdown v privilegovanom kontexte bez kontrol.",
    "Renderujte nedôveryhodný výstup v izolovaných kontextoch s prísnou politikou zabezpečenia obsahu.",
    "Testujte nadväzujúce analyzátory a vykresľovače so škodlivými prípravkami na výstup modelu."
  ]
};
