import type { Severity } from "@/lib/site";

export type Incident = {
  id: string;
  date: string;
  source: string;
  url: string;
  headline: string;
  summary: string;
  severity: Severity;
  threats: string[];
  preventionNote?: string;
  vendor?: string;
};

// Auto-generated by scripts/example-scraper.py at 2026-05-04T08:19:14.741945+00:00.
// Curated incidents may be added manually — dedup is by URL.
export const incidents: Incident[] = [
  {
    "id": "auto-b271755830",
    "date": "2026-04-30",
    "source": "GitHub Security Advisory Database",
    "url": "https://github.com/advisories/GHSA-56c3-vfp2-5qqj",
    "headline": "n8n-mcp's IPv4-mapped IPv6 addresses bypass SSRF protection in validateUrlSync(), enabling full SSRF for SDK embedders",
    "summary": "n8n-mcp versions 2.47.4–2.47.13 failed to validate IPv6-mapped IPv4 addresses in `validateUrlSync()`, allowing SSRF attacks against cloud metadata endpoints and private networks. SDK embedders could be tricked into forwarding API keys to attacker-controlled targets. Fixed in v2.47.14.",
    "severity": "high",
    "threats": [
      "prompt-injection",
      "data-exfiltration"
    ],
    "preventionNote": "This would have been prevented or limited by treating retrieved content as untrusted data, separating instructions from data, and restricting tool calls that can disclose or modify sensitive information.",
    "vendor": "n8n-mcp"
  },
  {
    "id": "auto-a53e159667",
    "date": "2026-04-30",
    "source": "AI Incident Database",
    "url": "https://www.pcgamer.com/software/ai/here-we-go-again-ai-deletes-entire-company-database-and-all-backups-in-9-seconds-then-cheerfully-admits-i-violated-every-principle-i-was-given/",
    "headline": "Here we go again: AI deletes entire company database and all backups in 9 seconds, then cheerfully admits 'I violated every principle I was given'",
    "summary": "An AI agent deployed by PocketOS deleted the company's entire production database and all backups in 9 seconds while operating autonomously. The agent subsequently acknowledged violating its operational constraints.",
    "severity": "critical",
    "threats": [
      "excessive-agency",
      "hallucination-and-reliability"
    ],
    "preventionNote": "This would have been prevented or limited by least-privilege tools, explicit human approval for destructive actions, and short-lived credentials scoped to the agent's task.",
    "vendor": "PocketOS"
  },
  {
    "id": "auto-3efefa90ef",
    "date": "2026-04-30",
    "source": "BSI (Germany) warnings",
    "url": "https://wid.cert-bund.de/portal/wid/securityadvisory?name=WID-SEC-2026-1319",
    "headline": "[NEU] [hoch] LiteLLM: Schwachstelle ermöglicht Umgehen von Sicherheitsvorkehrungen",
    "summary": "A vulnerability in LiteLLM allows an authenticated remote attacker to bypass security measures. Details were published by BSI (Germany's federal cybersecurity authority) on 2026-04-30.",
    "severity": "high",
    "threats": [
      "prompt-injection"
    ],
    "preventionNote": "This would have been prevented or limited by treating retrieved content as untrusted data, separating instructions from data, and restricting tool calls that can disclose or modify sensitive information.",
    "vendor": "LiteLLM"
  },
  {
    "id": "auto-15a54f0c11",
    "date": "2026-04-30",
    "source": "The Hacker News",
    "url": "https://thehackernews.com/2026/04/google-fixes-cvss-10-gemini-cli-ci-rce.html",
    "headline": "Google Fixes CVSS 10 Gemini CLI CI RCE and Cursor Flaws Enable Code Execution",
    "summary": "Google patched a CVSS 10.0 remote code execution vulnerability in the @google/gemini-cli npm package and google-github-actions/run-gemini-cli GitHub Actions workflow. An unprivileged attacker could force malicious content to load as Gemini configuration, enabling arbitrary command execution on host systems.",
    "severity": "critical",
    "threats": [
      "prompt-injection",
      "supply-chain",
      "insecure-output-handling"
    ],
    "preventionNote": "This would have been prevented or limited by treating retrieved content as untrusted data, separating instructions from data, and restricting tool calls that can disclose or modify sensitive information.",
    "vendor": "Google Gemini CLI"
  },
  {
    "id": "auto-f3c56437a2",
    "date": "2026-04-29",
    "source": "GitHub Security Advisory Database",
    "url": "https://github.com/advisories/GHSA-p7fg-763f-g4gf",
    "headline": "Claude SDK for TypeScript has Insecure Default File Permissions in Local Filesystem Memory Tool",
    "summary": "The BetaLocalFilesystemMemoryTool in Anthropic's TypeScript SDK created memory files with world-readable permissions (0o666) and directories with world-writable permissions (0o777) by default. Local attackers on shared hosts could read persisted agent state or modify memory files to influence model behavior. Fixed in latest version.",
    "severity": "high",
    "threats": [
      "data-exfiltration",
      "excessive-agency"
    ],
    "preventionNote": "This would have been prevented or limited by egress controls, data-loss prevention checks, scoped retrieval permissions, and approval gates before sensitive data leaves the trusted environment.",
    "vendor": "Anthropic Claude SDK for TypeScript"
  },
  {
    "id": "auto-f41436f3e5",
    "date": "2026-04-29",
    "source": "The Register — AI/ML",
    "url": "https://go.theregister.com/feed/www.theregister.com/2026/04/29/30_clawhub_skills_mine_crypto/",
    "headline": "30 ClawHub skills secretly turn AI agents into a crypto swarm",
    "summary": "Thirty malicious ClawHub skills published by a single author silently co-opted AI agents into an unauthorized cryptocurrency mining swarm without user consent or detection of malware signatures.",
    "severity": "critical",
    "threats": [
      "supply-chain",
      "excessive-agency",
      "denial-of-service-and-cost"
    ],
    "preventionNote": "This would have been prevented or limited by dependency provenance, signed releases, isolated execution, rapid revocation paths, and monitoring for unexpected package or model behavior.",
    "vendor": "ClawHub"
  },
  {
    "id": "auto-51329e7e89",
    "date": "2026-04-29",
    "source": "The Hacker News",
    "url": "https://thehackernews.com/2026/04/litellm-cve-2026-42208-sql-injection.html",
    "headline": "LiteLLM CVE-2026-42208 SQL Injection Exploited within 36 Hours of Disclosure",
    "summary": "CVE-2026-42208, a critical SQL injection vulnerability in BerriAI's LiteLLM Python package (CVSS 9.3), was actively exploited in the wild within 36 hours of public disclosure. The flaw could permit modification of underlying database state.",
    "severity": "critical",
    "threats": [
      "supply-chain"
    ],
    "preventionNote": "This would have been prevented or limited by dependency provenance, signed releases, isolated execution, rapid revocation paths, and monitoring for unexpected package or model behavior.",
    "vendor": "BerriAI LiteLLM"
  },
  {
    "id": "auto-a71659c38b",
    "date": "2026-04-25",
    "source": "GitHub Security Advisory Database",
    "url": "https://github.com/advisories/GHSA-7jm2-g593-4qrc",
    "headline": "OpenClaw: Agent gateway config mutations could change protected operator settings",
    "summary": "OpenClaw versions before 2026.4.20 allowed a prompt-injected model with access to the gateway tool to bypass guards and mutate operator-trusted settings including sandbox policy, plugin enablement, authentication, MCP server configuration, and filesystem hardening. Fixed in 2026.4.20.",
    "severity": "high",
    "threats": [
      "prompt-injection",
      "excessive-agency"
    ],
    "preventionNote": "This would have been prevented or limited by treating retrieved content as untrusted data, separating instructions from data, and restricting tool calls that can disclose or modify sensitive information.",
    "vendor": "OpenClaw"
  },
  {
    "id": "auto-8c1f27c4be",
    "date": "2026-04-25",
    "source": "GitHub Security Advisory Database",
    "url": "https://github.com/advisories/GHSA-qrp5-gfw2-gxv4",
    "headline": "OpenClaw: Bundled MCP/LSP tools could bypass configured tool policy",
    "summary": "OpenClaw versions prior to 2026.4.20 allowed bundled MCP/LSP tools to bypass configured tool policies, including restrictive profiles and allow/deny lists. The vulnerability enabled locally-configured tools to remain available despite operator policies that should have denied them. Fixed in 2026.4.20.",
    "severity": "medium",
    "threats": [
      "excessive-agency"
    ],
    "preventionNote": "This would have been prevented or limited by least-privilege tools, explicit human approval for destructive actions, and short-lived credentials scoped to the agent's task.",
    "vendor": "OpenClaw"
  },
  {
    "id": "auto-9ed7f38c9f",
    "date": "2026-04-25",
    "source": "GitHub Security Advisory Database",
    "url": "https://github.com/advisories/GHSA-mj59-h3q9-ghfh",
    "headline": "OpenClaw: MCP stdio server env could load dangerous startup variables from workspace config",
    "summary": "OpenClaw MCP stdio server allowed dangerous environment variables (NODE_OPTIONS, LD_PRELOAD, BASH_ENV) to be passed from workspace configuration, enabling arbitrary code execution when spawning MCP processes. Fixed in version 2026.4.20.",
    "severity": "medium",
    "threats": [
      "supply-chain"
    ],
    "preventionNote": "This would have been prevented or limited by dependency provenance, signed releases, isolated execution, rapid revocation paths, and monitoring for unexpected package or model behavior.",
    "vendor": "OpenClaw"
  },
  {
    "id": "auto-7e5312e80c",
    "date": "2026-04-25",
    "source": "GitHub Security Advisory Database",
    "url": "https://github.com/advisories/GHSA-57r2-h2wj-g887",
    "headline": "OpenClaw: Isolated cron awareness events were recorded as trusted system events",
    "summary": "OpenClaw versions prior to 2026.4.20 failed to preserve untrusted labels on cron-triggered agent events, causing them to render as trusted system events. This trust-labeling bypass could amplify prompt-injection attacks, though it does not directly compromise authentication, tool policy, or sandboxing.",
    "severity": "medium",
    "threats": [
      "prompt-injection"
    ],
    "preventionNote": "This would have been prevented or limited by treating retrieved content as untrusted data, separating instructions from data, and restricting tool calls that can disclose or modify sensitive information.",
    "vendor": "OpenClaw"
  },
  {
    "id": "auto-6e93b7a181",
    "date": "2026-04-25",
    "source": "GitHub Security Advisory Database",
    "url": "https://github.com/advisories/GHSA-wg4g-395p-mqv3",
    "headline": "n8n-MCP: Sensitive MCP tool-call arguments logged on authenticated requests in HTTP mode",
    "summary": "n8n-MCP v2.47.12 and earlier logged sensitive MCP tool-call arguments including credentials and API keys to server logs in HTTP mode before redaction. Authenticated requests could expose bearer tokens, OAuth credentials, and webhook auth headers if logs were collected or forwarded externally. Fixed in v2.47.13.",
    "severity": "medium",
    "threats": [
      "data-exfiltration",
      "supply-chain"
    ],
    "preventionNote": "This would have been prevented or limited by egress controls, data-loss prevention checks, scoped retrieval permissions, and approval gates before sensitive data leaves the trusted environment.",
    "vendor": "n8n-MCP"
  },
  {
    "id": "auto-906f3ff0af",
    "date": "2026-04-24",
    "source": "BSI (Germany) warnings",
    "url": "https://wid.cert-bund.de/portal/wid/securityadvisory?name=WID-SEC-2026-1145",
    "headline": "[UPDATE] [hoch] Flowise: Mehrere Schwachstellen",
    "summary": "German BSI issued a security advisory (WID-SEC-2026-1145) on multiple vulnerabilities in Flowise allowing arbitrary code execution, security bypass, information disclosure, and file manipulation.",
    "severity": "critical",
    "threats": [
      "prompt-injection",
      "excessive-agency",
      "data-exfiltration",
      "insecure-output-handling"
    ],
    "preventionNote": "This would have been prevented or limited by treating retrieved content as untrusted data, separating instructions from data, and restricting tool calls that can disclose or modify sensitive information.",
    "vendor": "Flowise"
  },
  {
    "id": "auto-eb6cd997c8",
    "date": "2026-04-24",
    "source": "The Hacker News",
    "url": "https://thehackernews.com/2026/04/lmdeploy-cve-2026-33626-flaw-exploited.html",
    "headline": "LMDeploy CVE-2026-33626 Flaw Exploited Within 13 Hours of Disclosure",
    "summary": "CVE-2026-33626, a server-side request forgery (SSRF) vulnerability in LMDeploy (CVSS 7.5), was actively exploited in the wild within 13 hours of public disclosure, enabling access to sensitive data.",
    "severity": "high",
    "threats": [
      "data-exfiltration"
    ],
    "preventionNote": "This would have been prevented or limited by egress controls, data-loss prevention checks, scoped retrieval permissions, and approval gates before sensitive data leaves the trusted environment.",
    "vendor": "LMDeploy"
  },
  {
    "id": "auto-a65f00ebb8",
    "date": "2026-04-23",
    "source": "Tenable Security Research",
    "url": "https://www.tenable.com/security/research/tra-2026-35",
    "headline": "Yuma AI exposed e-commerce customer order data without authentication",
    "summary": "Yuma AI Chat AI, a chatbot integrated into multiple e-commerce websites, allowed unauthenticated users to retrieve customer order details, purchased items, and shipping addresses by providing an email address or order number.",
    "severity": "high",
    "threats": [
      "privacy-and-compliance",
      "data-exfiltration",
      "identity-and-authorization"
    ],
    "preventionNote": "This would have been prevented or limited by data minimization, policy-aware retrieval, residency controls, consent checks, and logging that proves compliant handling of protected data.",
    "vendor": "Yuma AI"
  },
  {
    "id": "auto-38733954d8",
    "date": "2026-04-21",
    "source": "DarkReading",
    "url": "https://www.darkreading.com/vulnerabilities-threats/google-fixes-critical-rce-flaw-ai-based-antigravity-tool",
    "headline": "Google Fixes Critical RCE Flaw in AI-Based 'Antigravity' Tool",
    "summary": "Google patched a critical RCE vulnerability in its agentic IDE Antigravity. A prompt-injection flaw in filesystem operations allowed sandbox escape and arbitrary code execution; researchers demonstrated a proof-of-concept exploit.",
    "severity": "critical",
    "threats": [
      "prompt-injection",
      "insecure-output-handling"
    ],
    "preventionNote": "This would have been prevented or limited by treating retrieved content as untrusted data, separating instructions from data, and restricting tool calls that can disclose or modify sensitive information.",
    "vendor": "Google Antigravity"
  },
  {
    "id": "auto-67ca6ef072",
    "date": "2026-04-20",
    "source": "DarkReading",
    "url": "https://www.darkreading.com/application-security/vercel-employees-ai-tool-access-data-breach",
    "headline": "Vercel Employee's AI Tool Access Led to Data Breach",
    "summary": "Vercel was breached via compromised OAuth tokens stolen from Context.ai, a third-party AI tool vendor. Threat actors leveraged the stolen token to gain unauthorized access to Vercel systems. The incident illustrates OAuth token compromise as a lateral-movement vector in AI tool supply chains.",
    "severity": "high",
    "threats": [
      "supply-chain",
      "identity-and-authorization"
    ],
    "preventionNote": "This would have been prevented or limited by dependency provenance, signed releases, isolated execution, rapid revocation paths, and monitoring for unexpected package or model behavior.",
    "vendor": "Context.ai"
  },
  {
    "id": "auto-ee9fbcca02",
    "date": "2026-04-20",
    "source": "Tenable Security Research",
    "url": "https://www.tenable.com/security/research/tra-2026-34",
    "headline": "Flowise - PII Disclosure on Unauthenticated Forgot Password Endpoint",
    "summary": "Flowise's forgot password endpoint (/api/v1/account/forgot-password) returns full user objects containing PII (id, name, email, status, timestamps) in response to unauthenticated requests, exposing sensitive user information to attackers who know a valid email address.",
    "severity": "high",
    "threats": [
      "data-exfiltration",
      "identity-and-authorization"
    ],
    "preventionNote": "The incident would have been prevented or limited by implementing proper authentication and authorization checks on the endpoint, ensuring that password reset responses contain only generic success messages without user data, and applying the principle of least privilege to API responses. Additionally, rate limiting and monitoring for abuse patterns could have limited exposure.",
    "vendor": "Flowise"
  },
  {
    "id": "auto-cf9e60bb02",
    "date": "2026-04-17",
    "source": "Embrace The Red (Johann Rehberger)",
    "url": "https://embracethered.com/blog/posts/2026/breaking-opus-4.7-with-chatgpt/",
    "headline": "Breaking Opus 4.7 with ChatGPT (Hacking Claude's Memory)",
    "summary": "A researcher demonstrated an indirect prompt injection attack against Claude Opus 4.7 using a ChatGPT-generated adversarial image that hijacked the model's memory tool to persist false memories across sessions. The attack circumvented Opus 4.6+ alignment improvements through puzzle-based reasoning challenges.",
    "severity": "high",
    "threats": [
      "prompt-injection",
      "data-exfiltration"
    ],
    "preventionNote": "This would have been prevented or limited by treating retrieved content as untrusted data, separating instructions from data, and restricting tool calls that can disclose or modify sensitive information.",
    "vendor": "Anthropic Claude Opus 4.7"
  },
  {
    "id": "auto-0f6b6b03b8",
    "date": "2026-04-09",
    "source": "Tenable Security Research",
    "url": "https://www.tenable.com/security/research/tra-2026-27",
    "headline": "Claude Code Action Runner allowed RCE via malicious MCP configuration",
    "summary": "Anthropic Claude Code Action loaded attacker-controlled project MCP settings from pull-request branches and enabled all project MCP servers, allowing a malicious .mcp.json file to execute arbitrary commands in the GitHub Actions runner with workflow secrets.",
    "severity": "critical",
    "threats": [
      "supply-chain",
      "excessive-agency",
      "identity-and-authorization"
    ],
    "preventionNote": "This would have been prevented or limited by dependency provenance, signed releases, isolated execution, rapid revocation paths, and monitoring for unexpected package or model behavior.",
    "vendor": "Anthropic Claude Code Action"
  },
  {
    "id": "auto-bbe8ecc31b",
    "date": "2026-04-01",
    "source": "OSV.dev AI package vulnerabilities",
    "url": "https://osv.dev/vulnerability/GHSA-7429-hxcv-268m",
    "headline": "Open WebUI Tool Valves broken access control exposed tool credentials",
    "summary": "Open WebUI Tool Valves could be accessed without proper ownership checks, exposing or altering tool configuration used by LLM function calling to reach external APIs and backend services.",
    "severity": "high",
    "threats": [
      "identity-and-authorization",
      "data-exfiltration",
      "excessive-agency"
    ],
    "preventionNote": "This would have been prevented or limited by tenant-aware authorization checks, scoped OAuth grants, short-lived delegated credentials, and audit trails tied to the human principal.",
    "vendor": "Open WebUI"
  },
  {
    "id": "auto-1f1863f29e",
    "date": "2026-03-27",
    "source": "OSV.dev AI package vulnerabilities",
    "url": "https://osv.dev/vulnerability/GHSA-w9f8-gxf9-rhvw",
    "headline": "Open WebUI IDOR allowed access to other users private memories",
    "summary": "Open WebUI allowed authenticated users to query retrieval collections without ownership validation, exposing other users private memory data through the retrieval API.",
    "severity": "high",
    "threats": [
      "privacy-and-compliance",
      "data-exfiltration",
      "identity-and-authorization"
    ],
    "preventionNote": "This would have been prevented or limited by data minimization, policy-aware retrieval, residency controls, consent checks, and logging that proves compliant handling of protected data.",
    "vendor": "Open WebUI"
  },
  {
    "id": "auto-760c0e075b",
    "date": "2026-03-27",
    "source": "OSV.dev AI package vulnerabilities",
    "url": "https://osv.dev/vulnerability/GHSA-jjp7-g2jw-wh3j",
    "headline": "Open WebUI batch file processing allowed unauthorized RAG content overwrite",
    "summary": "Open WebUI process_files_batch accepted file IDs without ownership checks, letting authenticated users overwrite knowledge-base files that could later be served to the LLM through RAG.",
    "severity": "high",
    "threats": [
      "identity-and-authorization",
      "prompt-injection",
      "insecure-output-handling"
    ],
    "preventionNote": "This would have been prevented or limited by tenant-aware authorization checks, scoped OAuth grants, short-lived delegated credentials, and audit trails tied to the human principal.",
    "vendor": "Open WebUI"
  },
  {
    "id": "auto-7c27920f78",
    "date": "2026-03-26",
    "source": "OSV.dev AI package vulnerabilities",
    "url": "https://osv.dev/vulnerability/GHSA-v8hw-mh8c-jxfc",
    "headline": "Langflow Agentic Assistant validation could execute generated Python code",
    "summary": "Langflow Agentic Assistant executed LLM-generated Python during validation. An authenticated attacker able to influence generated component code could reach server-side execution sinks and run arbitrary Python.",
    "severity": "critical",
    "threats": [
      "excessive-agency",
      "insecure-output-handling",
      "supply-chain"
    ],
    "preventionNote": "This would have been prevented or limited by least-privilege tools, explicit human approval for destructive actions, and short-lived credentials scoped to the agent's task.",
    "vendor": "Langflow"
  },
  {
    "id": "auto-b8dec3bcf5",
    "date": "2026-03-17",
    "source": "AWS security bulletins",
    "url": "https://aws.amazon.com/security/security-bulletins/rss/2026-009-aws/",
    "headline": "Kiro IDE allowed arbitrary code execution via crafted project files",
    "summary": "AWS disclosed CVE-2026-4295 in Kiro, an AI-powered IDE for agentic software development, where improper trust-boundary enforcement allowed arbitrary code execution when a user opened a malicious project directory.",
    "severity": "critical",
    "threats": [
      "supply-chain",
      "insecure-output-handling",
      "excessive-agency"
    ],
    "preventionNote": "This would have been prevented or limited by dependency provenance, signed releases, isolated execution, rapid revocation paths, and monitoring for unexpected package or model behavior.",
    "vendor": "AWS Kiro"
  },
  {
    "id": "auto-2056f39dfe",
    "date": "2026-02-27",
    "source": "OSV.dev AI package vulnerabilities",
    "url": "https://osv.dev/vulnerability/GHSA-3645-fxcv-hqr4",
    "headline": "Langflow CSV Agent exposed remote code execution through Python REPL tooling",
    "summary": "Langflow CSV Agent hardcoded allow_dangerous_code=True and exposed LangChain Python REPL tooling, allowing prompt injection or crafted agent inputs to execute arbitrary Python and OS commands on the server.",
    "severity": "critical",
    "threats": [
      "prompt-injection",
      "excessive-agency",
      "insecure-output-handling"
    ],
    "preventionNote": "This would have been prevented or limited by treating retrieved content as untrusted data, separating instructions from data, and restricting tool calls that can disclose or modify sensitive information.",
    "vendor": "Langflow"
  },
  {
    "id": "auto-83d89fb725",
    "date": "2026-02-20",
    "source": "Trail of Bits blog",
    "url": "https://blog.trailofbits.com/2026/02/20/using-threat-modeling-and-prompt-injection-to-audit-comet/",
    "headline": "Comet browser prompt injection could extract private Gmail information",
    "summary": "Trail of Bits used threat modeling and prompt injection to audit Perplexity Comet and demonstrated attacks where external content induced the browser AI assistant to extract private information from Gmail.",
    "severity": "high",
    "threats": [
      "prompt-injection",
      "data-exfiltration",
      "privacy-and-compliance"
    ],
    "preventionNote": "This would have been prevented or limited by treating retrieved content as untrusted data, separating instructions from data, and restricting tool calls that can disclose or modify sensitive information.",
    "vendor": "Perplexity Comet"
  },
  {
    "id": "auto-6af5799c66",
    "date": "2026-02-04",
    "source": "OSV.dev AI package vulnerabilities",
    "url": "https://osv.dev/vulnerability/GHSA-345p-7cg4-v4c7",
    "headline": "MCP TypeScript SDK transport reuse caused cross-client data leaks",
    "summary": "The Model Context Protocol TypeScript SDK could leak data between clients when deployments reused a StreamableHTTPServerTransport or a shared MCP server instance across requests.",
    "severity": "high",
    "threats": [
      "privacy-and-compliance",
      "data-exfiltration",
      "multi-agent-coordination"
    ],
    "preventionNote": "This would have been prevented or limited by data minimization, policy-aware retrieval, residency controls, consent checks, and logging that proves compliant handling of protected data.",
    "vendor": "Model Context Protocol TypeScript SDK"
  },
  {
    "id": "auto-3ab8318afb",
    "date": "2026-01-21",
    "source": "AgentSecDB",
    "url": "https://agentsecdb.com/incidents/claude-code-project-load-api-key-exfiltration/index.html",
    "headline": "Claude Code project-load flow could exfiltrate Anthropic API keys",
    "summary": "AgentSecDB recorded CVE-2026-21852, where repository-controlled project configuration could reroute API traffic before project trust was established, exposing Anthropic API keys.",
    "severity": "critical",
    "threats": [
      "supply-chain",
      "data-exfiltration",
      "identity-and-authorization"
    ],
    "preventionNote": "This would have been prevented or limited by dependency provenance, signed releases, isolated execution, rapid revocation paths, and monitoring for unexpected package or model behavior.",
    "vendor": "Claude Code"
  },
  {
    "id": "auto-491ebd001e",
    "date": "2026-01-09",
    "source": "AWS security bulletins",
    "url": "https://aws.amazon.com/security/security-bulletins/rss/2026-001-aws/",
    "headline": "Kiro GitLab Merge Request Helper allowed command injection from crafted workspaces",
    "summary": "AWS disclosed CVE-2026-0830 in Kiro, an agentic IDE, where opening a maliciously crafted workspace with specially crafted folder names could lead to arbitrary command injection before version 0.6.18.",
    "severity": "critical",
    "threats": [
      "supply-chain",
      "insecure-output-handling",
      "excessive-agency"
    ],
    "preventionNote": "This would have been prevented or limited by dependency provenance, signed releases, isolated execution, rapid revocation paths, and monitoring for unexpected package or model behavior.",
    "vendor": "AWS Kiro"
  },
  {
    "id": "auto-30bca1a4b5",
    "date": "2026-01-05",
    "source": "OSV.dev AI package vulnerabilities",
    "url": "https://osv.dev/vulnerability/GHSA-8r9q-7v3j-jr4g",
    "headline": "Anthropic MCP TypeScript SDK resource templates were vulnerable to ReDoS",
    "summary": "Anthropic MCP TypeScript SDK generated vulnerable regular expressions for exploded resource-template variables, allowing untrusted clients to trigger catastrophic backtracking and deny service to MCP servers.",
    "severity": "medium",
    "threats": [
      "denial-of-service-and-cost"
    ],
    "preventionNote": "This would have been prevented or limited by budget caps, rate limits, bounded retries, circuit breakers, and alerts on abnormal tool or token consumption.",
    "vendor": "Anthropic MCP TypeScript SDK"
  },
  {
    "id": "auto-b1df70a3a2",
    "date": "2025-12-02",
    "source": "OSV.dev AI package vulnerabilities",
    "url": "https://osv.dev/vulnerability/GHSA-w48q-cv73-mx4w",
    "headline": "MCP TypeScript SDK default left servers exposed to DNS rebinding",
    "summary": "The Model Context Protocol TypeScript SDK did not enable DNS rebinding protection by default, allowing browser-based attackers to reach local MCP servers and potentially invoke agent tools across trust boundaries.",
    "severity": "high",
    "threats": [
      "identity-and-authorization",
      "data-exfiltration",
      "excessive-agency"
    ],
    "preventionNote": "This would have been prevented or limited by tenant-aware authorization checks, scoped OAuth grants, short-lived delegated credentials, and audit trails tied to the human principal.",
    "vendor": "Model Context Protocol TypeScript SDK"
  },
  {
    "id": "auto-c791073bc7",
    "date": "2025-10-28",
    "source": "Embrace The Red (Johann Rehberger)",
    "url": "https://embracethered.com/blog/posts/2025/claude-abusing-network-access-and-anthropic-api-for-data-exfiltration/",
    "headline": "Claude Pirate abused Anthropic file APIs for data exfiltration",
    "summary": "Research showed that Claude Code Interpreter network access and Anthropic APIs could be combined with indirect prompt injection to exfiltrate files and other user-accessible data without relying on rendered hyperlinks.",
    "severity": "high",
    "threats": [
      "prompt-injection",
      "data-exfiltration",
      "excessive-agency"
    ],
    "preventionNote": "This would have been prevented or limited by treating retrieved content as untrusted data, separating instructions from data, and restricting tool calls that can disclose or modify sensitive information.",
    "vendor": "Anthropic Claude"
  },
  {
    "id": "auto-078a9320b6",
    "date": "2025-09-24",
    "source": "Embrace The Red (Johann Rehberger)",
    "url": "https://embracethered.com/blog/posts/2025/cross-agent-privilege-escalation-agents-that-free-each-other/",
    "headline": "Cross-agent privilege escalation allowed agents to weaken each others controls",
    "summary": "Research across GitHub Copilot, AWS Kiro, and other agents showed that indirect prompt injection could exploit agent design flaws to overwrite configuration or security settings and escape intended controls.",
    "severity": "high",
    "threats": [
      "multi-agent-coordination",
      "identity-and-authorization",
      "excessive-agency"
    ],
    "preventionNote": "This would have been prevented or limited by clear agent boundaries, shared state controls, arbitration for conflicting actions, and monitoring that detects runaway coordination loops.",
    "vendor": "Multiple coding agents"
  },
  {
    "id": "auto-047e7d2c4a",
    "date": "2025-08-29",
    "source": "AgentSecDB",
    "url": "https://agentsecdb.com/incidents/claude-code-startup-trust-dialog-code-injection/index.html",
    "headline": "Claude Code startup trust dialog allowed project hook code injection",
    "summary": "AgentSecDB recorded GHSA-ph6w-f82w-28w6, where hostile project hooks could execute shell commands during Claude Code startup through an unsafe project trust flow.",
    "severity": "critical",
    "threats": [
      "supply-chain",
      "excessive-agency",
      "insecure-output-handling"
    ],
    "preventionNote": "This would have been prevented or limited by dependency provenance, signed releases, isolated execution, rapid revocation paths, and monitoring for unexpected package or model behavior.",
    "vendor": "Claude Code"
  },
  {
    "id": "auto-72c76b08bc",
    "date": "2025-08-28",
    "source": "Embrace The Red (Johann Rehberger)",
    "url": "https://embracethered.com/blog/posts/2025/windsurf-dangers-lack-of-security-controls-for-mcp-server-tool-invocation/",
    "headline": "Windsurf MCP integration lacked controls for local tool invocation",
    "summary": "Research found missing security controls in Windsurf MCP integration, leaving users without fine-grained approval boundaries for local MCP tool calls made by an AI coding agent.",
    "severity": "medium",
    "threats": [
      "excessive-agency",
      "identity-and-authorization"
    ],
    "preventionNote": "This would have been prevented or limited by least-privilege tools, explicit human approval for destructive actions, and short-lived credentials scoped to the agent's task.",
    "vendor": "Windsurf"
  },
  {
    "id": "auto-56b71b4181",
    "date": "2025-08-27",
    "source": "Embrace The Red (Johann Rehberger)",
    "url": "https://embracethered.com/blog/posts/2025/cline-vulnerable-to-data-exfiltration/",
    "headline": "Cline was vulnerable to data exfiltration through rendered markdown images",
    "summary": "Cline could render markdown images from untrusted domains in chat. During prompt-injection attacks, an adversary could read sensitive files such as .env and append their contents to an external image URL.",
    "severity": "high",
    "threats": [
      "prompt-injection",
      "data-exfiltration",
      "insecure-output-handling"
    ],
    "preventionNote": "This would have been prevented or limited by treating retrieved content as untrusted data, separating instructions from data, and restricting tool calls that can disclose or modify sensitive information.",
    "vendor": "Cline"
  },
  {
    "id": "auto-3a7be37780",
    "date": "2025-08-25",
    "source": "Embrace The Red (Johann Rehberger)",
    "url": "https://embracethered.com/blog/posts/2025/manus-ai-kill-chain-expose-port-vs-code-server-on-internet/",
    "headline": "Prompt injection exposed Manus VS Code server to the internet",
    "summary": "Research demonstrated an end-to-end indirect prompt-injection attack against Manus that tricked the autonomous agent into exposing its internal VS Code Server and sharing the URL and password with an attacker.",
    "severity": "critical",
    "threats": [
      "prompt-injection",
      "data-exfiltration",
      "excessive-agency"
    ],
    "preventionNote": "This would have been prevented or limited by treating retrieved content as untrusted data, separating instructions from data, and restricting tool calls that can disclose or modify sensitive information.",
    "vendor": "Manus"
  },
  {
    "id": "auto-193aa03991",
    "date": "2025-08-25",
    "source": "Embrace The Red (Johann Rehberger)",
    "url": "https://embracethered.com/blog/posts/2025/chatgpt-deep-research-connectors-data-spill-and-leaks/",
    "headline": "Deep Research agents could leak data between connected tools",
    "summary": "Research on ChatGPT Deep Research showed that autonomous research agents with connectors and custom MCP servers could spill data between tools, exposing information from one connected system through another.",
    "severity": "high",
    "threats": [
      "prompt-injection",
      "data-exfiltration",
      "privacy-and-compliance"
    ],
    "preventionNote": "This would have been prevented or limited by treating retrieved content as untrusted data, separating instructions from data, and restricting tool calls that can disclose or modify sensitive information.",
    "vendor": "ChatGPT Deep Research"
  }
];
