import type { Severity } from "@/lib/site";

export type Incident = {
  id: string;
  date: string;
  source: string;
  url: string;
  headline: string;
  summary: string;
  severity: Severity;
  threats: string[];
  vendor?: string;
};

// Auto-generated by scripts/example-scraper.py at 2026-04-26T16:01:33.952148+00:00.
// Curated incidents may be added manually — dedup is by URL.
export const incidents: Incident[] = [
  {
    "id": "auto-a71659c38b",
    "date": "2026-04-25",
    "source": "GitHub Security Advisory Database",
    "url": "https://github.com/advisories/GHSA-7jm2-g593-4qrc",
    "headline": "OpenClaw: Agent gateway config mutations could change protected operator settings",
    "summary": "OpenClaw versions before 2026.4.20 allowed a prompt-injected model with access to the gateway tool to bypass guards and mutate operator-trusted settings including sandbox policy, plugin enablement, authentication, MCP server configuration, and filesystem hardening. Fixed in 2026.4.20.",
    "severity": "high",
    "threats": [
      "prompt-injection",
      "excessive-agency"
    ],
    "vendor": "OpenClaw"
  },
  {
    "id": "auto-8c1f27c4be",
    "date": "2026-04-25",
    "source": "GitHub Security Advisory Database",
    "url": "https://github.com/advisories/GHSA-qrp5-gfw2-gxv4",
    "headline": "OpenClaw: Bundled MCP/LSP tools could bypass configured tool policy",
    "summary": "OpenClaw versions prior to 2026.4.20 allowed bundled MCP/LSP tools to bypass configured tool policies, including restrictive profiles and allow/deny lists. The vulnerability enabled locally-configured tools to remain available despite operator policies that should have denied them. Fixed in 2026.4.20.",
    "severity": "medium",
    "threats": [
      "excessive-agency"
    ],
    "vendor": "OpenClaw"
  },
  {
    "id": "auto-9ed7f38c9f",
    "date": "2026-04-25",
    "source": "GitHub Security Advisory Database",
    "url": "https://github.com/advisories/GHSA-mj59-h3q9-ghfh",
    "headline": "OpenClaw: MCP stdio server env could load dangerous startup variables from workspace config",
    "summary": "OpenClaw MCP stdio server allowed dangerous environment variables (NODE_OPTIONS, LD_PRELOAD, BASH_ENV) to be passed from workspace configuration, enabling arbitrary code execution when spawning MCP processes. Fixed in version 2026.4.20.",
    "severity": "medium",
    "threats": [
      "supply-chain"
    ],
    "vendor": "OpenClaw"
  },
  {
    "id": "auto-7e5312e80c",
    "date": "2026-04-25",
    "source": "GitHub Security Advisory Database",
    "url": "https://github.com/advisories/GHSA-57r2-h2wj-g887",
    "headline": "OpenClaw: Isolated cron awareness events were recorded as trusted system events",
    "summary": "OpenClaw versions prior to 2026.4.20 failed to preserve untrusted labels on cron-triggered agent events, causing them to render as trusted system events. This trust-labeling bypass could amplify prompt-injection attacks, though it does not directly compromise authentication, tool policy, or sandboxing.",
    "severity": "medium",
    "threats": [
      "prompt-injection"
    ],
    "vendor": "OpenClaw"
  },
  {
    "id": "auto-6e93b7a181",
    "date": "2026-04-25",
    "source": "GitHub Security Advisory Database",
    "url": "https://github.com/advisories/GHSA-wg4g-395p-mqv3",
    "headline": "n8n-MCP: Sensitive MCP tool-call arguments logged on authenticated requests in HTTP mode",
    "summary": "n8n-MCP v2.47.12 and earlier logged sensitive MCP tool-call arguments including credentials and API keys to server logs in HTTP mode before redaction. Authenticated requests could expose bearer tokens, OAuth credentials, and webhook auth headers if logs were collected or forwarded externally. Fixed in v2.47.13.",
    "severity": "medium",
    "threats": [
      "data-exfiltration",
      "supply-chain"
    ],
    "vendor": "n8n-MCP"
  },
  {
    "id": "auto-edb7f60c4c",
    "date": "2026-04-25",
    "source": "The Guardian — Technology",
    "url": "https://www.theguardian.com/uk-news/2026/apr/25/met-police-investigates-hundreds-officers-palantir-ai-tool",
    "headline": "Met investigates hundreds of officers after using Palantir AI tool",
    "summary": "The Metropolitan Police deployed a Palantir AI tool to surveil hundreds of officers, triggering investigations into alleged rule-breaking. The deployment raised immediate concerns about authorization scope, data access controls, and compliance with UK employment and privacy law.",
    "severity": "high",
    "threats": [
      "identity-and-authorization",
      "privacy-and-compliance"
    ],
    "vendor": "Palantir"
  },
  {
    "id": "auto-906f3ff0af",
    "date": "2026-04-24",
    "source": "BSI (Germany) warnings",
    "url": "https://wid.cert-bund.de/portal/wid/securityadvisory?name=WID-SEC-2026-1145",
    "headline": "[UPDATE] [hoch] Flowise: Mehrere Schwachstellen",
    "summary": "German BSI issued a security advisory (WID-SEC-2026-1145) on multiple vulnerabilities in Flowise allowing arbitrary code execution, security bypass, information disclosure, and file manipulation.",
    "severity": "critical",
    "threats": [
      "prompt-injection",
      "excessive-agency",
      "data-exfiltration",
      "insecure-output-handling"
    ],
    "vendor": "Flowise"
  },
  {
    "id": "auto-eb6cd997c8",
    "date": "2026-04-24",
    "source": "The Hacker News",
    "url": "https://thehackernews.com/2026/04/lmdeploy-cve-2026-33626-flaw-exploited.html",
    "headline": "LMDeploy CVE-2026-33626 Flaw Exploited Within 13 Hours of Disclosure",
    "summary": "CVE-2026-33626, a server-side request forgery (SSRF) vulnerability in LMDeploy (CVSS 7.5), was actively exploited in the wild within 13 hours of public disclosure, enabling access to sensitive data.",
    "severity": "high",
    "threats": [
      "data-exfiltration"
    ],
    "vendor": "LMDeploy"
  },
  {
    "id": "auto-ae076fc27e",
    "date": "2026-04-24",
    "source": "SecurityWeek",
    "url": "https://www.securityweek.com/bitwarden-npm-package-hit-in-supply-chain-attack/",
    "headline": "Bitwarden NPM Package Hit in Supply Chain Attack",
    "summary": "Bitwarden's NPM package was compromised in a supply chain attack claimed by TeamPCP, associated with the Shai-Hulud worm. The incident was disclosed by Checkmarx on 2026-04-24.",
    "severity": "high",
    "threats": [
      "supply-chain"
    ],
    "vendor": "Bitwarden"
  },
  {
    "id": "auto-65033bf057",
    "date": "2026-04-24",
    "source": "Risky Business news",
    "url": "https://risky.biz/RBNEWS555/",
    "headline": "Risky Bulletin: Sean Plankey withdraws CISA nomination",
    "summary": "Discord users gained unauthorized access to Anthropic's Mythos system, a confirmed breach of identity and authorization controls. The incident was reported by Risky Business on 2026-04-24.",
    "severity": "high",
    "threats": [
      "identity-and-authorization",
      "data-exfiltration"
    ],
    "vendor": "Anthropic"
  },
  {
    "id": "auto-ea90d771f2",
    "date": "2026-04-23",
    "source": "CISA alerts",
    "url": "https://www.cisa.gov/news-events/alerts/2026/04/23/cisa-adds-one-known-exploited-vulnerability-catalog",
    "headline": "CISA Adds One Known Exploited Vulnerability to Catalog",
    "summary": "CISA added CVE-2026-39987, a remote code execution vulnerability in Marimo, to its Known Exploited Vulnerabilities Catalog based on evidence of active exploitation in the wild.",
    "severity": "critical",
    "threats": [
      "insecure-output-handling"
    ],
    "vendor": "Marimo"
  },
  {
    "id": "auto-6d5f21a944",
    "date": "2026-04-23",
    "source": "BleepingComputer",
    "url": "https://www.bleepingcomputer.com/news/security/bitwarden-cli-npm-package-compromised-to-steal-developer-credentials/",
    "headline": "Bitwarden CLI npm package compromised to steal developer credentials",
    "summary": "The @bitwarden/cli npm package was compromised on April 22, 2026, with attackers uploading a malicious version (2026.4.0) containing credential-stealing payload. The package remained available for approximately 1.5 hours before removal by npm.",
    "severity": "critical",
    "threats": [
      "supply-chain"
    ],
    "vendor": "Bitwarden CLI"
  },
  {
    "id": "auto-6efd8aabaa",
    "date": "2026-04-23",
    "source": "The Hacker News",
    "url": "https://thehackernews.com/2026/04/bitwarden-cli-compromised-in-ongoing.html",
    "headline": "Bitwarden CLI Compromised in Ongoing Checkmarx Supply Chain Campaign",
    "summary": "Bitwarden CLI package @bitwarden/cli@2026.4.0 was compromised as part of an ongoing supply chain campaign. Malicious code was injected into bw1.js within the package contents, discovered by JFrog and Socket researchers.",
    "severity": "critical",
    "threats": [
      "supply-chain"
    ],
    "vendor": "Bitwarden CLI"
  },
  {
    "id": "auto-8e94f540ed",
    "date": "2026-04-23",
    "source": "The Hacker News",
    "url": "https://thehackernews.com/2026/04/vercel-finds-more-compromised-accounts.html",
    "headline": "Vercel Finds More Compromised Accounts in Context.ai-Linked Breach",
    "summary": "Vercel disclosed a confirmed breach affecting additional customer accounts through unauthorized internal system access. The compromise was discovered during an expanded investigation following initial indicators linked to Context.ai.",
    "severity": "high",
    "threats": [
      "identity-and-authorization",
      "data-exfiltration"
    ],
    "vendor": "Vercel"
  },
  {
    "id": "auto-f9be8dd752",
    "date": "2026-04-22",
    "source": "The Hacker News",
    "url": "https://thehackernews.com/2026/04/malicious-kics-docker-images-and-vs.html",
    "headline": "Malicious KICS Docker Images and VS Code Extensions Hit Checkmarx Supply Chain",
    "summary": "Malicious Docker images were pushed to the official checkmarx/kics Docker Hub repository, with threat actors overwriting existing version tags (v2.1.20, alpine) and introducing a fake v2.1.21 release. The compromise affected the official supply chain artifact.",
    "severity": "critical",
    "threats": [
      "supply-chain"
    ],
    "vendor": "Checkmarx KICS"
  },
  {
    "id": "auto-b08cf167d8",
    "date": "2026-04-22",
    "source": "DarkReading",
    "url": "https://www.darkreading.com/cyberattacks-data-breaches/dprk-fake-job-scams-self-propagate-contagious-interview",
    "headline": "DPRK Fake Job Scams Self-Propagate in 'Contagious Interview'",
    "summary": "North Korean threat actors evolved their \"Contagious Interview\" social engineering attack into a self-propagating supply-chain worm. Compromised developer repositories spread remote access trojans (RATs) across code repositories and development environments.",
    "severity": "high",
    "threats": [
      "supply-chain"
    ]
  },
  {
    "id": "auto-46ba971686",
    "date": "2026-04-21",
    "source": "CISA alerts",
    "url": "https://www.cisa.gov/news-events/ics-advisories/icsa-26-111-12",
    "headline": "SenseLive X3050",
    "summary": "CISA advisory for SenseLive X3050 V1.523 discloses 11 CVEs including authentication bypass, hardcoded credentials, and missing authorization controls in the web management interface. Successful exploitation allows complete device takeover.",
    "severity": "critical",
    "threats": [
      "identity-and-authorization"
    ],
    "vendor": "SenseLive X3050"
  },
  {
    "id": "auto-38733954d8",
    "date": "2026-04-21",
    "source": "DarkReading",
    "url": "https://www.darkreading.com/vulnerabilities-threats/google-fixes-critical-rce-flaw-ai-based-antigravity-tool",
    "headline": "Google Fixes Critical RCE Flaw in AI-Based 'Antigravity' Tool",
    "summary": "Google patched a critical RCE vulnerability in its agentic IDE Antigravity. A prompt-injection flaw in filesystem operations allowed sandbox escape and arbitrary code execution; researchers demonstrated a proof-of-concept exploit.",
    "severity": "critical",
    "threats": [
      "prompt-injection",
      "insecure-output-handling"
    ],
    "vendor": "Google Antigravity"
  },
  {
    "id": "auto-67ca6ef072",
    "date": "2026-04-20",
    "source": "DarkReading",
    "url": "https://www.darkreading.com/application-security/vercel-employees-ai-tool-access-data-breach",
    "headline": "Vercel Employee's AI Tool Access Led to Data Breach",
    "summary": "Vercel was breached via compromised OAuth tokens stolen from Context.ai, a third-party AI tool vendor. Threat actors leveraged the stolen token to gain unauthorized access to Vercel systems. The incident illustrates OAuth token compromise as a lateral-movement vector in AI tool supply chains.",
    "severity": "high",
    "threats": [
      "supply-chain",
      "identity-and-authorization"
    ],
    "vendor": "Context.ai"
  },
  {
    "id": "auto-cf9e60bb02",
    "date": "2026-04-17",
    "source": "Embrace The Red (Johann Rehberger)",
    "url": "https://embracethered.com/blog/posts/2026/breaking-opus-4.7-with-chatgpt/",
    "headline": "Breaking Opus 4.7 with ChatGPT (Hacking Claude's Memory)",
    "summary": "A researcher demonstrated an indirect prompt injection attack against Claude Opus 4.7 using a ChatGPT-generated adversarial image that hijacked the model's memory tool to persist false memories across sessions. The attack circumvented Opus 4.6+ alignment improvements through puzzle-based reasoning challenges.",
    "severity": "high",
    "threats": [
      "prompt-injection",
      "data-exfiltration"
    ],
    "vendor": "Anthropic Claude Opus 4.7"
  },
  {
    "id": "auto-cc8adfa06b",
    "date": "2026-04-15",
    "source": "Ars Technica security",
    "url": "https://arstechnica.com/gadgets/2026/04/totalrecall-reloaded-tool-finds-a-side-entrance-to-windows-11s-recall-database/",
    "headline": "\"TotalRecall Reloaded\" tool finds a side entrance to Windows 11's Recall database",
    "summary": "A tool called \"TotalRecall Reloaded\" discovered a method to access Windows 11's Recall screenshot database through an alternate attack surface, potentially allowing unauthorized extraction of sensitive captured data without proper authentication.",
    "severity": "high",
    "threats": [
      "data-exfiltration",
      "insecure-output-handling"
    ],
    "vendor": "Microsoft Windows 11 Recall"
  },
  {
    "id": "auto-1a8c08efec",
    "date": "2026-04-06",
    "source": "Bishop Fox blog",
    "url": "https://bishopfox.com/blog/delivered-by-trust-what-the-axios-supply-chain-attack-means-for-security-leaders",
    "headline": "Delivered by Trust: What the Axios Supply Chain Attack Means for Security Leaders",
    "summary": "On March 31, 2026, the Axios NPM package was compromised in a supply chain attack. Malicious versions 1.14.1 and 0.30.4 included a trojanized dependency that executed during installation and deployed platform-specific remote access trojans from attacker-controlled infrastructure, enabling persistent remote access, command execution, and data exfiltration.",
    "severity": "critical",
    "threats": [
      "supply-chain",
      "data-exfiltration"
    ],
    "vendor": "Axios (NPM package)"
  },
  {
    "id": "auto-bafb7f75d8",
    "date": "2026-04-03",
    "source": "Ars Technica security",
    "url": "https://arstechnica.com/security/2026/04/heres-why-its-prudent-for-openclaw-users-to-assume-compromise/",
    "headline": "OpenClaw gives users yet another reason to be freaked out about security",
    "summary": "OpenClaw, a viral agentic tool with 347k GitHub stars, had a recently fixed vulnerability enabling excessive resource access. Security practitioners have warned for over a month about the security implications of the tool's broad system and application control design.",
    "severity": "high",
    "threats": [
      "excessive-agency",
      "identity-and-authorization"
    ],
    "vendor": "OpenClaw"
  }
];
