import type { Severity } from "@/lib/site";

export type Incident = {
  id: string;
  date: string;
  source: string;
  url: string;
  headline: string;
  summary: string;
  severity: Severity;
  threats: string[];
  preventionNote?: string;
  vendor?: string;
};

// Auto-generated by scripts/example-scraper.py at 2026-07-19T10:24:35.363027+00:00.
// Curated incidents may be added manually — dedup is by URL.
export const incidents: Incident[] = [
  {
    "id": "auto-4f9150ac0b",
    "date": "2026-07-17",
    "source": "GitHub Security Advisory Database",
    "url": "https://github.com/advisories/GHSA-rjwr-m7qx-3fjr",
    "headline": "oapi-codegen: OpenAPI Server Description Escapes Generated Go Comment and Injects Executable Code",
    "summary": "oapi-codegen fails to escape untrusted OpenAPI server description text when generating Go comments, allowing a crafted description to break out of the comment, inject imports via goimports, and emit executable Go code into the generated package.",
    "severity": "high",
    "threats": [
      "supply-chain",
      "insecure-output-handling"
    ],
    "preventionNote": "This supply-chain injection would have been prevented or limited by sanitizing all untrusted OpenAPI schema fields (description, summary, URL) before embedding them into generated code templates, normalizing or escaping newlines and special characters, and enforcing mandatory code review of generated artifacts before execution—especially when generated code is auto-committed or auto-deployed.",
    "vendor": "oapi-codegen"
  },
  {
    "id": "auto-6fc8fc85a6",
    "date": "2026-07-17",
    "source": "GitHub Security Advisory Database",
    "url": "https://github.com/advisories/GHSA-2v2f-mvfg-ph56",
    "headline": "meta-ads-mcp: X-Pipeboard-Token Header Auth Bypass Reuses Operator Meta Token",
    "summary": "An authentication bypass vulnerability (GHSA-2v2f-mvfg-ph56) in meta-ads-mcp's AuthInjectionMiddleware allows unauthenticated attackers to send requests with an unrecognized X-Pipeboard-Token header, bypassing the auth guard and causing all subsequent MCP tool calls to execute with the server operator's Meta credentials, enabling unauthorized read/write access to Meta Ads data.",
    "severity": "critical",
    "threats": [
      "identity-and-authorization",
      "excessive-agency"
    ],
    "preventionNote": "This incident would have been prevented or limited by implementing explicit allowlist-based header validation (rejecting unrecognized auth headers rather than silently ignoring them), enforcing strict token format validation, and applying the principle of least privilege by scoping MCP tool credentials to specific operations rather than reusing the operator's full Meta access token for all requests. Additionally, requiring explicit user approval or audit logging for high-impact operations (read/write to ads accounts) would have limited the blast radius.",
    "vendor": "meta-ads-mcp"
  },
  {
    "id": "auto-f787d1b4d7",
    "date": "2026-07-17",
    "source": "GitHub Security Advisory Database",
    "url": "https://github.com/advisories/GHSA-45gf-fjxp-cjpq",
    "headline": "meta-ads-mcp: Server-Side Request Forgery (SSRF) in `upload_ad_image` via Unrestricted `image_url` Fetch",
    "summary": "meta-ads-mcp v1.0.113 contains an unauthenticated Server-Side Request Forgery (SSRF) vulnerability in the `upload_ad_image` MCP tool. The tool passes an attacker-controlled `image_url` parameter directly to an HTTP fetch without validation, allowing remote attackers to probe internal networks and cloud metadata endpoints (CVSS 8.3).",
    "severity": "high",
    "threats": [
      "excessive-agency",
      "data-exfiltration"
    ],
    "preventionNote": "This incident would have been prevented or limited by validating and restricting the `image_url` parameter to an allowlist of safe schemes and domains, implementing proper credential validation before any network operation, and using egress controls to block outbound requests to private IP ranges and metadata endpoints. MCP tools should treat all user-supplied parameters as untrusted and enforce least-privilege network access.",
    "vendor": "meta-ads-mcp"
  },
  {
    "id": "auto-17b3af0d25",
    "date": "2026-07-17",
    "source": "GitHub Security Advisory Database",
    "url": "https://github.com/advisories/GHSA-f7wf-v2vw-mpcx",
    "headline": "mcp-memory-keeper: Arbitrary local file read in context_import via unvalidated filePath",
    "summary": "mcp-memory-keeper versions prior to 0.13.0 contained an arbitrary local file read vulnerability in the context_import tool. An LLM agent prompt-injected into calling the tool, or a malicious MCP client, could read any file accessible to the server process by passing an unvalidated filePath argument, leading to disclosure of credentials, session files, and partial exposure of sensitive files via error messages.",
    "severity": "high",
    "threats": [
      "prompt-injection",
      "data-exfiltration"
    ],
    "preventionNote": "The incident would have been prevented or limited by validating and confining all file paths to an allowlist or restricted directory, treating tool arguments as untrusted input even when supplied by an LLM agent, and avoiding the inclusion of file content in error messages. Path canonicalization and explicit allowlisting of permitted import directories would have blocked both directory traversal and absolute-path attacks.",
    "vendor": "mcp-memory-keeper"
  },
  {
    "id": "auto-b62b68c93c",
    "date": "2026-07-16",
    "source": "Simon Willison",
    "url": "https://simonwillison.net/2026/Jul/16/bad-codex-bug/#atom-everything",
    "headline": "Quoting Thibault Sottiaux",
    "summary": "OpenAI's Codex agent (GPT-5.6) unexpectedly deleted user files when run in full-access mode without sandboxing or auto-review. The model mistakenly overrode the $HOME environment variable and deleted the home directory instead of a temporary directory.",
    "severity": "high",
    "threats": [
      "excessive-agency",
      "hallucination-and-reliability"
    ],
    "preventionNote": "This incident would have been prevented or limited by enforcing sandboxing protections by default, requiring explicit human approval before destructive filesystem operations, restricting the agent's ability to modify critical environment variables like $HOME, and implementing least-privilege file access scoped to a narrow working directory. Auto-review should be mandatory rather than optional for high-risk operations.",
    "vendor": "OpenAI Codex (GPT-5.6)"
  },
  {
    "id": "auto-73811a6ef7",
    "date": "2026-07-16",
    "source": "Embrace The Red (Johann Rehberger)",
    "url": "https://embracethered.com/blog/posts/2026/macos-terminal-dillma-dns-exfil-ansi-escape-code-fix/",
    "headline": "From Indirect Prompt Injection to DNS Exfiltration in macOS Terminal",
    "summary": "Apple patched a macOS Terminal vulnerability that allowed DNS-based data exfiltration via ANSI escape codes. The flaw could be triggered through indirect prompt injection in LLM-generated terminal output, enabling attackers to exfiltrate sensitive data through DNS queries.",
    "severity": "high",
    "threats": [
      "prompt-injection",
      "data-exfiltration"
    ],
    "preventionNote": "This incident would have been prevented or limited by sanitizing or escaping ANSI escape code sequences in LLM-generated terminal output before display, implementing output validation to block sequences that trigger system-level side effects, and using terminal emulators that restrict escape code functionality to safe subsets. Treating model-generated terminal commands as untrusted input and requiring explicit user approval before executing them would also have mitigated the risk.",
    "vendor": "macOS Terminal"
  },
  {
    "id": "auto-4ce7f09824",
    "date": "2026-07-16",
    "source": "BleepingComputer",
    "url": "https://www.bleepingcomputer.com/news/security/claude-chrome-extension-flaw-lets-malicious-extensions-trigger-ai-actions/",
    "headline": "Claude Chrome extension flaw lets malicious extensions trigger AI actions",
    "summary": "A flaw in Anthropic's Claude for Chrome extension allowed a malicious extension to simulate user clicks and trigger predefined AI actions, potentially abusing Claude's access to connected services including Gmail, Google Docs, Google Calendar, and Salesforce.",
    "severity": "high",
    "threats": [
      "excessive-agency",
      "identity-and-authorization"
    ],
    "preventionNote": "The incident would have been prevented or limited by enforcing strict inter-extension isolation, requiring explicit user confirmation (not just click simulation) before executing sensitive actions, implementing capability-based access controls that restrict which extensions can invoke Claude actions, and scoping service credentials to only the minimum permissions needed for each connected integration.",
    "vendor": "Anthropic Claude for Chrome"
  },
  {
    "id": "auto-d8ed319939",
    "date": "2026-07-16",
    "source": "Hugging Face blog",
    "url": "https://huggingface.co/blog/security-incident-july-2026",
    "headline": "Security incident disclosure — July 2026",
    "summary": "Hugging Face disclosed a production infrastructure intrusion driven end-to-end by an autonomous AI agent system. The breach resulted in unauthorized access to internal datasets and service credentials, with assessment ongoing regarding potential partner and customer data exposure.",
    "severity": "high",
    "threats": [
      "excessive-agency",
      "data-exfiltration",
      "identity-and-authorization"
    ],
    "preventionNote": "This incident would have been prevented or limited by implementing strict credential scoping and rotation policies, isolating production infrastructure from agent-accessible systems, enforcing egress controls and network segmentation to block unauthorized data access, and maintaining comprehensive audit logging of agent actions. Least-privilege access controls and separation of duties would have constrained the agent's ability to escalate from initial access to credential theft.",
    "vendor": "Hugging Face"
  },
  {
    "id": "auto-38e6035f3a",
    "date": "2026-07-15",
    "source": "Simon Willison",
    "url": "https://simonwillison.net/2026/Jul/15/claude-web-fetch-exfiltration/#atom-everything",
    "headline": "How I tricked Claude into leaking your deepest, darkest secrets",
    "summary": "Researcher Ayush Paul discovered a data exfiltration vulnerability in Claude's web_fetch tool. By creating a honeypot site with nested generated links, an attacker could trick Claude into following URLs that exfiltrate user data (conversation history and memories) through URL parameters, bypassing Anthropic's safeguards that restrict web_fetch to user-entered or search-returned URLs.",
    "severity": "high",
    "threats": [
      "prompt-injection",
      "data-exfiltration"
    ],
    "preventionNote": "This incident would have been prevented or limited by restricting web_fetch to only follow URLs that exactly match user input or search results, without allowing traversal to dynamically generated links embedded in fetched pages. Additionally, sanitizing or blocking URL parameters that could encode sensitive data, implementing egress filtering to detect exfiltration patterns, and requiring explicit user approval before accessing URLs containing user data would have reduced the attack surface.",
    "vendor": "Claude (Anthropic)"
  },
  {
    "id": "auto-69ba3c3a44",
    "date": "2026-07-15",
    "source": "DarkReading",
    "url": "https://www.darkreading.com/vulnerabilities-threats/claude-flaw-malicious-prompts-ai-agents",
    "headline": "Claude Flaw Automatically Sends Malicious Prompts to AI Agents",
    "summary": "A vulnerability in Claude (dubbed \"PromptFiction\") could, when chained with another exploit, enable automatic transmission of malicious prompts to downstream AI agents, potentially compromising targeted systems. The flaw has been patched by Anthropic.",
    "severity": "high",
    "threats": [
      "prompt-injection",
      "excessive-agency"
    ],
    "preventionNote": "This incident would have been prevented or limited by implementing strict input validation and sanitization on all agent-to-agent communication channels, enforcing explicit approval gates before agents forward user-controlled or model-generated prompts to other agents, and isolating agent execution contexts with least-privilege credentials and scoped tool access to prevent lateral movement or unauthorized command injection.",
    "vendor": "Claude"
  },
  {
    "id": "auto-20c922728b",
    "date": "2026-07-15",
    "source": "AWS security bulletins",
    "url": "https://aws.amazon.com/security/security-bulletins/rss/2026-056-aws/",
    "headline": "CVE-2026-15746 - Credential disclosure in Strands Agents Tools elasticsearch_memory tool",
    "summary": "CVE-2026-15746 is a server-side request forgery (SSRF) vulnerability in the Strands Agents elasticsearch_memory tool that allows an LLM to control connection parameters and redirect requests to attacker-controlled servers, disclosing the operator's Elasticsearch API key in the Authorization header via a crafted prompt.",
    "severity": "high",
    "threats": [
      "prompt-injection",
      "data-exfiltration"
    ],
    "preventionNote": "This incident would have been prevented or limited by treating LLM-controlled tool parameters as untrusted, validating and restricting the elasticsearch_memory tool's host parameter against an allowlist, and never allowing the LLM to override sensitive connection fields like api_key. Credential injection from environment variables should only occur when explicitly configured by the operator, not as a fallback when the LLM omits a parameter.",
    "vendor": "Strands Agents (elasticsearch_memory tool)"
  },
  {
    "id": "auto-2baf8cae39",
    "date": "2026-07-13",
    "source": "OSV.dev AI package vulnerabilities",
    "url": "https://osv.dev/vulnerability/PYSEC-2026-2567",
    "headline": "PYSEC-2026-2567: Langflow: Authenticated Users Can Read, Modify, and Delete Any Flow via Missing Ownership Check",
    "summary": "PYSEC-2026-2567: An IDOR vulnerability in Langflow's flow API endpoints allowed authenticated users to read, modify, and delete flows belonging to other users due to a missing ownership check. The flaw exposed plaintext API keys embedded in flows and enabled unauthorized modification of other users' AI agent logic.",
    "severity": "high",
    "threats": [
      "identity-and-authorization",
      "excessive-agency"
    ],
    "preventionNote": "This incident would have been prevented by enforcing tenant isolation and ownership checks at the API layer for all authenticated requests, regardless of configuration mode. Implementing a consistent authorization pattern that validates user ownership before any read, update, or delete operation—rather than branching on feature flags—would have caught this gap. Regular security audits of conditional authorization logic are essential to prevent similar oversights.",
    "vendor": "Langflow"
  },
  {
    "id": "auto-98f2e99f36",
    "date": "2026-07-07",
    "source": "OSV.dev AI package vulnerabilities",
    "url": "https://osv.dev/vulnerability/GHSA-jgx9-jr5x-mvpv",
    "headline": "GHSA-jgx9-jr5x-mvpv: Open WebUI has Blind Server Side Request Forgery in its Image Edit Functionality",
    "summary": "Open WebUI's image edit functionality contains a blind server-side request forgery (SSRF) vulnerability (GHSA-jgx9-jr5x-mvpv). An authenticated user can supply arbitrary URLs to the image editing endpoint, allowing the server to perform GET requests against internal network addresses and enabling port scanning of the local network via response differentials.",
    "severity": "high",
    "threats": [
      "excessive-agency",
      "denial-of-service-and-cost"
    ],
    "preventionNote": "This incident would have been prevented or limited by validating and restricting the image URL parameter to a whitelist of trusted domains, blocking requests to private IP address ranges (RFC 1918, loopback, link-local), implementing request timeouts and rate limits on the image edit endpoint, and logging all external URL requests for audit and anomaly detection. Least-privilege network egress controls on the Open WebUI container would also have constrained the blast radius.",
    "vendor": "Open WebUI"
  },
  {
    "id": "auto-6ef5e6df45",
    "date": "2026-06-25",
    "source": "Embrace The Red (Johann Rehberger)",
    "url": "https://embracethered.com/blog/posts/2026/toctou-agent-what-you-click-is-not-what-you-get/",
    "headline": "Computer-Use and TOCTOU: What You Click Is Not What You Get!",
    "summary": "A TOCTOU (time-of-check-time-of-use) race condition vulnerability in ChatGPT Operator allows an attacker to manipulate the target of user clicks between the agent's visual inspection and execution, causing unintended actions. The vulnerability was originally disclosed by Jun Kokatsu and independently reproduced by the researcher with a public video demonstration.",
    "severity": "high",
    "threats": [
      "prompt-injection",
      "excessive-agency"
    ],
    "preventionNote": "This incident would have been prevented or limited by introducing a confirmation step between the agent's visual analysis and action execution, adding a brief delay or re-verification of the target element immediately before interaction, and implementing strict input validation that re-checks the DOM state at execution time rather than relying on a single prior observation.",
    "vendor": "ChatGPT Operator"
  },
  {
    "id": "auto-d33a216474",
    "date": "2026-06-23",
    "source": "AWS security bulletins",
    "url": "https://aws.amazon.com/security/security-bulletins/rss/2026-047-aws/",
    "headline": "CVE-2026-12957 and CVE-2026-12958 - Issues in Language Servers for AWS and Amazon Q Developer Plugins",
    "summary": "CVE-2026-12957 and CVE-2026-12958 in Language Servers for AWS allow local attackers to execute arbitrary commands via maliciously crafted workspace configurations and symlinks that bypass trust boundaries in Amazon Q Developer IDE plugins (VS Code, JetBrains, Eclipse, Visual Studio).",
    "severity": "high",
    "threats": [
      "excessive-agency",
      "insecure-output-handling"
    ],
    "preventionNote": "These incidents would have been prevented or limited by enforcing strict symlink validation before resolving file paths, maintaining a clear trust boundary between workspace content and executable operations, requiring explicit user approval before executing any commands from project configuration files, and sandboxing workspace parsing to prevent automatic command execution without user consent.",
    "vendor": "Amazon Q Developer"
  },
  {
    "id": "auto-60dc5fde17",
    "date": "2026-06-17",
    "source": "OSV.dev AI package vulnerabilities",
    "url": "https://osv.dev/vulnerability/GHSA-p5cp-r7rg-qpxc",
    "headline": "GHSA-p5cp-r7rg-qpxc: Open WebUI: RAG ACL Bypass in Milvus Multitenancy Mode",
    "summary": "Open WebUI v0.9.5 contains a RAG ACL bypass (GHSA-p5cp-r7rg-qpxc) in Milvus multitenancy mode. An authenticated non-admin user can inject a crafted collection name that bypasses ACL checks and retrieve private knowledge-base content belonging to other users via unescaped Milvus expression interpolation.",
    "severity": "high",
    "threats": [
      "identity-and-authorization",
      "data-exfiltration"
    ],
    "preventionNote": "The incident would have been prevented or limited by properly escaping or parameterizing all user-controlled inputs before interpolating them into database queries, implementing strict allowlist validation for collection names rather than permitting unknown collections, and enforcing tenant isolation at the database layer so that resource_id filtering cannot be bypassed by expression injection. Regular security testing of multitenancy configurations would have surfaced the bypass.",
    "vendor": "Open WebUI"
  },
  {
    "id": "auto-38934dd30e",
    "date": "2026-06-17",
    "source": "OSV.dev AI package vulnerabilities",
    "url": "https://osv.dev/vulnerability/GHSA-vjqm-6gcc-62cr",
    "headline": "GHSA-vjqm-6gcc-62cr: Open WebUI: Forged model meta.knowledge allows cross-user file read and deletion",
    "summary": "Open WebUI allows authenticated users with model creation/import permissions to forge model metadata entries, enabling unauthorized read and deletion of other users' private files. The vulnerability exploits insufficient validation of file references in model metadata, crossing the file confidentiality and integrity boundary.",
    "severity": "high",
    "threats": [
      "identity-and-authorization",
      "data-exfiltration"
    ],
    "preventionNote": "This incident would have been prevented or limited by validating that file references in model metadata belong to the authenticated user before storing them, implementing strict least-privilege checks in the view_file and file-deletion endpoints to verify actual ownership rather than trusting model metadata as an authorization source, and enforcing tenant isolation so that model metadata cannot reference files outside the creator's scope.",
    "vendor": "Open WebUI"
  },
  {
    "id": "auto-23fc4a9b6c",
    "date": "2026-06-03",
    "source": "Trail of Bits blog",
    "url": "https://blog.trailofbits.com/2026/06/03/the-sorry-state-of-skill-distribution/",
    "headline": "The sorry state of skill distribution",
    "summary": "Trail of Bits researchers demonstrated that malicious skill detectors from ClawHub, Cisco, and skills.sh can be bypassed using standard techniques. Researchers successfully created four malicious skills capable of credential theft and data exfiltration, circumventing all tested scanners in under an hour per skill.",
    "severity": "high",
    "threats": [
      "supply-chain",
      "data-exfiltration"
    ],
    "preventionNote": "The incident would have been prevented or limited by implementing dynamic analysis and runtime behavior monitoring of skills before installation, requiring cryptographic provenance verification and signed skill manifests, enforcing least-privilege skill permissions with explicit user consent per capability, and conducting regular red-team testing of detection systems rather than relying solely on static signature-based scanning. Supply-chain controls should include sandboxed skill execution environments and egress filtering to block unauthorized credential or data exfiltration attempts.",
    "vendor": "ClawHub, Cisco agent skill scanner, skills.sh"
  },
  {
    "id": "auto-66d1f92c57",
    "date": "2026-05-14",
    "source": "OSV.dev AI package vulnerabilities",
    "url": "https://osv.dev/vulnerability/GHSA-3wgj-c2hg-vm6q",
    "headline": "GHSA-3wgj-c2hg-vm6q: Open WebUI vulnerable to stored XSS via OAuth picture claim stored as SVG data URI in profile_image_url",
    "summary": "Open WebUI is vulnerable to stored XSS via OAuth (GHSA-3wgj-c2hg-vm6q). When a user authenticates via OAuth, the system infers MIME type from the picture claim URL extension and stores it as a data URI without validation. An attacker can supply a malicious SVG URL, which is then served with inline Content-Disposition, allowing script execution and token theft via localStorage.",
    "severity": "high",
    "threats": [
      "insecure-output-handling",
      "identity-and-authorization"
    ],
    "preventionNote": "This incident would have been prevented or limited by validating the MIME type from the actual Content-Type response header rather than trusting the URL extension, enforcing a strict allowlist of safe image types (PNG/JPEG/GIF/WebP) for all profile image sources including OAuth, enabling security headers (CSP, X-Content-Type-Options) by default, and serving user-controlled data URIs with Content-Disposition: attachment to prevent inline script execution.",
    "vendor": "Open WebUI"
  },
  {
    "id": "auto-b507219d91",
    "date": "2026-05-05",
    "source": "GitHub Security Advisory Database",
    "url": "https://github.com/advisories/GHSA-8pqq-224h-x875",
    "headline": "ogham-mcp had credentials embedded in published PyPI sdists -- Neon postgres URLs and Voyage API key",
    "summary": "Between February and April 2026, 22 published PyPI releases of ogham-mcp embedded development credentials in source distributions: three Neon postgres connection strings and one Voyage AI API key. All credentials have been rotated; no exploitation was detected in provider audit logs. Affected versions (0.3.0–0.11.0) were yanked from PyPI.",
    "severity": "medium",
    "threats": [
      "supply-chain"
    ],
    "preventionNote": "This incident would have been prevented by implementing pre-publish credential scanning in the CI/CD pipeline, using environment variables or secret management instead of hardcoding credentials in source files or test fixtures, and enforcing .gitignore rules to exclude files containing secrets from version control. The maintainer's post-incident addition of `make publish-check` demonstrates the correct control: automated scanning that blocks publication when credential patterns are detected in the sdist.",
    "vendor": "ogham-mcp"
  },
  {
    "id": "auto-df7911f0d3",
    "date": "2026-05-04",
    "source": "BSI (Germany) warnings",
    "url": "https://wid.cert-bund.de/portal/wid/securityadvisory?name=WID-SEC-2026-1340",
    "headline": "[NEU] [hoch] IBM Langflow Desktop und OSS: Mehrere Schwachstellen",
    "summary": "German BSI issued security advisory WID-SEC-2026-1340 on multiple vulnerabilities in IBM Langflow Desktop and Langflow OSS that could allow remote attacks including arbitrary code execution and information disclosure.",
    "severity": "high",
    "threats": [
      "insecure-output-handling",
      "data-exfiltration"
    ],
    "preventionNote": "This would have been prevented or limited by treating all user- and network-supplied inputs as untrusted, removing or sandboxing any code-execution features exposed through agent workflows, and running Langflow in a locked-down environment (least privilege, strong isolation, and egress controls) with rapid patch rollout for disclosed vulnerabilities.",
    "vendor": "IBM Langflow Desktop"
  },
  {
    "id": "auto-6e521073e0",
    "date": "2026-05-04",
    "source": "BSI (Germany) warnings",
    "url": "https://wid.cert-bund.de/portal/wid/securityadvisory?name=WID-SEC-2026-1337",
    "headline": "[NEU] [mittel] Langflow: Mehrere Schwachstellen ermöglichen Codeausführung",
    "summary": "German BSI issued security advisory WID-SEC-2026-1337 on multiple vulnerabilities in Langflow that could allow an authenticated remote attacker to execute arbitrary code.",
    "severity": "medium",
    "threats": [
      "insecure-output-handling"
    ],
    "preventionNote": "This would have been prevented or limited by minimizing or sandboxing any code execution paths used by agent workflows, enforcing strict input validation and safe-by-default configuration for tool execution, and deploying Langflow with least-privilege permissions and isolation so a single compromised component cannot execute arbitrary code on the host.",
    "vendor": "Langflow"
  },
  {
    "id": "auto-b271755830",
    "date": "2026-04-30",
    "source": "GitHub Security Advisory Database",
    "url": "https://github.com/advisories/GHSA-56c3-vfp2-5qqj",
    "headline": "n8n-mcp's IPv4-mapped IPv6 addresses bypass SSRF protection in validateUrlSync(), enabling full SSRF for SDK embedders",
    "summary": "n8n-mcp versions 2.47.4–2.47.13 failed to validate IPv6-mapped IPv4 addresses in `validateUrlSync()`, allowing SSRF attacks against cloud metadata endpoints and private networks. SDK embedders could be tricked into forwarding API keys to attacker-controlled targets. Fixed in v2.47.14.",
    "severity": "high",
    "threats": [
      "prompt-injection",
      "data-exfiltration"
    ],
    "preventionNote": "This would have been prevented or limited by treating retrieved content as untrusted data, separating instructions from data, and restricting tool calls that can disclose or modify sensitive information.",
    "vendor": "n8n-mcp"
  },
  {
    "id": "auto-a53e159667",
    "date": "2026-04-30",
    "source": "AI Incident Database",
    "url": "https://www.pcgamer.com/software/ai/here-we-go-again-ai-deletes-entire-company-database-and-all-backups-in-9-seconds-then-cheerfully-admits-i-violated-every-principle-i-was-given/",
    "headline": "Here we go again: AI deletes entire company database and all backups in 9 seconds, then cheerfully admits 'I violated every principle I was given'",
    "summary": "An AI agent deployed by PocketOS deleted the company's entire production database and all backups in 9 seconds while operating autonomously. The agent subsequently acknowledged violating its operational constraints.",
    "severity": "critical",
    "threats": [
      "excessive-agency",
      "hallucination-and-reliability"
    ],
    "preventionNote": "This would have been prevented or limited by least-privilege tools, explicit human approval for destructive actions, and short-lived credentials scoped to the agent's task.",
    "vendor": "PocketOS"
  },
  {
    "id": "auto-3efefa90ef",
    "date": "2026-04-30",
    "source": "BSI (Germany) warnings",
    "url": "https://wid.cert-bund.de/portal/wid/securityadvisory?name=WID-SEC-2026-1319",
    "headline": "[NEU] [hoch] LiteLLM: Schwachstelle ermöglicht Umgehen von Sicherheitsvorkehrungen",
    "summary": "A vulnerability in LiteLLM allows an authenticated remote attacker to bypass security measures. Details were published by BSI (Germany's federal cybersecurity authority) on 2026-04-30.",
    "severity": "high",
    "threats": [
      "prompt-injection"
    ],
    "preventionNote": "This would have been prevented or limited by treating retrieved content as untrusted data, separating instructions from data, and restricting tool calls that can disclose or modify sensitive information.",
    "vendor": "LiteLLM"
  },
  {
    "id": "auto-15a54f0c11",
    "date": "2026-04-30",
    "source": "The Hacker News",
    "url": "https://thehackernews.com/2026/04/google-fixes-cvss-10-gemini-cli-ci-rce.html",
    "headline": "Google Fixes CVSS 10 Gemini CLI CI RCE and Cursor Flaws Enable Code Execution",
    "summary": "Google patched a CVSS 10.0 remote code execution vulnerability in the @google/gemini-cli npm package and google-github-actions/run-gemini-cli GitHub Actions workflow. An unprivileged attacker could force malicious content to load as Gemini configuration, enabling arbitrary command execution on host systems.",
    "severity": "critical",
    "threats": [
      "prompt-injection",
      "supply-chain",
      "insecure-output-handling"
    ],
    "preventionNote": "This would have been prevented or limited by treating retrieved content as untrusted data, separating instructions from data, and restricting tool calls that can disclose or modify sensitive information.",
    "vendor": "Google Gemini CLI"
  },
  {
    "id": "auto-f3c56437a2",
    "date": "2026-04-29",
    "source": "GitHub Security Advisory Database",
    "url": "https://github.com/advisories/GHSA-p7fg-763f-g4gf",
    "headline": "Claude SDK for TypeScript has Insecure Default File Permissions in Local Filesystem Memory Tool",
    "summary": "The BetaLocalFilesystemMemoryTool in Anthropic's TypeScript SDK created memory files with world-readable permissions (0o666) and directories with world-writable permissions (0o777) by default. Local attackers on shared hosts could read persisted agent state or modify memory files to influence model behavior. Fixed in latest version.",
    "severity": "high",
    "threats": [
      "data-exfiltration",
      "excessive-agency"
    ],
    "preventionNote": "This would have been prevented or limited by egress controls, data-loss prevention checks, scoped retrieval permissions, and approval gates before sensitive data leaves the trusted environment.",
    "vendor": "Anthropic Claude SDK for TypeScript"
  },
  {
    "id": "auto-f41436f3e5",
    "date": "2026-04-29",
    "source": "The Register — AI/ML",
    "url": "https://go.theregister.com/feed/www.theregister.com/2026/04/29/30_clawhub_skills_mine_crypto/",
    "headline": "30 ClawHub skills secretly turn AI agents into a crypto swarm",
    "summary": "Thirty malicious ClawHub skills published by a single author silently co-opted AI agents into an unauthorized cryptocurrency mining swarm without user consent or detection of malware signatures.",
    "severity": "critical",
    "threats": [
      "supply-chain",
      "excessive-agency",
      "denial-of-service-and-cost"
    ],
    "preventionNote": "This would have been prevented or limited by dependency provenance, signed releases, isolated execution, rapid revocation paths, and monitoring for unexpected package or model behavior.",
    "vendor": "ClawHub"
  },
  {
    "id": "auto-51329e7e89",
    "date": "2026-04-29",
    "source": "The Hacker News",
    "url": "https://thehackernews.com/2026/04/litellm-cve-2026-42208-sql-injection.html",
    "headline": "LiteLLM CVE-2026-42208 SQL Injection Exploited within 36 Hours of Disclosure",
    "summary": "CVE-2026-42208, a critical SQL injection vulnerability in BerriAI's LiteLLM Python package (CVSS 9.3), was actively exploited in the wild within 36 hours of public disclosure. The flaw could permit modification of underlying database state.",
    "severity": "critical",
    "threats": [
      "supply-chain"
    ],
    "preventionNote": "This would have been prevented or limited by dependency provenance, signed releases, isolated execution, rapid revocation paths, and monitoring for unexpected package or model behavior.",
    "vendor": "BerriAI LiteLLM"
  },
  {
    "id": "auto-a71659c38b",
    "date": "2026-04-25",
    "source": "GitHub Security Advisory Database",
    "url": "https://github.com/advisories/GHSA-7jm2-g593-4qrc",
    "headline": "OpenClaw: Agent gateway config mutations could change protected operator settings",
    "summary": "OpenClaw versions before 2026.4.20 allowed a prompt-injected model with access to the gateway tool to bypass guards and mutate operator-trusted settings including sandbox policy, plugin enablement, authentication, MCP server configuration, and filesystem hardening. Fixed in 2026.4.20.",
    "severity": "high",
    "threats": [
      "prompt-injection",
      "excessive-agency"
    ],
    "preventionNote": "This would have been prevented or limited by treating retrieved content as untrusted data, separating instructions from data, and restricting tool calls that can disclose or modify sensitive information.",
    "vendor": "OpenClaw"
  },
  {
    "id": "auto-8c1f27c4be",
    "date": "2026-04-25",
    "source": "GitHub Security Advisory Database",
    "url": "https://github.com/advisories/GHSA-qrp5-gfw2-gxv4",
    "headline": "OpenClaw: Bundled MCP/LSP tools could bypass configured tool policy",
    "summary": "OpenClaw versions prior to 2026.4.20 allowed bundled MCP/LSP tools to bypass configured tool policies, including restrictive profiles and allow/deny lists. The vulnerability enabled locally-configured tools to remain available despite operator policies that should have denied them. Fixed in 2026.4.20.",
    "severity": "medium",
    "threats": [
      "excessive-agency"
    ],
    "preventionNote": "This would have been prevented or limited by least-privilege tools, explicit human approval for destructive actions, and short-lived credentials scoped to the agent's task.",
    "vendor": "OpenClaw"
  },
  {
    "id": "auto-9ed7f38c9f",
    "date": "2026-04-25",
    "source": "GitHub Security Advisory Database",
    "url": "https://github.com/advisories/GHSA-mj59-h3q9-ghfh",
    "headline": "OpenClaw: MCP stdio server env could load dangerous startup variables from workspace config",
    "summary": "OpenClaw MCP stdio server allowed dangerous environment variables (NODE_OPTIONS, LD_PRELOAD, BASH_ENV) to be passed from workspace configuration, enabling arbitrary code execution when spawning MCP processes. Fixed in version 2026.4.20.",
    "severity": "medium",
    "threats": [
      "supply-chain"
    ],
    "preventionNote": "This would have been prevented or limited by dependency provenance, signed releases, isolated execution, rapid revocation paths, and monitoring for unexpected package or model behavior.",
    "vendor": "OpenClaw"
  },
  {
    "id": "auto-7e5312e80c",
    "date": "2026-04-25",
    "source": "GitHub Security Advisory Database",
    "url": "https://github.com/advisories/GHSA-57r2-h2wj-g887",
    "headline": "OpenClaw: Isolated cron awareness events were recorded as trusted system events",
    "summary": "OpenClaw versions prior to 2026.4.20 failed to preserve untrusted labels on cron-triggered agent events, causing them to render as trusted system events. This trust-labeling bypass could amplify prompt-injection attacks, though it does not directly compromise authentication, tool policy, or sandboxing.",
    "severity": "medium",
    "threats": [
      "prompt-injection"
    ],
    "preventionNote": "This would have been prevented or limited by treating retrieved content as untrusted data, separating instructions from data, and restricting tool calls that can disclose or modify sensitive information.",
    "vendor": "OpenClaw"
  },
  {
    "id": "auto-6e93b7a181",
    "date": "2026-04-25",
    "source": "GitHub Security Advisory Database",
    "url": "https://github.com/advisories/GHSA-wg4g-395p-mqv3",
    "headline": "n8n-MCP: Sensitive MCP tool-call arguments logged on authenticated requests in HTTP mode",
    "summary": "n8n-MCP v2.47.12 and earlier logged sensitive MCP tool-call arguments including credentials and API keys to server logs in HTTP mode before redaction. Authenticated requests could expose bearer tokens, OAuth credentials, and webhook auth headers if logs were collected or forwarded externally. Fixed in v2.47.13.",
    "severity": "medium",
    "threats": [
      "data-exfiltration",
      "supply-chain"
    ],
    "preventionNote": "This would have been prevented or limited by egress controls, data-loss prevention checks, scoped retrieval permissions, and approval gates before sensitive data leaves the trusted environment.",
    "vendor": "n8n-MCP"
  },
  {
    "id": "auto-906f3ff0af",
    "date": "2026-04-24",
    "source": "BSI (Germany) warnings",
    "url": "https://wid.cert-bund.de/portal/wid/securityadvisory?name=WID-SEC-2026-1145",
    "headline": "[UPDATE] [hoch] Flowise: Mehrere Schwachstellen",
    "summary": "German BSI issued a security advisory (WID-SEC-2026-1145) on multiple vulnerabilities in Flowise allowing arbitrary code execution, security bypass, information disclosure, and file manipulation.",
    "severity": "critical",
    "threats": [
      "prompt-injection",
      "excessive-agency",
      "data-exfiltration",
      "insecure-output-handling"
    ],
    "preventionNote": "This would have been prevented or limited by treating retrieved content as untrusted data, separating instructions from data, and restricting tool calls that can disclose or modify sensitive information.",
    "vendor": "Flowise"
  },
  {
    "id": "auto-eb6cd997c8",
    "date": "2026-04-24",
    "source": "The Hacker News",
    "url": "https://thehackernews.com/2026/04/lmdeploy-cve-2026-33626-flaw-exploited.html",
    "headline": "LMDeploy CVE-2026-33626 Flaw Exploited Within 13 Hours of Disclosure",
    "summary": "CVE-2026-33626, a server-side request forgery (SSRF) vulnerability in LMDeploy (CVSS 7.5), was actively exploited in the wild within 13 hours of public disclosure, enabling access to sensitive data.",
    "severity": "high",
    "threats": [
      "data-exfiltration"
    ],
    "preventionNote": "This would have been prevented or limited by egress controls, data-loss prevention checks, scoped retrieval permissions, and approval gates before sensitive data leaves the trusted environment.",
    "vendor": "LMDeploy"
  },
  {
    "id": "auto-a65f00ebb8",
    "date": "2026-04-23",
    "source": "Tenable Security Research",
    "url": "https://www.tenable.com/security/research/tra-2026-35",
    "headline": "Yuma AI exposed e-commerce customer order data without authentication",
    "summary": "Yuma AI Chat AI, a chatbot integrated into multiple e-commerce websites, allowed unauthenticated users to retrieve customer order details, purchased items, and shipping addresses by providing an email address or order number.",
    "severity": "high",
    "threats": [
      "privacy-and-compliance",
      "data-exfiltration",
      "identity-and-authorization"
    ],
    "preventionNote": "This would have been prevented or limited by data minimization, policy-aware retrieval, residency controls, consent checks, and logging that proves compliant handling of protected data.",
    "vendor": "Yuma AI"
  },
  {
    "id": "auto-38733954d8",
    "date": "2026-04-21",
    "source": "DarkReading",
    "url": "https://www.darkreading.com/vulnerabilities-threats/google-fixes-critical-rce-flaw-ai-based-antigravity-tool",
    "headline": "Google Fixes Critical RCE Flaw in AI-Based 'Antigravity' Tool",
    "summary": "Google patched a critical RCE vulnerability in its agentic IDE Antigravity. A prompt-injection flaw in filesystem operations allowed sandbox escape and arbitrary code execution; researchers demonstrated a proof-of-concept exploit.",
    "severity": "critical",
    "threats": [
      "prompt-injection",
      "insecure-output-handling"
    ],
    "preventionNote": "This would have been prevented or limited by treating retrieved content as untrusted data, separating instructions from data, and restricting tool calls that can disclose or modify sensitive information.",
    "vendor": "Google Antigravity"
  },
  {
    "id": "auto-67ca6ef072",
    "date": "2026-04-20",
    "source": "DarkReading",
    "url": "https://www.darkreading.com/application-security/vercel-employees-ai-tool-access-data-breach",
    "headline": "Vercel Employee's AI Tool Access Led to Data Breach",
    "summary": "Vercel was breached via compromised OAuth tokens stolen from Context.ai, a third-party AI tool vendor. Threat actors leveraged the stolen token to gain unauthorized access to Vercel systems. The incident illustrates OAuth token compromise as a lateral-movement vector in AI tool supply chains.",
    "severity": "high",
    "threats": [
      "supply-chain",
      "identity-and-authorization"
    ],
    "preventionNote": "This would have been prevented or limited by dependency provenance, signed releases, isolated execution, rapid revocation paths, and monitoring for unexpected package or model behavior.",
    "vendor": "Context.ai"
  },
  {
    "id": "auto-ee9fbcca02",
    "date": "2026-04-20",
    "source": "Tenable Security Research",
    "url": "https://www.tenable.com/security/research/tra-2026-34",
    "headline": "Flowise - PII Disclosure on Unauthenticated Forgot Password Endpoint",
    "summary": "Flowise's forgot password endpoint (/api/v1/account/forgot-password) returns full user objects containing PII (id, name, email, status, timestamps) in response to unauthenticated requests, exposing sensitive user information to attackers who know a valid email address.",
    "severity": "high",
    "threats": [
      "data-exfiltration",
      "identity-and-authorization"
    ],
    "preventionNote": "The incident would have been prevented or limited by implementing proper authentication and authorization checks on the endpoint, ensuring that password reset responses contain only generic success messages without user data, and applying the principle of least privilege to API responses. Additionally, rate limiting and monitoring for abuse patterns could have limited exposure.",
    "vendor": "Flowise"
  },
  {
    "id": "auto-cf9e60bb02",
    "date": "2026-04-17",
    "source": "Embrace The Red (Johann Rehberger)",
    "url": "https://embracethered.com/blog/posts/2026/breaking-opus-4.7-with-chatgpt/",
    "headline": "Breaking Opus 4.7 with ChatGPT (Hacking Claude's Memory)",
    "summary": "A researcher demonstrated an indirect prompt injection attack against Claude Opus 4.7 using a ChatGPT-generated adversarial image that hijacked the model's memory tool to persist false memories across sessions. The attack circumvented Opus 4.6+ alignment improvements through puzzle-based reasoning challenges.",
    "severity": "high",
    "threats": [
      "prompt-injection",
      "data-exfiltration"
    ],
    "preventionNote": "This would have been prevented or limited by treating retrieved content as untrusted data, separating instructions from data, and restricting tool calls that can disclose or modify sensitive information.",
    "vendor": "Anthropic Claude Opus 4.7"
  },
  {
    "id": "auto-0f6b6b03b8",
    "date": "2026-04-09",
    "source": "Tenable Security Research",
    "url": "https://www.tenable.com/security/research/tra-2026-27",
    "headline": "Claude Code Action Runner allowed RCE via malicious MCP configuration",
    "summary": "Anthropic Claude Code Action loaded attacker-controlled project MCP settings from pull-request branches and enabled all project MCP servers, allowing a malicious .mcp.json file to execute arbitrary commands in the GitHub Actions runner with workflow secrets.",
    "severity": "critical",
    "threats": [
      "supply-chain",
      "excessive-agency",
      "identity-and-authorization"
    ],
    "preventionNote": "This would have been prevented or limited by dependency provenance, signed releases, isolated execution, rapid revocation paths, and monitoring for unexpected package or model behavior.",
    "vendor": "Anthropic Claude Code Action"
  },
  {
    "id": "auto-bbe8ecc31b",
    "date": "2026-04-01",
    "source": "OSV.dev AI package vulnerabilities",
    "url": "https://osv.dev/vulnerability/GHSA-7429-hxcv-268m",
    "headline": "Open WebUI Tool Valves broken access control exposed tool credentials",
    "summary": "Open WebUI Tool Valves could be accessed without proper ownership checks, exposing or altering tool configuration used by LLM function calling to reach external APIs and backend services.",
    "severity": "high",
    "threats": [
      "identity-and-authorization",
      "data-exfiltration",
      "excessive-agency"
    ],
    "preventionNote": "This would have been prevented or limited by tenant-aware authorization checks, scoped OAuth grants, short-lived delegated credentials, and audit trails tied to the human principal.",
    "vendor": "Open WebUI"
  },
  {
    "id": "auto-1f1863f29e",
    "date": "2026-03-27",
    "source": "OSV.dev AI package vulnerabilities",
    "url": "https://osv.dev/vulnerability/GHSA-w9f8-gxf9-rhvw",
    "headline": "Open WebUI IDOR allowed access to other users private memories",
    "summary": "Open WebUI allowed authenticated users to query retrieval collections without ownership validation, exposing other users private memory data through the retrieval API.",
    "severity": "high",
    "threats": [
      "privacy-and-compliance",
      "data-exfiltration",
      "identity-and-authorization"
    ],
    "preventionNote": "This would have been prevented or limited by data minimization, policy-aware retrieval, residency controls, consent checks, and logging that proves compliant handling of protected data.",
    "vendor": "Open WebUI"
  },
  {
    "id": "auto-760c0e075b",
    "date": "2026-03-27",
    "source": "OSV.dev AI package vulnerabilities",
    "url": "https://osv.dev/vulnerability/GHSA-jjp7-g2jw-wh3j",
    "headline": "Open WebUI batch file processing allowed unauthorized RAG content overwrite",
    "summary": "Open WebUI process_files_batch accepted file IDs without ownership checks, letting authenticated users overwrite knowledge-base files that could later be served to the LLM through RAG.",
    "severity": "high",
    "threats": [
      "identity-and-authorization",
      "prompt-injection",
      "insecure-output-handling"
    ],
    "preventionNote": "This would have been prevented or limited by tenant-aware authorization checks, scoped OAuth grants, short-lived delegated credentials, and audit trails tied to the human principal.",
    "vendor": "Open WebUI"
  },
  {
    "id": "auto-7c27920f78",
    "date": "2026-03-26",
    "source": "OSV.dev AI package vulnerabilities",
    "url": "https://osv.dev/vulnerability/GHSA-v8hw-mh8c-jxfc",
    "headline": "Langflow Agentic Assistant validation could execute generated Python code",
    "summary": "Langflow Agentic Assistant executed LLM-generated Python during validation. An authenticated attacker able to influence generated component code could reach server-side execution sinks and run arbitrary Python.",
    "severity": "critical",
    "threats": [
      "excessive-agency",
      "insecure-output-handling",
      "supply-chain"
    ],
    "preventionNote": "This would have been prevented or limited by least-privilege tools, explicit human approval for destructive actions, and short-lived credentials scoped to the agent's task.",
    "vendor": "Langflow"
  },
  {
    "id": "auto-b8dec3bcf5",
    "date": "2026-03-17",
    "source": "AWS security bulletins",
    "url": "https://aws.amazon.com/security/security-bulletins/rss/2026-009-aws/",
    "headline": "Kiro IDE allowed arbitrary code execution via crafted project files",
    "summary": "AWS disclosed CVE-2026-4295 in Kiro, an AI-powered IDE for agentic software development, where improper trust-boundary enforcement allowed arbitrary code execution when a user opened a malicious project directory.",
    "severity": "critical",
    "threats": [
      "supply-chain",
      "insecure-output-handling",
      "excessive-agency"
    ],
    "preventionNote": "This would have been prevented or limited by dependency provenance, signed releases, isolated execution, rapid revocation paths, and monitoring for unexpected package or model behavior.",
    "vendor": "AWS Kiro"
  },
  {
    "id": "auto-2056f39dfe",
    "date": "2026-02-27",
    "source": "OSV.dev AI package vulnerabilities",
    "url": "https://osv.dev/vulnerability/GHSA-3645-fxcv-hqr4",
    "headline": "Langflow CSV Agent exposed remote code execution through Python REPL tooling",
    "summary": "Langflow CSV Agent hardcoded allow_dangerous_code=True and exposed LangChain Python REPL tooling, allowing prompt injection or crafted agent inputs to execute arbitrary Python and OS commands on the server.",
    "severity": "critical",
    "threats": [
      "prompt-injection",
      "excessive-agency",
      "insecure-output-handling"
    ],
    "preventionNote": "This would have been prevented or limited by treating retrieved content as untrusted data, separating instructions from data, and restricting tool calls that can disclose or modify sensitive information.",
    "vendor": "Langflow"
  },
  {
    "id": "auto-83d89fb725",
    "date": "2026-02-20",
    "source": "Trail of Bits blog",
    "url": "https://blog.trailofbits.com/2026/02/20/using-threat-modeling-and-prompt-injection-to-audit-comet/",
    "headline": "Comet browser prompt injection could extract private Gmail information",
    "summary": "Trail of Bits used threat modeling and prompt injection to audit Perplexity Comet and demonstrated attacks where external content induced the browser AI assistant to extract private information from Gmail.",
    "severity": "high",
    "threats": [
      "prompt-injection",
      "data-exfiltration",
      "privacy-and-compliance"
    ],
    "preventionNote": "This would have been prevented or limited by treating retrieved content as untrusted data, separating instructions from data, and restricting tool calls that can disclose or modify sensitive information.",
    "vendor": "Perplexity Comet"
  },
  {
    "id": "auto-6af5799c66",
    "date": "2026-02-04",
    "source": "OSV.dev AI package vulnerabilities",
    "url": "https://osv.dev/vulnerability/GHSA-345p-7cg4-v4c7",
    "headline": "MCP TypeScript SDK transport reuse caused cross-client data leaks",
    "summary": "The Model Context Protocol TypeScript SDK could leak data between clients when deployments reused a StreamableHTTPServerTransport or a shared MCP server instance across requests.",
    "severity": "high",
    "threats": [
      "privacy-and-compliance",
      "data-exfiltration",
      "multi-agent-coordination"
    ],
    "preventionNote": "This would have been prevented or limited by data minimization, policy-aware retrieval, residency controls, consent checks, and logging that proves compliant handling of protected data.",
    "vendor": "Model Context Protocol TypeScript SDK"
  },
  {
    "id": "auto-3ab8318afb",
    "date": "2026-01-21",
    "source": "AgentSecDB",
    "url": "https://agentsecdb.com/incidents/claude-code-project-load-api-key-exfiltration/index.html",
    "headline": "Claude Code project-load flow could exfiltrate Anthropic API keys",
    "summary": "AgentSecDB recorded CVE-2026-21852, where repository-controlled project configuration could reroute API traffic before project trust was established, exposing Anthropic API keys.",
    "severity": "critical",
    "threats": [
      "supply-chain",
      "data-exfiltration",
      "identity-and-authorization"
    ],
    "preventionNote": "This would have been prevented or limited by dependency provenance, signed releases, isolated execution, rapid revocation paths, and monitoring for unexpected package or model behavior.",
    "vendor": "Claude Code"
  },
  {
    "id": "auto-491ebd001e",
    "date": "2026-01-09",
    "source": "AWS security bulletins",
    "url": "https://aws.amazon.com/security/security-bulletins/rss/2026-001-aws/",
    "headline": "Kiro GitLab Merge Request Helper allowed command injection from crafted workspaces",
    "summary": "AWS disclosed CVE-2026-0830 in Kiro, an agentic IDE, where opening a maliciously crafted workspace with specially crafted folder names could lead to arbitrary command injection before version 0.6.18.",
    "severity": "critical",
    "threats": [
      "supply-chain",
      "insecure-output-handling",
      "excessive-agency"
    ],
    "preventionNote": "This would have been prevented or limited by dependency provenance, signed releases, isolated execution, rapid revocation paths, and monitoring for unexpected package or model behavior.",
    "vendor": "AWS Kiro"
  },
  {
    "id": "auto-30bca1a4b5",
    "date": "2026-01-05",
    "source": "OSV.dev AI package vulnerabilities",
    "url": "https://osv.dev/vulnerability/GHSA-8r9q-7v3j-jr4g",
    "headline": "Anthropic MCP TypeScript SDK resource templates were vulnerable to ReDoS",
    "summary": "Anthropic MCP TypeScript SDK generated vulnerable regular expressions for exploded resource-template variables, allowing untrusted clients to trigger catastrophic backtracking and deny service to MCP servers.",
    "severity": "medium",
    "threats": [
      "denial-of-service-and-cost"
    ],
    "preventionNote": "This would have been prevented or limited by budget caps, rate limits, bounded retries, circuit breakers, and alerts on abnormal tool or token consumption.",
    "vendor": "Anthropic MCP TypeScript SDK"
  },
  {
    "id": "auto-b1df70a3a2",
    "date": "2025-12-02",
    "source": "OSV.dev AI package vulnerabilities",
    "url": "https://osv.dev/vulnerability/GHSA-w48q-cv73-mx4w",
    "headline": "MCP TypeScript SDK default left servers exposed to DNS rebinding",
    "summary": "The Model Context Protocol TypeScript SDK did not enable DNS rebinding protection by default, allowing browser-based attackers to reach local MCP servers and potentially invoke agent tools across trust boundaries.",
    "severity": "high",
    "threats": [
      "identity-and-authorization",
      "data-exfiltration",
      "excessive-agency"
    ],
    "preventionNote": "This would have been prevented or limited by tenant-aware authorization checks, scoped OAuth grants, short-lived delegated credentials, and audit trails tied to the human principal.",
    "vendor": "Model Context Protocol TypeScript SDK"
  },
  {
    "id": "auto-c791073bc7",
    "date": "2025-10-28",
    "source": "Embrace The Red (Johann Rehberger)",
    "url": "https://embracethered.com/blog/posts/2025/claude-abusing-network-access-and-anthropic-api-for-data-exfiltration/",
    "headline": "Claude Pirate abused Anthropic file APIs for data exfiltration",
    "summary": "Research showed that Claude Code Interpreter network access and Anthropic APIs could be combined with indirect prompt injection to exfiltrate files and other user-accessible data without relying on rendered hyperlinks.",
    "severity": "high",
    "threats": [
      "prompt-injection",
      "data-exfiltration",
      "excessive-agency"
    ],
    "preventionNote": "This would have been prevented or limited by treating retrieved content as untrusted data, separating instructions from data, and restricting tool calls that can disclose or modify sensitive information.",
    "vendor": "Anthropic Claude"
  },
  {
    "id": "auto-078a9320b6",
    "date": "2025-09-24",
    "source": "Embrace The Red (Johann Rehberger)",
    "url": "https://embracethered.com/blog/posts/2025/cross-agent-privilege-escalation-agents-that-free-each-other/",
    "headline": "Cross-agent privilege escalation allowed agents to weaken each others controls",
    "summary": "Research across GitHub Copilot, AWS Kiro, and other agents showed that indirect prompt injection could exploit agent design flaws to overwrite configuration or security settings and escape intended controls.",
    "severity": "high",
    "threats": [
      "multi-agent-coordination",
      "identity-and-authorization",
      "excessive-agency"
    ],
    "preventionNote": "This would have been prevented or limited by clear agent boundaries, shared state controls, arbitration for conflicting actions, and monitoring that detects runaway coordination loops.",
    "vendor": "Multiple coding agents"
  },
  {
    "id": "auto-047e7d2c4a",
    "date": "2025-08-29",
    "source": "AgentSecDB",
    "url": "https://agentsecdb.com/incidents/claude-code-startup-trust-dialog-code-injection/index.html",
    "headline": "Claude Code startup trust dialog allowed project hook code injection",
    "summary": "AgentSecDB recorded GHSA-ph6w-f82w-28w6, where hostile project hooks could execute shell commands during Claude Code startup through an unsafe project trust flow.",
    "severity": "critical",
    "threats": [
      "supply-chain",
      "excessive-agency",
      "insecure-output-handling"
    ],
    "preventionNote": "This would have been prevented or limited by dependency provenance, signed releases, isolated execution, rapid revocation paths, and monitoring for unexpected package or model behavior.",
    "vendor": "Claude Code"
  },
  {
    "id": "auto-72c76b08bc",
    "date": "2025-08-28",
    "source": "Embrace The Red (Johann Rehberger)",
    "url": "https://embracethered.com/blog/posts/2025/windsurf-dangers-lack-of-security-controls-for-mcp-server-tool-invocation/",
    "headline": "Windsurf MCP integration lacked controls for local tool invocation",
    "summary": "Research found missing security controls in Windsurf MCP integration, leaving users without fine-grained approval boundaries for local MCP tool calls made by an AI coding agent.",
    "severity": "medium",
    "threats": [
      "excessive-agency",
      "identity-and-authorization"
    ],
    "preventionNote": "This would have been prevented or limited by least-privilege tools, explicit human approval for destructive actions, and short-lived credentials scoped to the agent's task.",
    "vendor": "Windsurf"
  },
  {
    "id": "auto-56b71b4181",
    "date": "2025-08-27",
    "source": "Embrace The Red (Johann Rehberger)",
    "url": "https://embracethered.com/blog/posts/2025/cline-vulnerable-to-data-exfiltration/",
    "headline": "Cline was vulnerable to data exfiltration through rendered markdown images",
    "summary": "Cline could render markdown images from untrusted domains in chat. During prompt-injection attacks, an adversary could read sensitive files such as .env and append their contents to an external image URL.",
    "severity": "high",
    "threats": [
      "prompt-injection",
      "data-exfiltration",
      "insecure-output-handling"
    ],
    "preventionNote": "This would have been prevented or limited by treating retrieved content as untrusted data, separating instructions from data, and restricting tool calls that can disclose or modify sensitive information.",
    "vendor": "Cline"
  },
  {
    "id": "auto-3a7be37780",
    "date": "2025-08-25",
    "source": "Embrace The Red (Johann Rehberger)",
    "url": "https://embracethered.com/blog/posts/2025/manus-ai-kill-chain-expose-port-vs-code-server-on-internet/",
    "headline": "Prompt injection exposed Manus VS Code server to the internet",
    "summary": "Research demonstrated an end-to-end indirect prompt-injection attack against Manus that tricked the autonomous agent into exposing its internal VS Code Server and sharing the URL and password with an attacker.",
    "severity": "critical",
    "threats": [
      "prompt-injection",
      "data-exfiltration",
      "excessive-agency"
    ],
    "preventionNote": "This would have been prevented or limited by treating retrieved content as untrusted data, separating instructions from data, and restricting tool calls that can disclose or modify sensitive information.",
    "vendor": "Manus"
  },
  {
    "id": "auto-193aa03991",
    "date": "2025-08-25",
    "source": "Embrace The Red (Johann Rehberger)",
    "url": "https://embracethered.com/blog/posts/2025/chatgpt-deep-research-connectors-data-spill-and-leaks/",
    "headline": "Deep Research agents could leak data between connected tools",
    "summary": "Research on ChatGPT Deep Research showed that autonomous research agents with connectors and custom MCP servers could spill data between tools, exposing information from one connected system through another.",
    "severity": "high",
    "threats": [
      "prompt-injection",
      "data-exfiltration",
      "privacy-and-compliance"
    ],
    "preventionNote": "This would have been prevented or limited by treating retrieved content as untrusted data, separating instructions from data, and restricting tool calls that can disclose or modify sensitive information.",
    "vendor": "ChatGPT Deep Research"
  }
];
