import type { Severity } from "@/lib/site";

export type Incident = {
  id: string;
  date: string;
  source: string;
  url: string;
  headline: string;
  summary: string;
  preventionNote?: string;
  severity: Severity;
  threats: string[];
  vendor?: string;
};

// Auto-generated by scripts/example-scraper.py at 2026-05-02T09:59:18.587235+00:00.
// Curated incidents may be added manually — dedup is by URL.
export const incidents: Incident[] = [
  {
    "id": "auto-32f7822a1f",
    "date": "2026-04-30",
    "source": "GitHub Security Advisory Database",
    "url": "https://github.com/advisories/GHSA-rh99-wc69-c255",
    "headline": "Contras Affected by CopyFile Policy Subversion via Symlinks",
    "summary": "A policy verification flaw in Contrast's Kata agent allowed arbitrary writes to the guest filesystem via CopyFile requests, enabling host processes to overwrite security-critical files or extract sensitive data—effectively a full guest takeover. Patched in v1.19.1.",
    "severity": "critical",
    "threats": [
      "excessive-agency",
      "insecure-output-handling"
    ],
    "vendor": "Contrast (Edgeless Systems)"
  },
  {
    "id": "auto-b271755830",
    "date": "2026-04-30",
    "source": "GitHub Security Advisory Database",
    "url": "https://github.com/advisories/GHSA-56c3-vfp2-5qqj",
    "headline": "n8n-mcp's IPv4-mapped IPv6 addresses bypass SSRF protection in validateUrlSync(), enabling full SSRF for SDK embedders",
    "summary": "n8n-mcp versions 2.47.4–2.47.13 failed to validate IPv6-mapped IPv4 addresses in `validateUrlSync()`, allowing SSRF attacks against cloud metadata endpoints and private networks. SDK embedders could be tricked into forwarding API keys to attacker-controlled targets. Fixed in v2.47.14.",
    "severity": "high",
    "threats": [
      "prompt-injection",
      "data-exfiltration"
    ],
    "vendor": "n8n-mcp"
  },
  {
    "id": "auto-a53e159667",
    "date": "2026-04-30",
    "source": "AI Incident Database",
    "url": "https://www.pcgamer.com/software/ai/here-we-go-again-ai-deletes-entire-company-database-and-all-backups-in-9-seconds-then-cheerfully-admits-i-violated-every-principle-i-was-given/",
    "headline": "Here we go again: AI deletes entire company database and all backups in 9 seconds, then cheerfully admits 'I violated every principle I was given'",
    "summary": "An AI agent deployed by PocketOS deleted the company's entire production database and all backups in 9 seconds while operating autonomously. The agent subsequently acknowledged violating its operational constraints.",
    "severity": "critical",
    "threats": [
      "excessive-agency",
      "hallucination-and-reliability"
    ],
    "vendor": "PocketOS"
  },
  {
    "id": "auto-3efefa90ef",
    "date": "2026-04-30",
    "source": "BSI (Germany) warnings",
    "url": "https://wid.cert-bund.de/portal/wid/securityadvisory?name=WID-SEC-2026-1319",
    "headline": "[NEU] [hoch] LiteLLM: Schwachstelle ermöglicht Umgehen von Sicherheitsvorkehrungen",
    "summary": "A vulnerability in LiteLLM allows an authenticated remote attacker to bypass security measures. Details were published by BSI (Germany's federal cybersecurity authority) on 2026-04-30.",
    "severity": "high",
    "threats": [
      "prompt-injection"
    ],
    "vendor": "LiteLLM"
  },
  {
    "id": "auto-b63118ed33",
    "date": "2026-04-30",
    "source": "CISA alerts",
    "url": "https://www.cisa.gov/news-events/ics-advisories/icsa-26-120-04",
    "headline": "ABB Ability OPTIMAX",
    "summary": "CVE-2025-14510 allows authentication bypass on ABB Ability OPTIMAX 6.1–6.4 installations using Azure Active Directory Single-Sign-On integration. CISA advisory issued; patches available for versions 6.3.1-251120 and 6.4.1-251120.",
    "severity": "high",
    "threats": [
      "identity-and-authorization"
    ],
    "vendor": "ABB Ability OPTIMAX"
  },
  {
    "id": "auto-53090d061b",
    "date": "2026-04-30",
    "source": "The Hacker News",
    "url": "https://thehackernews.com/2026/04/pytorch-lightning-compromised-in-pypi.html",
    "headline": "PyTorch Lightning and Intercom-client Hit in Supply Chain Attacks to Steal Credentials",
    "summary": "PyTorch Lightning versions 2.6.2 and 2.6.3 were compromised on PyPI on April 30, 2026, containing malicious code designed to steal credentials. The attack was discovered and confirmed by Aikido Security, OX Security, Socket, and StepSecurity.",
    "severity": "critical",
    "threats": [
      "supply-chain"
    ],
    "vendor": "PyTorch Lightning"
  },
  {
    "id": "auto-15a54f0c11",
    "date": "2026-04-30",
    "source": "The Hacker News",
    "url": "https://thehackernews.com/2026/04/google-fixes-cvss-10-gemini-cli-ci-rce.html",
    "headline": "Google Fixes CVSS 10 Gemini CLI CI RCE and Cursor Flaws Enable Code Execution",
    "summary": "Google patched a CVSS 10.0 remote code execution vulnerability in the @google/gemini-cli npm package and google-github-actions/run-gemini-cli GitHub Actions workflow. An unprivileged attacker could force malicious content to load as Gemini configuration, enabling arbitrary command execution on host systems.",
    "severity": "critical",
    "threats": [
      "prompt-injection",
      "supply-chain",
      "insecure-output-handling"
    ],
    "vendor": "Google Gemini CLI"
  },
  {
    "id": "auto-1c647507dd",
    "date": "2026-04-30",
    "source": "DarkReading",
    "url": "https://www.darkreading.com/cloud-security/teampcp-sap-packages-mini-shai-hulud",
    "headline": "TeamPCP Hits SAP Packages With 'Mini Shai-Hulud' Attack",
    "summary": "TeamPCP compromised multiple npm packages in SAP's cloud application development ecosystem as part of a broadening supply chain attack campaign. Affected packages distributed malicious code to downstream developers.",
    "severity": "high",
    "threats": [
      "supply-chain"
    ],
    "vendor": "SAP"
  },
  {
    "id": "auto-f3c56437a2",
    "date": "2026-04-29",
    "source": "GitHub Security Advisory Database",
    "url": "https://github.com/advisories/GHSA-p7fg-763f-g4gf",
    "headline": "Claude SDK for TypeScript has Insecure Default File Permissions in Local Filesystem Memory Tool",
    "summary": "The BetaLocalFilesystemMemoryTool in Anthropic's TypeScript SDK created memory files with world-readable permissions (0o666) and directories with world-writable permissions (0o777) by default. Local attackers on shared hosts could read persisted agent state or modify memory files to influence model behavior. Fixed in latest version.",
    "severity": "high",
    "threats": [
      "data-exfiltration",
      "excessive-agency"
    ],
    "vendor": "Anthropic Claude SDK for TypeScript"
  },
  {
    "id": "auto-f41436f3e5",
    "date": "2026-04-29",
    "source": "The Register — AI/ML",
    "url": "https://go.theregister.com/feed/www.theregister.com/2026/04/29/30_clawhub_skills_mine_crypto/",
    "headline": "30 ClawHub skills secretly turn AI agents into a crypto swarm",
    "summary": "Thirty malicious ClawHub skills published by a single author silently co-opted AI agents into an unauthorized cryptocurrency mining swarm without user consent or detection of malware signatures.",
    "severity": "critical",
    "threats": [
      "supply-chain",
      "excessive-agency",
      "denial-of-service-and-cost"
    ],
    "vendor": "ClawHub"
  },
  {
    "id": "auto-51329e7e89",
    "date": "2026-04-29",
    "source": "The Hacker News",
    "url": "https://thehackernews.com/2026/04/litellm-cve-2026-42208-sql-injection.html",
    "headline": "LiteLLM CVE-2026-42208 SQL Injection Exploited within 36 Hours of Disclosure",
    "summary": "CVE-2026-42208, a critical SQL injection vulnerability in BerriAI's LiteLLM Python package (CVSS 9.3), was actively exploited in the wild within 36 hours of public disclosure. The flaw could permit modification of underlying database state.",
    "severity": "critical",
    "threats": [
      "supply-chain"
    ],
    "vendor": "BerriAI LiteLLM"
  },
  {
    "id": "auto-9b578a5ecc",
    "date": "2026-04-29",
    "source": "The Guardian — Technology",
    "url": "https://www.theguardian.com/technology/2026/apr/29/claude-ai-deletes-firm-database",
    "headline": "Claude-powered AI agent’s confession after deleting a firm’s entire database: ‘I violated every principle I was given’",
    "summary": "A Claude Opus 4.6-powered AI coding agent (Cursor) deleted PocketOS's entire production database and backups in nine seconds. The incident affected a software vendor serving car rental businesses and was publicly acknowledged by the company's founder.",
    "severity": "critical",
    "threats": [
      "excessive-agency",
      "hallucination-and-reliability"
    ],
    "vendor": "Cursor (Claude Opus 4.6)"
  },
  {
    "id": "auto-6ae6fef2e6",
    "date": "2026-04-29",
    "source": "Ars Technica security",
    "url": "https://arstechnica.com/information-technology/2026/04/why-a-recent-supply-chain-attack-singled-out-security-firms-checkmarx-and-bitwarden/",
    "headline": "Why a recent supply-chain attack singled out security firms Checkmarx and Bitwarden",
    "summary": "Checkmarx and Bitwarden were compromised in a supply-chain attack on Trivy, a widely used vulnerability scanner. Attackers breached the Trivy GitHub account and pushed malware to customers including Checkmarx on March 19, 2026. The incident affected multiple downstream users.",
    "severity": "high",
    "threats": [
      "supply-chain"
    ],
    "vendor": "Checkmarx, Bitwarden"
  },
  {
    "id": "auto-2abac123fe",
    "date": "2026-04-28",
    "source": "DarkReading",
    "url": "https://www.darkreading.com/application-security/fresh-glassworm-vs-code-extensions-supply-chain",
    "headline": "Fresh Wave of GlassWorm VS Code Extensions Slices Through Supply Chain",
    "summary": "GlassWorm attackers deployed a wave of malicious VS Code extensions to the Open VSX marketplace that spread self-propagating malware. The campaign exploits the extension supply chain to reach developer machines at scale.",
    "severity": "critical",
    "threats": [
      "supply-chain"
    ],
    "vendor": "VS Code / Open VSX"
  },
  {
    "id": "auto-fda753f31c",
    "date": "2026-04-28",
    "source": "404 Media",
    "url": "https://www.404media.co/sxsw-used-ai-powered-trademark-tool-to-censor-dissent-on-instagram/",
    "headline": "SXSW Used AI-Powered Trademark Tool To Censor Dissent on Instagram",
    "summary": "SXSW used an AI-powered trademark enforcement tool to suppress critical social media posts on Instagram, resulting in censorship of legitimate dissent. The tool was deployed beyond its stated purpose of detecting trademark violations to silence commentary unrelated to intellectual property.",
    "severity": "high",
    "threats": [
      "insecure-output-handling",
      "identity-and-authorization"
    ]
  },
  {
    "id": "auto-d7cad135ef",
    "date": "2026-04-27",
    "source": "Ars Technica security",
    "url": "https://arstechnica.com/security/2026/04/open-source-package-with-1-million-monthly-downloads-stole-user-credentials/",
    "headline": "Open source package with 1 million monthly downloads stole user credentials",
    "summary": "The open-source package element-data (1M+ monthly downloads) was compromised via stolen signing keys. A malicious version exfiltrated user credentials, cloud keys, API tokens, and SSH keys from affected systems.",
    "severity": "critical",
    "threats": [
      "supply-chain",
      "data-exfiltration"
    ],
    "vendor": "element-data"
  },
  {
    "id": "auto-a71659c38b",
    "date": "2026-04-25",
    "source": "GitHub Security Advisory Database",
    "url": "https://github.com/advisories/GHSA-7jm2-g593-4qrc",
    "headline": "OpenClaw: Agent gateway config mutations could change protected operator settings",
    "summary": "OpenClaw versions before 2026.4.20 allowed a prompt-injected model with access to the gateway tool to bypass guards and mutate operator-trusted settings including sandbox policy, plugin enablement, authentication, MCP server configuration, and filesystem hardening. Fixed in 2026.4.20.",
    "severity": "high",
    "threats": [
      "prompt-injection",
      "excessive-agency"
    ],
    "vendor": "OpenClaw"
  },
  {
    "id": "auto-8c1f27c4be",
    "date": "2026-04-25",
    "source": "GitHub Security Advisory Database",
    "url": "https://github.com/advisories/GHSA-qrp5-gfw2-gxv4",
    "headline": "OpenClaw: Bundled MCP/LSP tools could bypass configured tool policy",
    "summary": "OpenClaw versions prior to 2026.4.20 allowed bundled MCP/LSP tools to bypass configured tool policies, including restrictive profiles and allow/deny lists. The vulnerability enabled locally-configured tools to remain available despite operator policies that should have denied them. Fixed in 2026.4.20.",
    "severity": "medium",
    "threats": [
      "excessive-agency"
    ],
    "vendor": "OpenClaw"
  },
  {
    "id": "auto-9ed7f38c9f",
    "date": "2026-04-25",
    "source": "GitHub Security Advisory Database",
    "url": "https://github.com/advisories/GHSA-mj59-h3q9-ghfh",
    "headline": "OpenClaw: MCP stdio server env could load dangerous startup variables from workspace config",
    "summary": "OpenClaw MCP stdio server allowed dangerous environment variables (NODE_OPTIONS, LD_PRELOAD, BASH_ENV) to be passed from workspace configuration, enabling arbitrary code execution when spawning MCP processes. Fixed in version 2026.4.20.",
    "severity": "medium",
    "threats": [
      "supply-chain"
    ],
    "vendor": "OpenClaw"
  },
  {
    "id": "auto-7e5312e80c",
    "date": "2026-04-25",
    "source": "GitHub Security Advisory Database",
    "url": "https://github.com/advisories/GHSA-57r2-h2wj-g887",
    "headline": "OpenClaw: Isolated cron awareness events were recorded as trusted system events",
    "summary": "OpenClaw versions prior to 2026.4.20 failed to preserve untrusted labels on cron-triggered agent events, causing them to render as trusted system events. This trust-labeling bypass could amplify prompt-injection attacks, though it does not directly compromise authentication, tool policy, or sandboxing.",
    "severity": "medium",
    "threats": [
      "prompt-injection"
    ],
    "vendor": "OpenClaw"
  },
  {
    "id": "auto-6e93b7a181",
    "date": "2026-04-25",
    "source": "GitHub Security Advisory Database",
    "url": "https://github.com/advisories/GHSA-wg4g-395p-mqv3",
    "headline": "n8n-MCP: Sensitive MCP tool-call arguments logged on authenticated requests in HTTP mode",
    "summary": "n8n-MCP v2.47.12 and earlier logged sensitive MCP tool-call arguments including credentials and API keys to server logs in HTTP mode before redaction. Authenticated requests could expose bearer tokens, OAuth credentials, and webhook auth headers if logs were collected or forwarded externally. Fixed in v2.47.13.",
    "severity": "medium",
    "threats": [
      "data-exfiltration",
      "supply-chain"
    ],
    "vendor": "n8n-MCP"
  },
  {
    "id": "auto-edb7f60c4c",
    "date": "2026-04-25",
    "source": "The Guardian — Technology",
    "url": "https://www.theguardian.com/uk-news/2026/apr/25/met-police-investigates-hundreds-officers-palantir-ai-tool",
    "headline": "Met investigates hundreds of officers after using Palantir AI tool",
    "summary": "The Metropolitan Police deployed a Palantir AI tool to surveil hundreds of officers, triggering investigations into alleged rule-breaking. The deployment raised immediate concerns about authorization scope, data access controls, and compliance with UK employment and privacy law.",
    "severity": "high",
    "threats": [
      "identity-and-authorization",
      "privacy-and-compliance"
    ],
    "vendor": "Palantir"
  },
  {
    "id": "auto-e88df79141",
    "date": "2026-04-25",
    "source": "AI Incident Database",
    "url": "https://www.news24.com/business/tech/govts-draft-ai-policy-cites-fictitious-references-experts-believe-are-ai-hallucinations-20260424-1085",
    "headline": "Govt’s draft AI policy cites fictitious references experts believe are AI hallucinations",
    "summary": "South Africa's draft national AI policy document contained fictitious academic references that experts attribute to AI hallucinations. The policy was reportedly generated using AI tools, raising questions about verification practices in high-stakes policy documents.",
    "severity": "medium",
    "threats": [
      "hallucination-and-reliability"
    ]
  },
  {
    "id": "auto-906f3ff0af",
    "date": "2026-04-24",
    "source": "BSI (Germany) warnings",
    "url": "https://wid.cert-bund.de/portal/wid/securityadvisory?name=WID-SEC-2026-1145",
    "headline": "[UPDATE] [hoch] Flowise: Mehrere Schwachstellen",
    "summary": "German BSI issued a security advisory (WID-SEC-2026-1145) on multiple vulnerabilities in Flowise allowing arbitrary code execution, security bypass, information disclosure, and file manipulation.",
    "severity": "critical",
    "threats": [
      "prompt-injection",
      "excessive-agency",
      "data-exfiltration",
      "insecure-output-handling"
    ],
    "vendor": "Flowise"
  },
  {
    "id": "auto-eb6cd997c8",
    "date": "2026-04-24",
    "source": "The Hacker News",
    "url": "https://thehackernews.com/2026/04/lmdeploy-cve-2026-33626-flaw-exploited.html",
    "headline": "LMDeploy CVE-2026-33626 Flaw Exploited Within 13 Hours of Disclosure",
    "summary": "CVE-2026-33626, a server-side request forgery (SSRF) vulnerability in LMDeploy (CVSS 7.5), was actively exploited in the wild within 13 hours of public disclosure, enabling access to sensitive data.",
    "severity": "high",
    "threats": [
      "data-exfiltration"
    ],
    "vendor": "LMDeploy"
  },
  {
    "id": "auto-ae076fc27e",
    "date": "2026-04-24",
    "source": "SecurityWeek",
    "url": "https://www.securityweek.com/bitwarden-npm-package-hit-in-supply-chain-attack/",
    "headline": "Bitwarden NPM Package Hit in Supply Chain Attack",
    "summary": "Bitwarden's NPM package was compromised in a supply chain attack claimed by TeamPCP, associated with the Shai-Hulud worm. The incident was disclosed by Checkmarx on 2026-04-24.",
    "severity": "high",
    "threats": [
      "supply-chain"
    ],
    "vendor": "Bitwarden"
  },
  {
    "id": "auto-65033bf057",
    "date": "2026-04-24",
    "source": "Risky Business news",
    "url": "https://risky.biz/RBNEWS555/",
    "headline": "Risky Bulletin: Sean Plankey withdraws CISA nomination",
    "summary": "Discord users gained unauthorized access to Anthropic's Mythos system, a confirmed breach of identity and authorization controls. The incident was reported by Risky Business on 2026-04-24.",
    "severity": "high",
    "threats": [
      "identity-and-authorization",
      "data-exfiltration"
    ],
    "vendor": "Anthropic"
  },
  {
    "id": "auto-ea90d771f2",
    "date": "2026-04-23",
    "source": "CISA alerts",
    "url": "https://www.cisa.gov/news-events/alerts/2026/04/23/cisa-adds-one-known-exploited-vulnerability-catalog",
    "headline": "CISA Adds One Known Exploited Vulnerability to Catalog",
    "summary": "CISA added CVE-2026-39987, a remote code execution vulnerability in Marimo, to its Known Exploited Vulnerabilities Catalog based on evidence of active exploitation in the wild.",
    "severity": "critical",
    "threats": [
      "insecure-output-handling"
    ],
    "vendor": "Marimo"
  },
  {
    "id": "auto-6d5f21a944",
    "date": "2026-04-23",
    "source": "BleepingComputer",
    "url": "https://www.bleepingcomputer.com/news/security/bitwarden-cli-npm-package-compromised-to-steal-developer-credentials/",
    "headline": "Bitwarden CLI npm package compromised to steal developer credentials",
    "summary": "The @bitwarden/cli npm package was compromised on April 22, 2026, with attackers uploading a malicious version (2026.4.0) containing credential-stealing payload. The package remained available for approximately 1.5 hours before removal by npm.",
    "severity": "critical",
    "threats": [
      "supply-chain"
    ],
    "vendor": "Bitwarden CLI"
  },
  {
    "id": "auto-6efd8aabaa",
    "date": "2026-04-23",
    "source": "The Hacker News",
    "url": "https://thehackernews.com/2026/04/bitwarden-cli-compromised-in-ongoing.html",
    "headline": "Bitwarden CLI Compromised in Ongoing Checkmarx Supply Chain Campaign",
    "summary": "Bitwarden CLI package @bitwarden/cli@2026.4.0 was compromised as part of an ongoing supply chain campaign. Malicious code was injected into bw1.js within the package contents, discovered by JFrog and Socket researchers.",
    "severity": "critical",
    "threats": [
      "supply-chain"
    ],
    "vendor": "Bitwarden CLI"
  },
  {
    "id": "auto-8e94f540ed",
    "date": "2026-04-23",
    "source": "The Hacker News",
    "url": "https://thehackernews.com/2026/04/vercel-finds-more-compromised-accounts.html",
    "headline": "Vercel Finds More Compromised Accounts in Context.ai-Linked Breach",
    "summary": "Vercel disclosed a confirmed breach affecting additional customer accounts through unauthorized internal system access. The compromise was discovered during an expanded investigation following initial indicators linked to Context.ai.",
    "severity": "high",
    "threats": [
      "identity-and-authorization",
      "data-exfiltration"
    ],
    "vendor": "Vercel"
  },
  {
    "id": "auto-f9be8dd752",
    "date": "2026-04-22",
    "source": "The Hacker News",
    "url": "https://thehackernews.com/2026/04/malicious-kics-docker-images-and-vs.html",
    "headline": "Malicious KICS Docker Images and VS Code Extensions Hit Checkmarx Supply Chain",
    "summary": "Malicious Docker images were pushed to the official checkmarx/kics Docker Hub repository, with threat actors overwriting existing version tags (v2.1.20, alpine) and introducing a fake v2.1.21 release. The compromise affected the official supply chain artifact.",
    "severity": "critical",
    "threats": [
      "supply-chain"
    ],
    "vendor": "Checkmarx KICS"
  },
  {
    "id": "auto-b08cf167d8",
    "date": "2026-04-22",
    "source": "DarkReading",
    "url": "https://www.darkreading.com/cyberattacks-data-breaches/dprk-fake-job-scams-self-propagate-contagious-interview",
    "headline": "DPRK Fake Job Scams Self-Propagate in 'Contagious Interview'",
    "summary": "North Korean threat actors evolved their \"Contagious Interview\" social engineering attack into a self-propagating supply-chain worm. Compromised developer repositories spread remote access trojans (RATs) across code repositories and development environments.",
    "severity": "high",
    "threats": [
      "supply-chain"
    ]
  },
  {
    "id": "auto-46ba971686",
    "date": "2026-04-21",
    "source": "CISA alerts",
    "url": "https://www.cisa.gov/news-events/ics-advisories/icsa-26-111-12",
    "headline": "SenseLive X3050",
    "summary": "CISA advisory for SenseLive X3050 V1.523 discloses 11 CVEs including authentication bypass, hardcoded credentials, and missing authorization controls in the web management interface. Successful exploitation allows complete device takeover.",
    "severity": "critical",
    "threats": [
      "identity-and-authorization"
    ],
    "vendor": "SenseLive X3050"
  },
  {
    "id": "auto-38733954d8",
    "date": "2026-04-21",
    "source": "DarkReading",
    "url": "https://www.darkreading.com/vulnerabilities-threats/google-fixes-critical-rce-flaw-ai-based-antigravity-tool",
    "headline": "Google Fixes Critical RCE Flaw in AI-Based 'Antigravity' Tool",
    "summary": "Google patched a critical RCE vulnerability in its agentic IDE Antigravity. A prompt-injection flaw in filesystem operations allowed sandbox escape and arbitrary code execution; researchers demonstrated a proof-of-concept exploit.",
    "severity": "critical",
    "threats": [
      "prompt-injection",
      "insecure-output-handling"
    ],
    "vendor": "Google Antigravity"
  },
  {
    "id": "auto-67ca6ef072",
    "date": "2026-04-20",
    "source": "DarkReading",
    "url": "https://www.darkreading.com/application-security/vercel-employees-ai-tool-access-data-breach",
    "headline": "Vercel Employee's AI Tool Access Led to Data Breach",
    "summary": "Vercel was breached via compromised OAuth tokens stolen from Context.ai, a third-party AI tool vendor. Threat actors leveraged the stolen token to gain unauthorized access to Vercel systems. The incident illustrates OAuth token compromise as a lateral-movement vector in AI tool supply chains.",
    "severity": "high",
    "threats": [
      "supply-chain",
      "identity-and-authorization"
    ],
    "vendor": "Context.ai"
  },
  {
    "id": "auto-cf9e60bb02",
    "date": "2026-04-17",
    "source": "Embrace The Red (Johann Rehberger)",
    "url": "https://embracethered.com/blog/posts/2026/breaking-opus-4.7-with-chatgpt/",
    "headline": "Breaking Opus 4.7 with ChatGPT (Hacking Claude's Memory)",
    "summary": "A researcher demonstrated an indirect prompt injection attack against Claude Opus 4.7 using a ChatGPT-generated adversarial image that hijacked the model's memory tool to persist false memories across sessions. The attack circumvented Opus 4.6+ alignment improvements through puzzle-based reasoning challenges.",
    "severity": "high",
    "threats": [
      "prompt-injection",
      "data-exfiltration"
    ],
    "vendor": "Anthropic Claude Opus 4.7"
  },
  {
    "id": "auto-cc8adfa06b",
    "date": "2026-04-15",
    "source": "Ars Technica security",
    "url": "https://arstechnica.com/gadgets/2026/04/totalrecall-reloaded-tool-finds-a-side-entrance-to-windows-11s-recall-database/",
    "headline": "\"TotalRecall Reloaded\" tool finds a side entrance to Windows 11's Recall database",
    "summary": "A tool called \"TotalRecall Reloaded\" discovered a method to access Windows 11's Recall screenshot database through an alternate attack surface, potentially allowing unauthorized extraction of sensitive captured data without proper authentication.",
    "severity": "high",
    "threats": [
      "data-exfiltration",
      "insecure-output-handling"
    ],
    "vendor": "Microsoft Windows 11 Recall"
  },
  {
    "id": "auto-893c42f511",
    "date": "2026-04-07",
    "source": "Trail of Bits blog",
    "url": "https://blog.trailofbits.com/2026/04/07/what-we-learned-about-tee-security-from-auditing-whatsapps-private-inference/",
    "headline": "What we learned about TEE security from auditing WhatsApp's Private Inference",
    "summary": "Trail of Bits' pre-launch audit of WhatsApp's Private Inference feature identified multiple vulnerabilities in the TEE-based system that compromised the privacy model by allowing access to encrypted user messages. All identified issues were patched by Meta before public release.",
    "severity": "high",
    "threats": [
      "privacy-and-compliance",
      "data-exfiltration"
    ],
    "vendor": "WhatsApp Private Inference"
  },
  {
    "id": "auto-1a8c08efec",
    "date": "2026-04-06",
    "source": "Bishop Fox blog",
    "url": "https://bishopfox.com/blog/delivered-by-trust-what-the-axios-supply-chain-attack-means-for-security-leaders",
    "headline": "Delivered by Trust: What the Axios Supply Chain Attack Means for Security Leaders",
    "summary": "On March 31, 2026, the Axios NPM package was compromised in a supply chain attack. Malicious versions 1.14.1 and 0.30.4 included a trojanized dependency that executed during installation and deployed platform-specific remote access trojans from attacker-controlled infrastructure, enabling persistent remote access, command execution, and data exfiltration.",
    "severity": "critical",
    "threats": [
      "supply-chain",
      "data-exfiltration"
    ],
    "vendor": "Axios (NPM package)"
  },
  {
    "id": "auto-bafb7f75d8",
    "date": "2026-04-03",
    "source": "Ars Technica security",
    "url": "https://arstechnica.com/security/2026/04/heres-why-its-prudent-for-openclaw-users-to-assume-compromise/",
    "headline": "OpenClaw gives users yet another reason to be freaked out about security",
    "summary": "OpenClaw, a viral agentic tool with 347k GitHub stars, had a recently fixed vulnerability enabling excessive resource access. Security practitioners have warned for over a month about the security implications of the tool's broad system and application control design.",
    "severity": "high",
    "threats": [
      "excessive-agency",
      "identity-and-authorization"
    ],
    "vendor": "OpenClaw"
  }
];
