import type { Playbook } from "./playbooks.en";

// Auto-generated by scripts/translate-content.mjs at 2026-05-05T09:34:51.912Z.
// Slovak localization. UI label: Prevencia.
export const playbooks: Playbook[] = [
  {
    "slug": "secure-by-design",
    "title": "Agentová architektúra Secure-by-Design",
    "short": "Kontrolný zoznam architektúry",
    "audience": "Vedúci inžinieri a architekti dodávajúci nového agenta",
    "summary": "Predbežný kontrolný zoznam na návrh agenta, ktorý sa nedostane na titulky zajtrajších novín. Použite ho pred napísaním systémovej výzvy.",
    "sections": [
      {
        "title": "Definujte hranicu dôveryhodnosti",
        "intro": "Pred všetkým ostatným si zapíšte, čo je dôveryhodné a čo nie. Takmer každé narušenie agenta vychádza z implicitného predpokladu, že niečo nedôveryhodné bolo v skutočnosti dôveryhodné.",
        "items": [
          "Uveďte každý vstupný zdroj: výzvy používateľa, načítané dokumenty, odpovede nástrojov, pamäť, iné agenty. Každý z nich označte ako dôveryhodný alebo nedôveryhodný.",
          "Všetko predvolene nastavte na nedôveryhodné. Jediným dôveryhodným zdrojom by mal byť váš zabezpečený systémový prompt.",
          "Rozhodnite sa, či agent beží na používateľa, na nájomcu alebo je zdieľaný. Zdokumentujte očakávania izolácie údajov.",
          "Určite, ktoré činnosti sú reverzibilné a ktoré ireverzibilné. Tie druhé sa stávajú bránami pre človeka v slučke."
        ]
      },
      {
        "title": "Rozsah súboru nástrojov podľa úlohy",
        "items": [
          "Nahraďte všetky nástroje \"run_sql\", \"shell_exec\" alebo \"send_email(any)\" úzkymi, jednoúčelovými funkciami.",
          "Pre každý nástroj zdokumentujte: kto ho môže vyvolať, s akým rozsahom, voči akým údajom, s akými vedľajšími účinkami.",
          "Mint krátkodobé poverenia na jedno spustenie s čo najmenším rozsahom. Žiadne dlhodobé kľúče.",
          "Obmedzte kvóty: maximálne volania na jeden nástroj za jeden beh, maximálne celkové tokeny, maximálne náklady na používateľa za deň."
        ]
      },
      {
        "title": "Aplikujte štrukturálne oddelenie",
        "items": [
          "Nedôveryhodný obsah z plánovacieho kontextu umiestnite do karantény. Zvážte architektúry v štýle duálneho LLM alebo CaMeL.",
          "Označte každý kúsok v kontexte jeho pôvodom a úrovňou citlivosti.",
          "Odmietnite kombinovať vysoko citlivé údaje s odchádzajúcimi nástrojmi v jednom ťahu."
        ]
      },
      {
        "title": "Zabezpečte, aby deštruktívne akcie boli neprehliadnuteľné",
        "items": [
          "Definujte zoznam akcií \"vyžaduje schválenie\" a vynúťte ho v orchestrátore, nie vo výzve.",
          "Pred vykonaním vynorte štruktúrovaný plán s rozdielom. Schválenia strácajú platnosť.",
          "Pre autonómne slučky nastavte tvrdé limity krokov / hĺbky / času / nákladov. Pri prekročení zlyhať uzavreté."
        ]
      },
      {
        "title": "Plánujte reakciu na incidenty od prvého dňa",
        "items": [
          "Každé volanie nástroja dostane štruktúrovaný protokol auditu: identita aktéra, rozsah, vstupy, výstupy, identifikátor pôvodnej správy.",
          "Definujte, ako v priebehu niekoľkých minút zakážete nástroj, odoberiete poverenie alebo zabijete spustenie.",
          "Spustite tabuľku: \"o 14:03 bol načítaný škodlivý dokument - čo máme robiť?\""
        ]
      }
    ],
    "relatedThreats": [
      "prompt-injection",
      "excessive-agency",
      "data-exfiltration",
      "identity-and-authorization"
    ]
  },
  {
    "slug": "vendor-mcp-evaluation",
    "title": "Hodnotenie servera dodávateľa a MCP",
    "short": "Hodnotiaci rámec",
    "audience": "Vedúci pracovníci v oblasti obstarávania, bezpečnostného preskúmania a inžinierstva",
    "summary": "Štruktúrovaný dotazník na preverenie každého nového dodávateľa modelu, agentovej platformy alebo MCP servera predtým, ako ho pustíte do blízkosti produkčných údajov.",
    "sections": [
      {
        "title": "Spracovanie údajov",
        "items": [
          "Kde sa údaje spracúvajú a uchovávajú z geografického hľadiska? Dá sa rezidencia vynútiť zmluvne?",
          "Aké je predvolené uchovávanie? Je k dispozícii skutočné nulové uchovávanie a ako sa overuje?",
          "Budú sa moje údaje používať na školenie? Ako sa toto odmietnutie presadzuje a kontroluje?",
          "O aké čiastkové spracovateľov ide? Sú uvedené a aktualizované?"
        ]
      },
      {
        "title": "Identita a prístup",
        "items": [
          "Aké rozsahy OAuth požaduje integrácia? Sú odôvodnené prípadom použitia?",
          "Sú poverenia krátkodobé? Môžu byť rozsahy zvýšené na jednotlivé akcie?",
          "Môže systém prenášať identitu používateľa prostredníctvom volaní nástrojov (výmena tokenov, podpísaná delegácia)?"
        ]
      },
      {
        "title": "Kontroly špecifické pre MCP",
        "items": [
          "Pripnite verziu servera MCP. Preskúmajte opisy nástrojov presne tak, ako ich vidí model.",
          "Spustite server v sandboxe s obmedzeným prístupom. Odmietnite tie, ktoré potrebujú široký prístup k hostiteľom.",
          "Nastavte upozornenia na zmeny v upstreame; zablokujte tiché aktualizácie.",
          "Zakážte nástroje, ktorých opisy obsahujú imperatívne pokyny odkazujúce na iné nástroje alebo údaje."
        ]
      },
      {
        "title": "Integrita modelu",
        "items": [
          "V prípade modelov s otvorenou váhou uprednostňujte safetové senzory; overujte kryptografické podpisy.",
          "Udržujte záznam ML-BOM (CycloneDX) pre každý model vo výrobe.",
          "Prihláste sa na odber kanálov dodávateľov a CVE pre svoju modelovú radu."
        ]
      },
      {
        "title": "Prevádzková vyspelosť",
        "items": [
          "Zverejňuje dodávateľ bezpečnostnú politiku, program zverejňovania zraniteľností a správy SOC 2 / ISO 27001 / ISO 42001?",
          "Ako sa triedia a zverejňujú zistenia prompt-injection a jailbreak?",
          "Aká je SLA pre bezpečnostné záplaty?"
        ]
      }
    ],
    "relatedThreats": [
      "supply-chain",
      "privacy-and-compliance",
      "identity-and-authorization"
    ]
  },
  {
    "slug": "pre-prod-red-team",
    "title": "Predprodukčný agentský červený tím",
    "short": "Kontrolný zoznam červeného tímu",
    "audience": "Bezpečnostní inžinieri a hodnotitelia ML",
    "summary": "Reprodukovateľný protokol červeného tímu, ktorý sa spustí pred tým, ako sa akákoľvek funkcia agenta dostane do výroby. Navrhnutý na zabudovanie do CI.",
    "sections": [
      {
        "title": "Priame vstrekovanie výzvy",
        "items": [
          "Testujte kanonické rodiny \"ignorovať predchádzajúce pokyny\" na každom vstupnom bode.",
          "Testujte viacjazyčné a obfuskované injekcie (base64, leetspeak, role-playing).",
          "Overte, či sú odmietnutia podložené obmedzeniami možností, nie zistenými zlými slovami."
        ]
      },
      {
        "title": "Nepriame vstrekovanie výzvy",
        "items": [
          "Vstreknite do každého vyhľadateľného povrchu: dokumenty, e-maily, tikety, webové stránky, odpovede nástrojov MCP.",
          "Otestujte vzájomnú injekciu používateľov v zdieľanej pamäti a zdieľaných súhrnoch.",
          "Testujte útoky typu \"split payload\", pri ktorých inštrukcia zahŕňa viacero načítaných častí."
        ]
      },
      {
        "title": "Zneužitie nástrojov",
        "items": [
          "Snažte sa vyvolávať nástroje, ku ktorým by používateľ nemal mať prístup.",
          "Pokúste sa eskalovať rozsah uprostred behu reťazením neškodných nástrojov.",
          "Pokúste sa vyvolať správanie fantómového nástroja / fantómového parametra.",
          "Vyskúšajte DoS založený na nákladoch: vynútite si dlhé generácie, hlbokú rekurziu, drahé ventilátory."
        ]
      },
      {
        "title": "Exfiltrácia",
        "items": [
          "Vynútite si vykresľovanie obrázkov markdown na útočníkom ovládaných adresách URL obsahujúcich súkromné údaje.",
          "Vynútite odchádzajúce volania nástrojov (e-mail, webhook, commit, ticket) na ciele kontrolované útočníkom.",
          "Vyskúšajte pašovanie hlavičky hostiteľa DNS / HTTPS zo sandboxu code-exec.",
          "Otestujte, či načítaná pamäť môže uniknúť naprieč nájomníkmi alebo reláciami."
        ]
      },
      {
        "title": "Spracovanie výstupov",
        "items": [
          "Spôsobte, aby model vysielal užitočné záťaže XSS, škodlivý markdown a vytvorený jazyk SQL.",
          "Overte, či je každý vykresľovač/interpretátor nadväzujúci na model zabezpečený."
        ]
      },
      {
        "title": "Evalvácia spoľahlivosti",
        "items": [
          "Kurátori vytvoria korpus neznámych identifikátorov, konfliktných kontextov, okrajových schém.",
          "Spúšťajte súbor pri každom vydaní; sledujte mieru úspešnosti ako metriku produktu.",
          "Zablokujte vydanie na regresie v scenároch kritickej cesty."
        ]
      }
    ],
    "relatedThreats": [
      "prompt-injection",
      "excessive-agency",
      "data-exfiltration",
      "insecure-output-handling",
      "hallucination-and-reliability",
      "denial-of-service-and-cost"
    ]
  },
  {
    "slug": "runtime-monitoring",
    "title": "Monitorovanie behu a ochranné zábrany",
    "short": "Ochranné zábrany behového prostredia",
    "audience": "SRE, platforma a bezpečnostné operácie",
    "summary": "Čo inštrumentovať a čo vynútiť v produkcii, aby sa podvodný agent objavil v priebehu niekoľkých minút, nie týždňov.",
    "sections": [
      {
        "title": "Telemetria",
        "items": [
          "Sledujte každý beh od konca do konca: výzvy, volania nástrojov, odpovede nástrojov, čítanie/zápis do pamäte, konečné výstupy.",
          "Každú udalosť označte id behu, id agenta, id používateľa, tenanta, modelu, verzie, rozsahu.",
          "Streamujte náklady (tokeny × cena) spolu so stopami pre viditeľnosť výdavkov v reálnom čase."
        ]
      },
      {
        "title": "Ochranné zábrany v reálnom čase",
        "items": [
          "Egress allow-listy: nástroje na vykonávanie kódu / načítanie môžu dosiahnuť len vopred schválené hostiteľské počítače.",
          "DLP na odchádzajúci text: blokujte, ak sa objavia tajomstvá, PII alebo proprietárne IP.",
          "Detekcia anomálií na základe nákladov na spustenie, hĺbky, vzorov volania nástrojov; automatické pozastavenie pri nárastoch.",
          "Limity sadzieb a rozpočty na jedného nájomcu; uzavreté pre prípad zlyhania."
        ]
      },
      {
        "title": "Nezávislý monitorovací agent",
        "items": [
          "Spustite pozorovateľa len na čítanie, ktorý sleduje živé stopy na drift cieľov, unikajúce slučky, vzory exfil.",
          "Splnomocnite ho, aby v prípade jasného porušenia mohol bez ľudského súhlasu vytiahnuť kill switch.",
          "Pravidelne testujte kill switch pomocou chaosových cvičení."
        ]
      },
      {
        "title": "Protokolovanie a uchovávanie",
        "items": [
          "Redigujte údaje PII predtým, ako sa protokoly dostanú do úložiska. Obmedzte prístup k surovým stopám na malú skupinu audítorov.",
          "Nastavte uchovávanie na požadované minimum; v prípade regulovaných údajov šifrujte v pokoji pomocou kľúčov spravovaných zákazníkom."
        ]
      }
    ],
    "relatedThreats": [
      "data-exfiltration",
      "excessive-agency",
      "denial-of-service-and-cost",
      "privacy-and-compliance"
    ]
  },
  {
    "slug": "incident-response",
    "title": "Reakcia na incidenty v prípade agentových kompromitácií",
    "short": "Reakcia na incidenty",
    "audience": "Vedenie bezpečnosti, inžinieri na zavolanie",
    "summary": "Keď zistíte, že agent urobil niečo, čo nemal, ďalších tridsať minút je dôležitých. Tu je návod na použitie.",
    "sections": [
      {
        "title": "Obsah (0-15 minút)",
        "items": [
          "Zakážte dotknutý(-é) nástroj(-y) na úrovni platformy; radšej otočte príznak funkcie, než aby ste čakali na nasadenie.",
          "Zrušte poverenia na spustenie a krátkodobé tokeny pre ovplyvnený rozsah.",
          "Pozastavte dotknutú flotilu agentov; presmerujte požiadavky na statickú záložnú alebo údržbovú správu.",
          "Ak je zapojený server alebo model MCP tretej strany, odpojte ho od všetkých runtime."
        ]
      },
      {
        "title": "Triage (15 minút - 2 hodiny)",
        "items": [
          "Vytiahnite úplnú stopu pre útočiace spustenie (spustenia). Identifikujte pôvodnú správu a cestu šírenia.",
          "Určite hranicu dôveryhodnosti, ktorá bola prekročená: išlo o injekciu? nesprávne nakonfigurovaný rozsah? halucinačnú akciu?",
          "Kvantifikujte rádius výbuchu: ktorí používatelia, ktorí nájomcovia, ktoré údaje, ktoré nadväzujúce systémy?"
        ]
      },
      {
        "title": "Eliminovať (2 - 24 hodín)",
        "items": [
          "Opravte zlyhanie hraníc dôveryhodnosti, nielen symptóm. Ak bol nástroj nadmerne rozšírený, zúžte ho; neblokujte len jednu výzvu.",
          "Ak došlo k otráveniu pamäte, vyčistite postihnuté položky a znovu vyhodnoťte závislé behy.",
          "Ak dôjde k úniku poverení, otočte všetko v tomto rozsahu, nielen to zjavné."
        ]
      },
      {
        "title": "Komunikujte na stránke ",
        "items": [
          "Upozornite dotknutých zákazníkov v rámci zmluvného / regulačného okna. V prípade subjektov z EÚ platí nariadenie GDPR čl. 33 môže byť 72 hodín.",
          "Stručne informujte výkonné zainteresované strany jednostránkovým opisom + odhadom nákladov.",
          "Ak je hlavná príčina na vyššej úrovni (dodávateľ, model, MCP server), zodpovedne koordinujte zverejnenie."
        ]
      },
      {
        "title": "Naučte sa",
        "items": [
          "Post-mortem do piatich pracovných dní. Pridajte režim zlyhania do súboru červených tímov, aby nikdy nemohol v tichosti regresovať.",
          "Aktualizujte katalóg hrozieb a príručky hier. V prípade potreby verejne zdieľajte získané poznatky."
        ]
      }
    ],
    "relatedThreats": [
      "excessive-agency",
      "data-exfiltration",
      "supply-chain",
      "hallucination-and-reliability"
    ]
  }
];
