import type { ResourceGroup } from "./resources.en";

// Auto-generated by scripts/translate-content.mjs at 2026-05-03T10:48:05.006Z.
// Slovak localization. UI label: Prevencia.
export const resourceGroups: ResourceGroup[] = [
  {
    "title": "Rámce a normy",
    "intro": "Ak si v tomto štvrťroku prečítate len štyri dokumenty, prečítajte si tieto. Tvoria chrbticu každého seriózneho programu agentúrnej bezpečnosti.",
    "items": [
      {
        "name": "OWASP Top 10 pre aplikácie LLM (2025)",
        "org": "OWASP",
        "url": "https://genai.owasp.org/llm-top-10/",
        "note": "Kanonická taxonómia rizík LLM/agentov. Každoročne aktualizovaná pomocou komunitného procesu."
      },
      {
        "name": "NIST AI Risk Management Framework + GenAI Profile (Rámec riadenia rizík umelej inteligencie NIST + profil GenAI)",
        "org": "NIST",
        "url": "https://www.nist.gov/itl/ai-risk-management-framework",
        "note": "Riadiť / mapovať / merať / spravovať. Profil GenAI (NIST AI 600-1) mapuje rámec na riziká špecifické pre GenAI."
      },
      {
        "name": "MITRE ATLAS",
        "org": "MITRE",
        "url": "https://atlas.mitre.org/",
        "note": "Protivníkove TTP v štýle ATT&CK pre systémy AI/ML. Užitočné pre red-team rozsah a detekčné inžinierstvo."
      },
      {
        "name": "ISO/IEC 42001 - Systém riadenia AI",
        "org": "ISO/IEC",
        "url": "https://www.iso.org/standard/81230.html",
        "note": "Norma systému riadenia pre AI; \"ISO 27001 pre AI\". Čoraz častejšie citovaný v podnikovom obstarávaní."
      },
      {
        "name": "Zákon EÚ o umelej inteligencii",
        "org": "European Union",
        "url": "https://artificialintelligenceact.eu/",
        "note": "Rizikovo odstupňovaná regulácia s postupným uplatňovaním od roku 2025-2027. Kľúčové pre všetky produkty, ktoré sa dotýkajú používateľov v EÚ."
      }
    ]
  },
  {
    "title": "Výskum a písanie, ktorému dôverujeme",
    "intro": "Krátky, mienkotvorný zoznam čítania. Každý z nich zmenil spôsob, akým pristupujeme k bezpečnosti agentov.",
    "items": [
      {
        "name": "Archív prompt-injection Simona Willisona",
        "org": "Simon Willison",
        "url": "https://simonwillison.net/tags/prompt-injection/",
        "note": "Najdlhšie trvajúce a najdostupnejšie spravodajstvo o promptných injekciách v produkčných systémoch."
      },
      {
        "name": "Embrace The Red - Johann Rehberger",
        "org": "Johann Rehberger",
        "url": "https://embracethered.com/blog/",
        "note": "Neustály prúd vysokokvalitných exfiltrácií / agent-injection POC. Povinné čítanie pre červené tímy."
      },
      {
        "name": "Google DeepMind - dokument CaMeL",
        "org": "Google DeepMind",
        "url": "https://arxiv.org/abs/2503.18813",
        "note": "Architektúra dual-LLM založená na schopnostiach na obranu pred promptným vstrekovaním v agentoch používajúcich nástroje."
      },
      {
        "name": "Správy o agentúrnej bezpečnosti Anthropic & OpenAI",
        "org": "Anthropic / OpenAI",
        "url": "https://www.anthropic.com/research",
        "note": "Pokyny zverejnené dodávateľom o bezpečnosti používania nástrojov, odolnosti voči úniku z väzenia a vzoroch identity agenta."
      },
      {
        "name": "Blog spoločnosti Invariant Labs",
        "org": "Invariant Labs",
        "url": "https://invariantlabs.ai/blog",
        "note": "Praktické, výskumné analýzy zraniteľností MCP a agentov."
      }
    ]
  },
  {
    "title": "Zdroje, ktoré sledujeme na účely informovania o incidentoch",
    "intro": "Náš denný škrabák ich prehľadáva a vyhľadáva nové incidenty. Každý z nich sa nezávisle od seba oplatí predplatiť.",
    "items": [
      {
        "name": "Národná databáza zraniteľností NIST",
        "org": "NIST",
        "url": "https://nvd.nist.gov/",
        "note": "Autoritatívny zdroj CVE. Sledujeme značky relevantné pre platformy AI/ML a agentov."
      },
      {
        "name": "Oznámenia projektu OWASP GenAI Security",
        "org": "OWASP",
        "url": "https://genai.owasp.org/",
        "note": "Zverejnenia pracovných skupín a referenčné odporúčania."
      },
      {
        "name": "Bezpečnostné odporúčania dodávateľov (OpenAI, Anthropic, Google, Microsoft)",
        "org": "Vendors",
        "url": "https://msrc.microsoft.com/",
        "note": "Prihláste sa na odber RSS správ o zabezpečení od dodávateľov, ktoré sa týkajú opráv prvej strany ovplyvňujúcich váš zásobník."
      },
      {
        "name": "Databáza incidentov umelej inteligencie",
        "org": "Responsible AI Collaborative",
        "url": "https://incidentdatabase.ai/",
        "note": "Katalóg incidentov zostavený komunitou, ktorý pokrýva širšie škody spôsobené umelou inteligenciou nad rámec čistej bezpečnosti."
      }
    ]
  }
];
