import type { Surface } from "./surfaces.en";

// Auto-generated by scripts/translate-content.mjs at 2026-05-04T08:19:15.269Z.
// Slovak localization. UI label: Prevencia.
export const surfaces: Surface[] = [
  {
    "id": "llm",
    "title": "Model",
    "short": "Model",
    "role": "Interpretuje kontext, rozhoduje, ktoré nástroje zavolať, generuje výstup.",
    "threats": [
      "prompt-injection",
      "hallucination-and-reliability",
      "supply-chain",
      "privacy-and-compliance"
    ],
    "mitigations": [
      "Používajte model so silným dodržiavaním pokynov a zverejneným bezpečnostným postojom.",
      "Obmedzte výstup prostredníctvom schém JSON a volania funkcií.",
      "Overte integritu modelu (podpisy, safetové senzory) pre samohostiteľné váhy.",
      "S modelom zaobchádzajte ako s výkonným, ale nedôveryhodným dodávateľom - nikdy nie ako s vlastným inžinierom."
    ]
  },
  {
    "id": "system-prompt",
    "title": "Systémové výzvy a zásady",
    "short": "Politika",
    "role": "Zakódujte pravidlá, osoby a zakázané činnosti agenta.",
    "threats": [
      "prompt-injection",
      "excessive-agency"
    ],
    "mitigations": [
      "Zásady udržiavajte krátke, deklaratívne a riadené podľa verzií.",
      "Nespoliehajte sa na to, že samotné zásady zabránia nebezpečným volaniam nástrojov - presadzujte ich v kóde.",
      "Pri každom vydaní zásady auditne otestujte na základe súboru červených tímov."
    ]
  },
  {
    "id": "memory",
    "title": "Pamäť a dlhodobý stav",
    "short": "Pamäť",
    "role": "Zachováva fakty, preferencie a predchádzajúce výstupy naprieč spusteniami.",
    "threats": [
      "prompt-injection",
      "data-exfiltration",
      "privacy-and-compliance"
    ],
    "mitigations": [
      "Rozdeľte pamäť podľa používateľov a nájomcov; nikdy ju nezdieľajte cez hranice dôveryhodnosti.",
      "Uchovávajte len štruktúrované, priradené fakty - nie výpisy voľného textu.",
      "Plánujte vymazanie: sledujte líniu, aby sa šírili žiadosti o právo byť zabudnutý.",
      "Pri každom čítaní považujte načítanú pamäť za nedôveryhodný vstup."
    ]
  },
  {
    "id": "retrieval",
    "title": "Vyhľadávanie a RAG",
    "short": "Vyhľadávanie",
    "role": "Vytiahne dokumenty, webové stránky a vektory do kontextového okna.",
    "threats": [
      "prompt-injection",
      "data-exfiltration",
      "privacy-and-compliance"
    ],
    "mitigations": [
      "Označte každý kúsok provenienciou a citlivosťou; zobrazte provenienciu v používateľskom rozhraní.",
      "Aplikujte kontroly prístupu na úrovni používateľa v načítavacom zariadení, nie vo výzve.",
      "Sanitizujte HTML, odstraňujte skrytý text a odmietajte zjavne nepriateľské časti."
    ]
  },
  {
    "id": "tools",
    "title": "Nástroje a servery MCP",
    "short": "Nástroje",
    "role": "Externé možnosti - API, databázy, interpretátory kódu, vyhľadávanie.",
    "threats": [
      "excessive-agency",
      "supply-chain",
      "data-exfiltration",
      "denial-of-service-and-cost",
      "insecure-output-handling"
    ],
    "mitigations": [
      "Jednoúčelové, úzke nástroje. Žiadne záchytné nástroje.",
      "Per-run, krátkodobé poverenia. Zoznamy povolených vstupov.",
      "Sandbox servery MCP tretích strán; pripnite a skontrolujte každú aktualizáciu.",
      "Kvóty a rozpočty vynútené u orchestrátora."
    ]
  },
  {
    "id": "orchestrator",
    "title": "Orchestrátor / plánovač",
    "short": "Orchestrátor",
    "role": "Koordinuje kroky, volá nástroje, spravuje stav v celom behu.",
    "threats": [
      "excessive-agency",
      "multi-agent-coordination",
      "hallucination-and-reliability",
      "denial-of-service-and-cost"
    ],
    "mitigations": [
      "Tvrdé obmedzenia: hĺbka, kroky, čas, náklady. Presadzujte v kóde.",
      "Vzor naplánuj-vykonaj s rozdielmi pre ľudské schválenie pri nezvratných akciách.",
      "Schematicky overujte každé volanie nástroja; odmietnite fantómové nástroje/parametre."
    ]
  },
  {
    "id": "identity",
    "title": "Identita, Authn & Authz",
    "short": "Identita",
    "role": "Určuje, za koho agent vystupuje a čo môže robiť.",
    "threats": [
      "identity-and-authorization",
      "excessive-agency",
      "privacy-and-compliance"
    ],
    "mitigations": [
      "Odlišná identita pracovnej záťaže pre agenta (v štýle SPIFFE); nikdy nedediť používateľské tokeny pre prevádzku služieb.",
      "Súhlas s jednotlivými akciami just-in-time pre citlivé oblasti.",
      "Prenášajte používateľský kontext end-to-end prostredníctvom podpísaného delegovania (RFC 8693)."
    ]
  },
  {
    "id": "output",
    "title": "Obsluha výstupov / Renderer",
    "short": "Výstup",
    "role": "Renderuje, vykonáva alebo prenáša všetko, čo model vytvorí.",
    "threats": [
      "insecure-output-handling",
      "data-exfiltration"
    ],
    "mitigations": [
      "S výstupom modelu zaobchádzajte ako s používateľským vstupom. Vynechajte, overte, parametrizujte.",
      "Zakázať automatické načítanie vzdialených obrázkov, iframeov, skriptov v používateľských rozhraniach chatu.",
      "Sandboxujte akékoľvek spúšťanie kódu; predvolene zamedzte výstup do siete."
    ]
  }
];
