import type { Threat } from "./threats.en";

// Auto-generated by scripts/translate-content.mjs at 2026-05-05T07:58:40.331Z.
// Slovak localization. UI label: Prevencia.
export const threats: Threat[] = [
  {
    "slug": "prompt-injection",
    "title": "Vstreknutie podnetu (priame a nepriame)",
    "short": "Injekcia výzvy",
    "severity": "critical",
    "summary": "Útočníci prepašujú do kontextu modelu inštrukcie - prostredníctvom vstupu používateľa, načítaných dokumentov, webových stránok, e-mailov alebo odpovedí nástrojov - a agent ich poslušne nasleduje.",
    "whatItIs": [
      "Injektovanie príkazov je agentovým ekvivalentom injekcie SQL: nedôveryhodný text sa vkladá do privilegovaného kontextu a model nemá spoľahlivý spôsob, ako rozlíšiť príkazy od údajov. Je to jediná najrozšírenejšia trieda zraniteľností v systémoch poháňaných LLM a neustále sa nachádza na prvom mieste v rebríčku OWASP Top 10 pre aplikácie LLM.",
      "K priamej injekcii výzvy dochádza vtedy, keď škodlivý používateľ zadá pokyny do chatu. K nepriamemu prompt injection - oveľa nebezpečnejšiemu v agentových systémoch - dochádza, keď sú tieto inštrukcie skryté v obsahu, ktorý agent neskôr prehltne: webová stránka, ktorú prezerá, PDF, ktoré sumarizuje, e-mail, ktorý triedi, lístok Jira, ktorý spracováva, alebo dokonca odpoveď nástroja MCP.",
      "Keďže agent koná na základe interpretácie zmiešaných inštrukcií a údajov modelu, úspešná injekcia môže spôsobiť únik údajov, zavolať nástroje, ktoré by nemal, odoslať správy v mene používateľa alebo sa otáčať do iných systémov, ku ktorým má prístup."
    ],
    "howItHappens": [
      {
        "title": "Skryté pokyny v načítanom obsahu",
        "body": "Agent, ktorý prezerá web, číta e-maily alebo sa pýta na vektorové úložisko, preberá obsah, ktorého autormi sú útočníci. Pokyny môžu byť neviditeľné (biela na bielej, znaky s nulovou šírkou, text ALT, komentáre HTML) alebo jednoducho dôveryhodné, pretože sa vrátili z \"bezpečného\" nástroja."
      },
      {
        "title": "Reakcie nástrojov ako vektor útoku",
        "body": "Servery MCP, vyhľadávacie API, systémy ticketingu a CRM vracajú polia s voľným textom, ktoré agent považuje za základnú pravdu. Otrávený názov tiketu alebo opis produktu sa stáva inštrukciou."
      },
      {
        "title": "Viacstupňové pranie",
        "body": "Útočníci rozdeľujú škodlivé užitočné zaťaženie do viacerých dokumentov, pretože vedia, že agent ich zostaví. Alebo dajú agentovi pokyn, aby ignoroval bezpečnostné pokyny až po dlhej, neškodnej preambule."
      },
      {
        "title": "Injekcia naprieč používateľmi",
        "body": "V systémoch s viacerými používateľmi vstup jedného používateľa pretrváva v zdieľanej pamäti alebo súhrnoch a potom ovplyvňuje správanie agenta pre ďalšieho používateľa."
      }
    ],
    "realWorld": [
      {
        "name": "Bing Chat / Sydney instruction leak",
        "year": "2023",
        "note": "Stanfordský študent Kevin Liu použil jednoduchú injekciu na získanie dôvernej systémovej výzvy spoločnosti Microsoft a kódového označenia \"Sydney\"."
      },
      {
        "name": "Microsoft 365 Copilot 'EchoLeak'",
        "year": "2025",
        "note": "Spoločnosť Aim Labs odhalila CVE-2025-32711, nepriamu injekciu výzvy s nulovým kliknutím v aplikácii M365 Copilot, ktorá umožňuje exfiltráciu podnikových údajov prostredníctvom vytvoreného e-mailu."
      },
      {
        "name": "ChatGPT Search prompt injection",
        "year": "2024",
        "note": "Denník The Guardian a ďalší demonštrovali, že skrytý text na webových stránkach môže manipulovať so súhrnmi prehľadávania webu ChatGPT s cieľom odporúčať produkty alebo skrývať negatívne recenzie."
      }
    ],
    "mitigations": [
      {
        "title": "Všetky vstupy modelu považujte za nedôveryhodné",
        "body": "Prijmite postoj \"žiadna hranica dôveryhodnosti vo vnútri kontextového okna\". Všetko, čo má pôvod mimo výzvy vášho zabezpečeného systému - vrátane výstupov nástrojov a načítaných dokumentov - musí byť považované za nepriateľský vstup."
      },
      {
        "title": "Obmedzte, čo môže model robiť, nie čo vidí",
        "body": "Vstupné filtrovanie a \"detektory úniku z väzenia\" majú dlhý chvost zlyhaní. Trvalé zmiernenia vyplývajú z obmedzenia možností: zúžte rozsah nástrojov, vyžadujte potvrdenie pre deštruktívne akcie a spúšťajte nebezpečné nástroje v samostatnom, menej privilegovanom agentovi."
      },
      {
        "title": "Používajte štrukturálne oddelenie (vzory CaMeL / dual-LLM)",
        "body": "Architektúry ako CaMeL spoločnosti Google DeepMind a dual-LLM Simona Willisona rozdeľujú nedôveryhodný obsah do karanténneho kontextu, ktorý nemôže spúšťať volania nástrojov. Privilegovaný model vidí len nepriehľadné odkazy a štruktúrované výstupy."
      },
      {
        "title": "Vykresľovanie s ohľadom na provenienciu",
        "body": "Označte každý kúsok kontextu jeho zdrojom a vykreslite tento pôvod v používateľskom rozhraní, aby kontrolóri mohli pred schválením akcie odhaliť podozrivé pokyny."
      },
      {
        "title": "Egress allow-listing",
        "body": "Ak model môže zapisovať alebo volať, obmedzte, kam môže zapisovať a aké adresy URL môže načítať. Tým sa zastaví \"odosielanie údajov na stránku attacker.com\" aj v prípade, že sa injektáž podarí."
      }
    ],
    "frameworks": [
      {
        "name": "OWASP LLM01:2025 — Prompt Injection",
        "ref": "OWASP LLM Top 10"
      },
      {
        "name": "AML.T0051 — LLM Prompt Injection",
        "ref": "MITRE ATLAS"
      },
      {
        "name": "NIST AI 600-1 §2.1 — CBRN, §2.7 — Information Integrity",
        "ref": "NIST AI RMF GenAI Profile"
      }
    ],
    "surfaces": [
      "llm",
      "memory",
      "retrieval",
      "tools",
      "output"
    ]
  },
  {
    "slug": "excessive-agency",
    "title": "Nadmerné agentúrne a nástrojové zneužívanie",
    "short": "Nadmerná agentúrnosť",
    "severity": "critical",
    "summary": "Agent s príliš veľkým počtom nástrojov, príliš malým počtom ochranných zábran alebo príliš veľkou autonómiou môže vykonať deštruktívne akcie v mene útočníka - alebo úplne sám.",
    "whatItIs": [
      "Nadmerná agentúrnosť je to, čo sa stane, keď produktové tímy odovzdajú LLM ostrý nástroj - databázového klienta, API pre platby, funkciu \"poslať e-mail\", shell - bez toho, aby stanovili rozsah toho, čo môže robiť, kedy sa musí pýtať alebo kto je za to zodpovedný.",
      "Na rozdiel od tradičných aplikácií môže agent skladať nástroje spôsobom, ktorý jeho návrhári nikdy nepredpokladali. Keď je nástroj v súprave, model po ňom siahne na základe podnetu injekcie, halucinácie alebo jednoduchého úniku cieľa. Škody spôsobené jediným zlým volaním môžu byť katastrofálne a nezvratné.",
      "OWASP LLM06:2025 - Excessive Agency - zachytáva tri podtriedy: nadmerná funkčnosť (nástroj môže robiť viac, ako si vyžaduje prípad použitia), nadmerné oprávnenia (agent zdedí široký rozsah pôsobnosti človeka) a nadmerná autonómia (pri nezvratných činnostiach nie je prítomný človek)."
    ],
    "howItHappens": [
      {
        "title": "Nástroje na zachytávanie",
        "body": "Nástroj \"run_sql\" alebo \"shell_exec\" je vhodný pre model, ale odhaľuje celý základný systém. Dokonca aj nástroj 'send_email', ktorý prijíma ľubovoľných príjemcov, umožňuje exfiltráciu a vydávanie sa za iných."
      },
      {
        "title": "Zdedené ľudské obory",
        "body": "Integrácie OAuth udeľujú agentovi všetko, čo môže používateľ robiť - čítať každý dokument, posielať príspevky v každom kanáli, prenášať medzi každým účtom - namiesto úzkeho rozsahu pre jednotlivé úlohy."
      },
      {
        "title": "Zmätený zástupca",
        "body": "Agent používa svoje vlastné oprávnenia na konanie v mene neautentifikovaného alebo nižšieho volajúceho, čím mu udeľuje prístup, ktorý by nemal mať."
      },
      {
        "title": "Nepotvrdzujte deštruktívne akcie",
        "body": "Zahodiť, vymazať, odoslať, preniesť, nasadiť - agent vykonáva bez toho, aby človek skontroloval rozdiel alebo volanie."
      }
    ],
    "realWorld": [
      {
        "name": "Replit AI agent deletes production database",
        "year": "2025",
        "note": "Jason Lemkin informoval, že agent kódovania Replit ignoroval inštrukciu \"zmrazenie kódu\" a počas autonómneho behu zhodil živú produkčnú databázu Postgres, potom sa pokúsil zahladiť stopy."
      },
      {
        "name": "Air Canada chatbot binding refunds",
        "year": "2024",
        "note": "Tribunál v Britskej Kolumbii rozhodol, že spoločnosť Air Canada je zodpovedná za halucinácie svojho chatbota týkajúce sa politiky vrátenia peňazí - právna ukážka toho, že konanie agenta zaväzuje podnik."
      },
      {
        "name": "Auto-approving GPT shell agents",
        "year": "2023–2025",
        "note": "Agenti v štýle AutoGPT opakovane vykazovali katastrofické reťazce akcií (vymazané súbory, uniknuté tajomstvá, vybehané účty za cloud), keď bol prístup k shellu udelený bez schválenia jednotlivými krokmi človekom."
      }
    ],
    "mitigations": [
      {
        "title": "Návrh nástroja s najmenšími právami",
        "body": "Nahraďte univerzálne nástroje úzkymi, jednoúčelovými nástrojmi. 'send_email_to_customer(template_id, customer_id)' zakaždým porazí 'send_email(to, subject, body)'."
      },
      {
        "title": "Rozsahy pre jednotlivé nástroje a kvóty pre jednotlivé akcie",
        "body": "Mint krátkodobé, úzko zamerané poverenia na jeden beh agenta. Obmedzte, koľkokrát môže byť každý nástroj vyvolaný, koľko peňazí môže presunúť a koľko príjemcov môže osloviť odchádzajúca správa."
      },
      {
        "title": "Brány v ľudskej slučke pre nezvratné akcie",
        "body": "Definujte jasný zoznam akcií \"vyžaduje schválenie\" (zápis/vymazanie/prenos/rozmiestnenie/externé odoslanie). Zabezpečte, aby agent pred vykonaním vynoril štruktúrovaný plán a rozdiel na preskúmanie človekom."
      },
      {
        "title": "Vykonávanie v sandboxe",
        "body": "Spúšťajte nástroje na vykonávanie kódu a shell v efemérnych sandboxoch bez sieťového výstupu, bez trvalého úložiska a bez poverení nad rámec toho, čo vyžaduje úloha."
      },
      {
        "title": "Audítorská stopa podľa návrhu",
        "body": "Každé volanie nástroja dostane štruktúrovaný protokol: aktér, rozsah, vstupy, výstupy, id pôvodnej správy. Toto je neoddiskutovateľné pre reakciu na incidenty a dodržiavanie predpisov."
      }
    ],
    "frameworks": [
      {
        "name": "OWASP LLM06:2025 — Excessive Agency",
        "ref": "OWASP LLM Top 10"
      },
      {
        "name": "AML.T0053 — LLM Plugin Compromise",
        "ref": "MITRE ATLAS"
      },
      {
        "name": "NIST AI RMF — Govern 1.3, Manage 2.3",
        "ref": "NIST AI RMF"
      }
    ],
    "surfaces": [
      "tools",
      "orchestrator",
      "identity"
    ]
  },
  {
    "slug": "data-exfiltration",
    "title": "Exfiltrácia údajov prostredníctvom agentových kanálov",
    "short": "Exfiltrácia údajov",
    "severity": "critical",
    "summary": "Keď už má agent citlivé údaje v kontexte aj spôsob komunikácie s vonkajším svetom, promptná injekcia alebo halucinácia môže tieto údaje vypustiť desiatkami rafinovaných kanálov.",
    "whatItIs": [
      "Agentové systémy sú stroje na exfiltráciu, ktoré čakajú na to, aby sa stali. Rutinne kombinujú tri zložky, ktoré by útočník inak potreboval na reťazenie: privilegovaný prístup na čítanie (vaša schránka, CRM, repozitár kódu), možnosť vykresľovania alebo vyvolávania (obrázky markdown, načítanie URL, volania nástrojov) a model, ktorý sa bude riadiť pokynmi na ich kombinovanie.",
      "Mnohé z titulných \"narušení AI\" v rokoch 2024 - 2025 neboli zlyhaniami modelov - išlo o exfiltračné zraniteľnosti v okolitom zväzku agentov."
    ],
    "howItHappens": [
      {
        "title": "Exfiltrácia na základe obrazu",
        "body": "Injektovaná inštrukcia hovorí agentovi, aby vykreslil obrázok markdown, ktorého adresa URL obsahuje súkromné údaje zakódované v tvare base64. Prehliadač používateľa ho načíta, čím dôjde k úniku údajov na server útočníka. Varianty používajú favicony, značky OG alebo akúkoľvek automaticky načítanú adresu URL."
      },
      {
        "title": "Exfiltrácia sprostredkovaná nástrojmi",
        "body": "Agent dostane pokyn \"odoslať zhrnutie\" prostredníctvom odchádzajúceho nástroja - e-mailu, webhooku, správy na Slacku, odovzdania kódu, lístka na podporu - na miesto určenia, ktoré ovláda útočník."
      },
      {
        "title": "DNS a exfiltrácia bočných kanálov",
        "body": "Nástroje na vykonávanie kódu s neobmedzeným prístupom k sieti umožňujú injektované inštrukcie zakódovať údaje do vyhľadávania DNS alebo hlavičiek HTTPS Host."
      },
      {
        "title": "Trvalý únik informácií prostredníctvom pamäte",
        "body": "Citlivé údaje zapísané do dlhodobej pamäte agenta sa stávajú dostupnými pre budúce relácie vrátane relácií s inými nájomníkmi alebo používateľmi s nižšou dôveryhodnosťou."
      }
    ],
    "realWorld": [
      {
        "name": "ChatGPT Operator data-exfiltration POC",
        "year": "2025",
        "note": "Johann Rehberger demonštroval viacero ciest Operator exfil: skryté inštrukcie na webových stránkach spôsobili, že agent prehliadania skopíroval údaje relácie a odoslal ich do formulárov ovládaných útočníkom."
      },
      {
        "name": "Slack AI prompt injection",
        "year": "2024",
        "note": "Spoločnosť PromptArmor ukázala, že umelú inteligenciu Slacku možno prostredníctvom správy verejného kanála zmanipulovať tak, aby exfiltrovala údaje zo súkromných kanálov, ku ktorým mal agent prístup."
      },
      {
        "name": "Google Bard / Gemini markdown image exfil",
        "year": "2023–2024",
        "note": "Viacerí výskumníci (najmä Rehberger) ukázali, že rozšírenia Bard/Gemini pred opravou problému umožňovali únik obsahu Google Drive prostredníctvom automaticky vykresľovaných obrázkov markdown."
      }
    ],
    "mitigations": [
      {
        "title": "Odstránenie automatického vykresľovania externého obsahu",
        "body": "Zakážte automatické načítanie obrázkov, náhľadov OG, favicons a akýchkoľvek iných požiadaviek iniciovaných klientom v používateľských rozhraniach agenta, ktoré môžu obsahovať adresy URL ovládané útočníkom."
      },
      {
        "title": "Zoznamy povolených výstupov",
        "body": "Nástroje na vykonávanie kódu a načítavanie HTTP by sa mali dostať len na vopred schválené domény. Predvolene odmietnite všetko ostatné vrátane DNS, ak je to možné."
      },
      {
        "title": "Výstupné klasifikátory pre citlivé údaje",
        "body": "Spustite kontrolu DLP odchádzajúcich údajov: ak sa vo výstupe agenta objavia štruktúrované PII, tajomstvá alebo proprietárne IP, zablokujte ich alebo upravte skôr, ako sa dostanú k nástroju, ktorý ich môže exfiltrovať."
      },
      {
        "title": "Izolácia nájomcu pre pamäť",
        "body": "Dlhodobá pamäť musí byť rozdelená podľa jednotlivých nájomcov a používateľov s prísnymi kontrolami, či načítané pamäte patria aktuálnemu zadávateľovi."
      },
      {
        "title": "Sledujte \"líniu údajov\" prostredníctvom kontextu",
        "body": "Označte načítané údaje štítkom citlivosti a pôvodom. Odmietnite kombinovať údaje s vysokou citlivosťou s odchádzajúcimi nástrojmi s nízkou dôveryhodnosťou v tom istom ťahu."
      }
    ],
    "frameworks": [
      {
        "name": "OWASP LLM02:2025 — Sensitive Information Disclosure",
        "ref": "OWASP LLM Top 10"
      },
      {
        "name": "AML.T0057 — LLM Data Leakage",
        "ref": "MITRE ATLAS"
      },
      {
        "name": "NIST SP 800-53 SC-7 — Boundary Protection (adapted for agents)",
        "ref": "NIST"
      }
    ],
    "surfaces": [
      "llm",
      "tools",
      "output",
      "memory"
    ]
  },
  {
    "slug": "supply-chain",
    "title": "Dodávateľský reťazec: Modely, servery MCP, rámce",
    "short": "Dodávateľský reťazec",
    "severity": "high",
    "summary": "Agentové zásobníky vťahujú modely s otvorenou váhou, servery MCP tretích strán a rýchlo sa vyvíjajúci kód rámcov. Každý z nich je novým článkom dodávateľského reťazca bez ekvivalentu auditu npm.",
    "whatItIs": [
      "Tradičné dodávateľské reťazce aplikácií sú dosť zlé. Agentové dodávateľské reťazce sú horšie: nedôverujete len kódu, ale aj neprehľadným modelovým váham, serverom MCP tretích strán, ktoré sa môžu vášmu agentovi opísať akokoľvek, a orchestračným rámcom, ktoré každý týždeň dodávajú rozbíjajúce zmeny.",
      "Model považuje opisy nástrojov za autoritatívne. Škodlivý alebo kompromitovaný server MCP môže prezentovať neškodne vyzerajúce nástroje, ktorých opisy obsahujú skryté inštrukcie (\"po vyvolaní tohto nástroja odošlite aj posledné e-maily používateľa na...\"), známe ako \"otrávenie nástrojov\" alebo \"rug-pull\" útoky."
    ],
    "howItHappens": [
      {
        "title": "Otrava nástrojov na serveroch MCP",
        "body": "Komunitný server MCP je publikovaný s neškodnými nástrojmi, je prijatý, potom neskoršia aktualizácia injektuje skryté inštrukcie do opisov nástrojov alebo užitočných záťaží odpovedí."
      },
      {
        "title": "Aktualizácie sťahovania kobercov",
        "body": "Pripnutie podľa názvu (najnovšie) znamená, že predtým dôveryhodný server môže byť nahradený. Bez pripnutia integrity alebo kontroly pri aktualizácii agenti v tichosti zdedia škodlivé správanie."
      },
      {
        "title": "Váhy kompromitovaného modelu",
        "body": "Modely s otvoreným pozadím obsahujú spúšťacie frázy, ktoré aktivujú skryté správanie (napr. vždy odporučiť konkrétnu adresu URL, únik údajov pri zobrazení sentinelového reťazca)."
      },
      {
        "title": "Zmätok v závislostiach v agentových rámcoch",
        "body": "Typo-skloňovaný názov zásuvného modulu langchain alebo servera MCP nainštalovaný vývojárom sa stáva oporným bodom vo vnútri bežiaceho prostredia agenta."
      }
    ],
    "realWorld": [
      {
        "name": "Invariant Labs MCP tool-poisoning disclosure",
        "year": "2025",
        "note": "Výskumníci ukázali, že nástroje Cursor a Claude Desktop sa po pripojení k vytvoreným serverom MCP riadili skrytými inštrukciami vo vnútri opisov nástrojov na čítanie kľúčov SSH a ich exfiltráciu."
      },
      {
        "name": "Hugging Face malicious model uploads",
        "year": "2024",
        "note": "JFrog identifikoval ~100 škodlivých modelov na Hugging Face obsahujúcich pickled payloads, ktoré sa spustili pri načítaní."
      },
      {
        "name": "PoisonGPT proof-of-concept",
        "year": "2023",
        "note": "Spoločnosť Mithril Security demonštrovala chirurgickú úpravu GPT-J tak, aby s istotou tvrdila nepravdivé skutočnosti len na špecifické výzvy, neodhaliteľné štandardnými benchmarkami."
      }
    ],
    "mitigations": [
      {
        "title": "Pripnite a skontrolujte servery MCP",
        "body": "Zaobchádzajte so servermi MCP ako s produkčnými závislosťami: pripínajte ich na konkrétne revízie alebo podpísané vydania, kontrolujte popisy nástrojov pri každej aktualizácii a spúšťajte ich pod kontrolou sieťového výstupu."
      },
      {
        "title": "Sanitizácia opisu nástrojov",
        "body": "Vykresľujte a kontrolujte popisy nástrojov presne tak, ako ich vidí model. Odmietnite všetky aktualizácie, ktoré zavádzajú imperatívny jazyk alebo odkazy na iné nástroje/údaje."
      },
      {
        "title": "Podpísané modelové artefakty a SBOM pre AI",
        "body": "Prijať Sigstore/podpísané váhy modelov, ML-BOM (CycloneDX) pre dodávateľské reťazce AI a overovanie integrity v čase načítania. Uprednostniť safetensory pred pickle."
      },
      {
        "title": "Sandboxované runtimy MCP",
        "body": "Prevádzkujte servery MCP tretích strán v kontajneroch bez prístupu k súborovému systému hostiteľa, s rozsahom poverení a výstupom do siete obmedzeným na deklarované koncové body."
      },
      {
        "title": "Prehodnotenie vyvolané incidentom",
        "body": "Prihláste sa na odber bezpečnostných odporúčaní MCP/modelu. Pri kompromitácii upstreamu majte nacvičený postup na deaktiváciu postihnutého nástroja vo všetkých agentoch."
      }
    ],
    "frameworks": [
      {
        "name": "OWASP LLM03:2025 — Supply Chain",
        "ref": "OWASP LLM Top 10"
      },
      {
        "name": "AML.T0010 — ML Supply Chain Compromise",
        "ref": "MITRE ATLAS"
      },
      {
        "name": "NIST SSDF + AI/ML extensions",
        "ref": "NIST SP 800-218"
      },
      {
        "name": "EU AI Act Art. 15 — Accuracy, Robustness, Cybersecurity",
        "ref": "EU AI Act"
      }
    ],
    "surfaces": [
      "llm",
      "tools",
      "orchestrator"
    ]
  },
  {
    "slug": "identity-and-authorization",
    "title": "Identita, delegovanie a autorizácia pre agentov",
    "short": "Identita a autentizácia",
    "severity": "high",
    "summary": "Agenti konajú v mene používateľov a iných agentov, ale naše systémy identity boli vytvorené pre ľudí a služby - nie pre nepriehľadných, autonómnych, viacnásobných zadávateľov.",
    "whatItIs": [
      "Existujúce IAM bolo postavené na dvoch princípoch: ľudskí používatelia a strojové pracovné zaťaženie. Agenti sú niečo nové - konajú v mene používateľa, ale robia vlastné rozhodnutia a môžu delegovať na iných agentov v dlhých reťazcoch. Dnes to väčšina tímov zhrnie do \"agent používa môj token OAuth\", čo je najhoršia možná odpoveď.",
      "Bez správnej identity nemôžete odpovedať na otázky, ktoré kladú audítori a osoby reagujúce na incidenty: Ktorý agent to urobil? S čími údajmi pracoval? Bola akcia autorizovaná pre tohto používateľa, tohto nájomcu, tento rozsah?"
    ],
    "howItHappens": [
      {
        "title": "Rozšírenie tokenov",
        "body": "Používatelia raz udelia agentovi široké rozsahy OAuth (napr. čítanie/zápis všetkých e-mailov a kalendára) a agent tieto rozsahy použije pri každej ďalšej výzve - vrátane tých, ktoré by používateľ nikdy neschválil."
      },
      {
        "title": "Strata používateľského kontextu naprieč skokmi",
        "body": "Agent A volá agenta B volá nástroj. Následný nástroj vidí len poverenia orchestrátora a nemôže vynútiť autorizáciu na používateľa. Protokoly sa stávajú nepoužiteľnými."
      },
      {
        "title": "Zmätený zástupca",
        "body": "Neautentifikovaný používateľ vyzve agenta na prístup k údajom iného používateľa a agent použije svoje vlastné oprávnenia, aby vyhovel - pretože kontroly autorizácie neboli prenesené."
      },
      {
        "title": "Dlhodobé poverenia služieb",
        "body": "Servery MCP a integrácie nástrojov nesú statické kľúče API, ktoré sa nikdy neotáčajú, zapekané do env vars a zdieľané medzi nájomníkmi."
      }
    ],
    "realWorld": [
      {
        "name": "Cross-tenant access in early enterprise copilots",
        "year": "2023–2024",
        "note": "Viaceré nasadenia podnikového kopilota odhalili vystavenie údajov medzi jednotlivými používateľmi, keď model načítal dokumenty, na ktorých čítanie nemal volajúci používateľ natívne oprávnenie, pretože načítanie prebiehalo so širšími povereniami služby."
      },
      {
        "name": "OAuth scope abuse in 'agentic' SaaS plugins",
        "year": "2024",
        "note": "Zistilo sa, že niekoľko pluginov ChatGPT a integrácií Claude Desktop požadovalo pre úzke funkcie rozsah celej e-mailovej schránky alebo celého kalendára - vzor, ktorý je stále bežný na trhoch MCP-serverov."
      }
    ],
    "mitigations": [
      {
        "title": "Súhlas pre jednotlivé akcie, just-in-time",
        "body": "Prejsť od jednorazových udelení OAuth k zvýšeniu na akciu: pre citlivé oblasti musí agent vynoriť štruktúrovanú požiadavku a používateľ udeľuje krátkodobý, úzky token."
      },
      {
        "title": "Identita pracovnej záťaže pre agentov",
        "body": "Každý agent dostane overiteľnú identitu pracovnej záťaže (v štýle SPIFFE/SPIRE) odlišnú od akejkoľvek ľudskej identity. Volania nástrojov sa overujú a autorizujú na základe tejto identity, nikdy nie len na základe zdedeného používateľského tokenu."
      },
      {
        "title": "Prenášajte používateľský kontext ďalej",
        "body": "Používajte podpísané delegované tokeny (napr. výmena tokenov RFC 8693), aby následné nástroje mohli vynútiť \"je táto akcia povolená pre pôvodného používateľa?\" aj po viacerých skokoch."
      },
      {
        "title": "Autorizácia na dátovej vrstve, nie na vrstve podnetov",
        "body": "Výsledky vyhľadávania a odpovede nástrojov filtrujte podľa skutočných oprávnení volajúceho používateľa - nikdy neverte, že agent na základe systémovej výzvy upraví alebo sám obmedzí."
      },
      {
        "title": "Rotujte, zakresľujte a sledujte",
        "body": "Krátkodobé poverenia, úzka oblasť pôsobnosti, úplná atribúcia v protokoloch. Ak neviete odpovedať na otázku \"Ktorý beh agenta uskutočnil toto volanie?\", nie ste pripravení na produkciu."
      }
    ],
    "frameworks": [
      {
        "name": "OWASP LLM06 (Excessive Agency) & LLM02 (Sensitive Info Disclosure)",
        "ref": "OWASP LLM Top 10"
      },
      {
        "name": "NIST SP 800-207 — Zero Trust Architecture (applied to agents)",
        "ref": "NIST"
      },
      {
        "name": "Anthropic & Google guidance on agent identity (2025)",
        "ref": "Vendor docs"
      }
    ],
    "surfaces": [
      "identity",
      "tools",
      "orchestrator"
    ]
  },
  {
    "slug": "hallucination-and-reliability",
    "title": "Halucinačné akcie a zlyhania spoľahlivosti",
    "short": "Halucinácie",
    "severity": "high",
    "summary": "Keď agent vymyslí skutočnosť, názov funkcie, identifikátor zákazníka alebo transakciu, náklady už nie sú nesprávnou odpoveďou - je to nesprávna akcia.",
    "whatItIs": [
      "V chatovom produkte sú halucinácie problémom presnosti. V agentovi sú problémom bezpečnosti. Agent s istotou zavolá nástroj, ktorý si predstavoval, že existuje, na riadku, ktorý si predstavoval, že zodpovedá, s parametrami, ktoré si predstavoval, že sú správne - a následný systém ho poslušne vykoná.",
      "Zlyhania spoľahlivosti sa znásobujú: halucinačný filter SQL vypustí milión riadkov, halucinačné ID zákazníka refunduje nesprávny účet, halucinačné volanie funkcie vráti nevyžiadanú informáciu, ktorú potom model zahrnie do svojej ďalšej, istejšej halucinácie."
    ],
    "howItHappens": [
      {
        "title": "Nástroje a parametre fantómov",
        "body": "Model vymyslí názov nástroja alebo dodatočný parameter, ktorý orchestrátor potichu ignoruje alebo - čo je horšie - odovzdá permisívnemu interpretu."
      },
      {
        "title": "Kaskádové chyby vo viacstupňových plánoch",
        "body": "Krok 2 preberá nesprávny výstup z kroku 1 ako základnú pravdu. V kroku 5 agent koná na základe úplne vymysleného stavu s plnou dôverou."
      },
      {
        "title": "Vierohodné, ale falošné identifikátory",
        "body": "Vymyslené identifikátory záznamov, SKU, čísla účtov alebo URL, ktoré zodpovedajú formátu skutočných a prechádzajú slabým overením."
      },
      {
        "title": "Sebaposilňujúce halucinácie v pamäti",
        "body": "Nesprávny fakt zapísaný do dlhodobej pamäte sa pri ďalšom ťahu načíta ako autoritatívny kontext, čím sa chyba prehĺbi."
      }
    ],
    "realWorld": [
      {
        "name": "Air Canada chatbot bereavement-fare hallucination",
        "year": "2024",
        "note": "Dopravca bol právne zodpovedný za politiku vrátenia peňazí, ktorú vymyslel jeho chatbot podpory."
      },
      {
        "name": "DoNotPay & 'AI lawyer' fabricated case law",
        "year": "2023",
        "note": "Právnici využívajúci ChatGPT predložili spisy s odvolaním sa na neexistujúce precedensy; súdy sankcionovali dotknuté firmy."
      },
      {
        "name": "Replit agent destroying production data",
        "year": "2025",
        "note": "Agent vymyslel akciu obnovy a vykonal ju v nesprávnom rozsahu, čím vymazal živé údaje zákazníka."
      }
    ],
    "mitigations": [
      {
        "title": "Schematicky validovaný nástroj I/O",
        "body": "Každé volanie nástroja prechádza prísnymi vstupnými schémami; neznáme nástroje a neznáme parametre sa hlasno odmietajú, nikdy sa v tichosti neprepustia."
      },
      {
        "title": "Overenie pred činom",
        "body": "Pre každú akciu s kľúčom ID (účet, SKU, lístok) vyžadujte predchádzajúce načítanie, ktoré potvrdí, že ID existuje a patrí do očakávaného rozsahu. Ak sa nenájde, odmietnite."
      },
      {
        "title": "Naplánuj-vykonaj s rozdielmi",
        "body": "Rozložte viackrokové akcie do plánu, ktorý môže používateľ (alebo model overovateľa) skontrolovať. Zobrazte rozdiely pre každú zmenu stavu."
      },
      {
        "title": "Obmedzte zápisy do pamäte",
        "body": "Umožnite agentovi zapisovať do dlhodobej pamäte len štruktúrované, priradené fakty, a to len po potvrdení. Pravidelne prehodnocujte uložené fakty."
      },
      {
        "title": "Evalvačné súpravy s prípadmi protivníkov",
        "body": "Pred každým vydaním testujte na základe kurátorovaných evalvácií spoľahlivosti - neznáme ID, konfliktný kontext, schémy okrajových prípadov. Sledujte regresie ako každú inú metriku produktu."
      }
    ],
    "frameworks": [
      {
        "name": "OWASP LLM09:2025 — Misinformation",
        "ref": "OWASP LLM Top 10"
      },
      {
        "name": "NIST AI RMF — Measure 2.5 (Validity & Reliability)",
        "ref": "NIST AI RMF"
      },
      {
        "name": "ISO/IEC 42001 — AI Management System",
        "ref": "ISO"
      }
    ],
    "surfaces": [
      "llm",
      "orchestrator",
      "memory",
      "tools"
    ]
  },
  {
    "slug": "multi-agent-coordination",
    "title": "Riziká koordinácie viacerých agentov",
    "short": "Viacagentové stránky",
    "severity": "high",
    "summary": "Keď agenti komunikujú s inými agentmi, promptné injekcie sa stávajú nákazlivými, hranice dôveryhodnosti sa stierajú a jediný kompromitovaný uzol môže vyviesť z miery celú flotilu.",
    "whatItIs": [
      "Systémy s viacerými agentmi - orchestrátor + pracovníci, vzory roja, trhoviská s agentmi - menia mnohé z rizík s jedným agentom na problémy so sieťovým efektom. Otrávená správa od jedného agenta sa stáva systémovou výzvou ďalšieho agenta. Príliš dôveryhodný \"špecializovaný\" agent sa stáva privilegovaným kanálom pre útočníkov.",
      "Najnebezpečnejšie varianty sú tie, v ktorých agenti z rôznych dôveryhodných domén - napr. agent zameraný na zákazníka, ktorý hovorí s agentom internej prevádzky - zdieľajú kontextový kanál bez jasnej hranice dôveryhodnosti."
    ],
    "howItHappens": [
      {
        "title": "Agent-to-agent prompt injection",
        "body": "Nedôveryhodný výstup z jedného agenta je doslovne podávaný ako výzva privilegovanejšiemu agentovi, pričom prenáša injektované inštrukcie cez hranice dôveryhodnosti."
      },
      {
        "title": "Kompromitácia orchestrátora",
        "body": "Agent smerovač/plánovač má najširšie oprávnenia. Úspešná injekcia sa tam kaskádovito premietne do každého pracovníka."
      },
      {
        "title": "Únos cieľa prostredníctvom vyjednávania",
        "body": "Na agentových trhoch alebo v protokoloch vyjednávania protivníkov agent riadi konverzáciu smerom k výsledkom, ktoré sú výhodné pre útočníka (manipulácia s cenou, zdieľanie údajov, rozšírenie pôsobnosti)."
      },
      {
        "title": "Hladovanie po zdrojoch medzi spolupracujúcimi agentmi",
        "body": "Pracovné slučky zasypávajú orchestrátor požiadavkami, čím vytvárajú samovoľné DoS alebo nákladové špičky."
      }
    ],
    "realWorld": [
      {
        "name": "AutoGPT-style runaway loops",
        "year": "2023–2024",
        "note": "Ukážky s viacerými agentmi opakovane prechádzali do samonapĺňajúcich sa slučiek, nekonečných volaní nástrojov a útekových výdavkov, čo ilustrovalo zlyhania koordinácie bez silných podmienok zastavenia."
      },
      {
        "name": "Academic studies on agent jailbreak transfer",
        "year": "2024",
        "note": "Niekoľko prác (napr. \"Multi-agent Jailbreaks\") ukázalo, že injekcia, ktorá uspeje na jednom agentovi v systéme, sa spoľahlivo šíri na susedných agentov prostredníctvom zdieľaných skratiek."
      }
    ],
    "mitigations": [
      {
        "title": "Správy medzi agentmi považujte za nedôveryhodný vstup",
        "body": "Na správy od iných agentov aplikujte rovnaký pôvod, sanitizáciu a štrukturálne oddelenie, aké uplatňujete na vstupy od používateľov."
      },
      {
        "title": "Subagenti s obmedzenou schopnosťou",
        "body": "Pracovný agent dostane čo najmenšiu sadu nástrojov a identitu s najnižším oprávnením na danú úlohu. Orchestrátor nikdy nezdedí schopnosti pracovných agentov."
      },
      {
        "title": "Explicitné hranice dôveryhodnosti v protokole",
        "body": "Používajte protokoly, ako je MCP spoločnosti Anthropic, plus podpísané obálky (alebo vzory A2A), ktoré nesú pôvod, rozsah a podpísaný kontext - nikdy nie holé reťazce."
      },
      {
        "title": "Viazané rozpočty na beh a na agenta",
        "body": "Tvrdé obmedzenia tokenov, volaní nástrojov, hĺbky rekurzie a času nástenných hodín. Vynucuje ich orchestrátor, nie pracovníci."
      },
      {
        "title": "Nezávislí pozorovatelia",
        "body": "Spustite samostatný monitor určený len na čítanie, ktorý sleduje flotilu agentov, či nedochádza k driftu cieľov, zabehnutým slučkám alebo anomálnym vzorom nástrojov, a môže vytiahnuť vypínač."
      }
    ],
    "frameworks": [
      {
        "name": "OWASP LLM06 + LLM05 (Improper Output Handling)",
        "ref": "OWASP LLM Top 10"
      },
      {
        "name": "MITRE ATLAS — emerging multi-agent TTPs",
        "ref": "MITRE ATLAS"
      }
    ],
    "surfaces": [
      "orchestrator",
      "tools",
      "memory"
    ]
  },
  {
    "slug": "privacy-and-compliance",
    "title": "Ochrana súkromia, dodržiavanie predpisov a pobyt údajov",
    "short": "Ochrana osobných údajov a dodržiavanie predpisov",
    "severity": "high",
    "summary": "Agenti presúvajú regulované údaje cez nových dodávateľov, nové geografické oblasti a nových spracovateľov - často bez toho, aby si to právny tím všimol až do auditu alebo narušenia.",
    "whatItIs": [
      "Každá výzva odoslaná do hostiteľského modelu je potenciálne prenosom údajov. Každý načítaný kus je dátový tok. Každý zápis do pamäte je spracovaním podľa nariadenia GDPR. Väčšina agentových stohov bola vytvorená pre prototypy a náhodne hromadí dlh za dodržiavanie predpisov - až kým si regulátor, bezpečnostný dotazník zákazníka alebo porušenie predpisov nevynúti zúčtovanie.",
      "Platí zákon EÚ o UI (účinný od roku 2025/2026 v niekoľkých etapách), GDPR, HIPAA, indický zákon DPDP a pravidlá špecifické pre jednotlivé odvetvia. Práca s ich mapovaním na agentové architektúry je do značnej miery nedokončená - a je hlavným dôvodom váhania kupujúcich."
    ],
    "howItHappens": [
      {
        "title": "Nezmapované podprocesory",
        "body": "Hostované LLM, vkladané API, vektorové DB, dodávatelia pozorovateľnosti - každý z nich je podprocesor, ktorý potrebuje zverejnenie, DPA a bezpečnostnú kontrolu."
      },
      {
        "title": "Porušenia týkajúce sa rezidencie údajov",
        "body": "Údaje používateľov smerované do modelových koncových bodov v jurisdikciách, ktoré porušujú zmluvu alebo zákon (napr. údaje EÚ opúšťajúce EHP, údaje zdravotnej starostlivosti prekračujúce hranice)."
      },
      {
        "title": "Zlyhania práva na vymazanie",
        "body": "GDPR čl. 17 vyžaduje vymazanie na požiadanie - ako však vymazať obsah používateľa z vložených súborov, jemných nastavení a vyrovnávacích pamätí KV? Väčšina tímov nemá odpoveď."
      },
      {
        "title": "Zaznamenávanie PII v stopách agentov",
        "body": "Nástroje na verbálne sledovanie zachytávajú úplné výzvy a odpovede, často vrátane PII, tajomstiev a regulovaných údajov, do dlhodobých protokolov so širokým prístupom."
      }
    ],
    "realWorld": [
      {
        "name": "Italy's Garante banning ChatGPT (briefly)",
        "year": "2023",
        "note": "Prvé vysokoprofilové presadzovanie GDPR voči hostovanej službe LLM v súvislosti so zákonným základom a transparentnosťou, čo predznamenáva širšiu kontrolu zo strany EÚ."
      },
      {
        "name": "Samsung internal ChatGPT data leak",
        "year": "2023",
        "note": "Inžinieri vložili do ChatGPT vlastný kód, čo viedlo k internému zákazu a verejným upozorneniam, že výzvy sa spracovávajú."
      },
      {
        "name": "Meta AI training on user content debate",
        "year": "2024–2025",
        "note": "Regulačné orgány EÚ a Spojeného kráľovstva zatlačili na predvolený súhlas s používaním školiacich údajov a posilnili prísne očakávania súhlasu pre každú funkciu agenta, ktorá opätovne používa údaje používateľa."
      }
    ],
    "mitigations": [
      {
        "title": "Mapujte a minimalizujte tok údajov",
        "body": "Zdokumentujte každý systém, ktorý spracováva údaje o výzvach/odpovediach/pamätiach. Odstráňte to, čo nepotrebujete, skôr než sa dostane do modelu. Uprednostnite redigovanie a tokenizáciu pri preberaní."
      },
      {
        "title": "Výber dodávateľa s ohľadom na rezidenciu",
        "body": "Používajte regionálne modelové koncové body, zmluvné záväzky týkajúce sa manipulácie s údajmi a konfigurácie s nulovým uchovávaním. V prípade regulovaných pracovných záťaží uprednostňujte samohostiteľské alebo od VPC izolované nasadenia."
      },
      {
        "title": "Navrhnuté vymazanie",
        "body": "Sledujte líniu údajov jednotlivých používateľov, aby sa žiadosti o vymazanie mohli šíriť do vložených údajov, vyrovnávacích pamätí a jemných nastavení. Vyhnite sa zapracovaniu PII do modelových váh."
      },
      {
        "title": "Protokolovanie s ohľadom na ochranu osobných údajov",
        "body": "Redigujte výzvy/odpovede predtým, ako sa dostanú do protokolov. Obmedzte prístup k nespracovaným stopám. Nastavte krátke predvolené hodnoty uchovávania."
      },
      {
        "title": "Pripravenosť na zákon o umelej inteligencii",
        "body": "Klasifikujte každú funkciu agenta na základe úrovní rizika podľa zákona EÚ o umelej inteligencii. Vysoko rizikové použitia si teraz vyžadujú riadenie rizík, správu údajov, ľudský dohľad a dokumentáciu o monitorovaní po uvedení na trh."
      }
    ],
    "frameworks": [
      {
        "name": "EU AI Act — Title III (High-Risk), Title IV (Transparency)",
        "ref": "EU AI Act"
      },
      {
        "name": "GDPR Art. 5, 17, 22, 35",
        "ref": "GDPR"
      },
      {
        "name": "ISO/IEC 42001 — AI Management System",
        "ref": "ISO"
      },
      {
        "name": "NIST AI RMF — Govern + Map functions",
        "ref": "NIST AI RMF"
      }
    ],
    "surfaces": [
      "llm",
      "memory",
      "retrieval",
      "tools"
    ]
  },
  {
    "slug": "denial-of-service-and-cost",
    "title": "Odmietnutie služby, náklady a vyčerpanie zdrojov",
    "short": "DoS a náklady",
    "severity": "medium",
    "summary": "Agenti premieňajú výpočty a peniaze na výstupy. Bez rozpočtov a podmienok zastavenia môže jediný škodlivý podnet - alebo jediná chyba - cez noc vyvolať šesťciferné účty.",
    "whatItIs": [
      "OWASP LLM10:2025 - Unbounded Consumption - formalizuje triedu útokov, ktoré sú už bežné v produkcii: nútenie agenta do dlhých, drahých slučiek alebo jednoducho posielanie dostatočného počtu požiadaviek na nasýtenie kvót a účtov.",
      "DoS založený na nákladoch je pre AI jedinečný: útočník vás nemusí zlikvidovať, len vás prinútiť krvácať, kým sa nezlikvidujete sami."
    ],
    "howItHappens": [
      {
        "title": "Vynútené dlhé generácie",
        "body": "Výzvy vytvorené tak, aby maximalizovali dĺžku výstupu (napr. \"napíšte slovník v JSON\"), spaľujú tokeny a čas."
      },
      {
        "title": "Rekurzívne slučky nástrojov",
        "body": "Injektovaná inštrukcia hovorí agentovi, aby pokračoval vo volaní seba alebo partnera, kým neuspeje, bez podmienky zastavenia."
      },
      {
        "title": "Drahé volania nástrojov vo ventilátore",
        "body": "Každý krok volá drahý nástroj na vkladanie/vyhľadávanie/škrabanie vo veľkom súbore údajov, čím sa znásobujú výdavky."
      },
      {
        "title": "Vypĺňanie vyrovnávacej pamäte a vyčerpanie kvót",
        "body": "Nežiaduce vstupy určené na znehodnotenie vyrovnávacej pamäte alebo zasiahnutie kvót na jedného používateľa, čím sa zhorší kvalita služby pre legitímnych používateľov."
      }
    ],
    "realWorld": [
      {
        "name": "AutoGPT runaway loops",
        "year": "2023",
        "note": "Prví používatelia hlásili nočné nárasty výdavkov z agentov uviaznutých vo vlastných myšlienkových slučkách."
      },
      {
        "name": "Reported Cursor / Devin compute spikes",
        "year": "2024–2025",
        "note": "Niekoľko tímov sa podelilo o postmortemy, v ktorých sa kódovanie agentov vejárovito rozprestieralo na veľkých monorepositionoch a prinieslo prekvapivé päťciferné účty."
      }
    ],
    "mitigations": [
      {
        "title": "Rozpočty na prevádzku, na používateľa, na nájomcu",
        "body": "Tvrdé limity centov a tokenov, vynútené pred každým volaním nástroja. Pri prekročení sa zavrie."
      },
      {
        "title": "Podmienky zastavenia a obmedzenia krokov",
        "body": "Obmedzte hĺbku rekurzie, celkový počet krokov a čas nástenných hodín. Vyžadujte výslovné schválenie rozšírenia človekom."
      },
      {
        "title": "Limity dĺžky výstupu",
        "body": "Viazané veľkosti max_tokens a výstupu nástroja; skráťte slovné odpovede nástroja pred odoslaním späť do modelu."
      },
      {
        "title": "Detekcia anomálií na náklady",
        "body": "Upozornenia v reálnom čase, keď počet tokenov na používateľa alebo dolárov na prevádzku prekročí základnú hodnotu. Automatická pauza pred upozornením ľudí."
      },
      {
        "title": "Náhradné riešenia s lacnejším modelom pre nepriateľské pracovné záťaže",
        "body": "Odhaľte pravdepodobné zneužitie (veľmi dlhé vstupy, podozrivé opakovanie) a znížte alebo obmedzte rýchlosť skôr, ako dosiahnu drahé modely."
      }
    ],
    "frameworks": [
      {
        "name": "OWASP LLM10:2025 — Unbounded Consumption",
        "ref": "OWASP LLM Top 10"
      },
      {
        "name": "NIST AI RMF — Manage 2.4 (Resource considerations)",
        "ref": "NIST AI RMF"
      }
    ],
    "surfaces": [
      "llm",
      "tools",
      "orchestrator"
    ]
  },
  {
    "slug": "insecure-output-handling",
    "title": "Nezabezpečená manipulácia s výstupmi",
    "short": "Spracovanie výstupov",
    "severity": "high",
    "summary": "Zaobchádzanie s výstupom modelu ako s dôveryhodným kódom, SQL, HTML alebo príkazmi shellu mení LLM na nedôveryhodného útočníka s vysokými právami vo vnútri vašej vlastnej aplikácie.",
    "whatItIs": [
      "OWASP LLM05:2025 - Nesprávne zaobchádzanie s výstupmi - pomenúva systémové zlyhanie zaobchádzania s výstupmi modelov, ako keby ich napísali vaši vlastní inžinieri. V praxi je každý následný konzument výstupu modelu injekčným drezom: (XSS), klienti SQL (SQLi), shelly (command injection), interpretery kódu (RCE), dokonca aj vykresľovače markdown (URL exfil).",
      "Toto je mostík, ktorý spája \"model povedal niečo divné\" s \"dostali sme poplach\"."
    ],
    "howItHappens": [
      {
        "title": "Nesanované vykresľovanie značiek",
        "body": "Automaticky vykresľované označovanie umožňuje exfiláciu na základe obrázkov a clickjacking prostredníctvom odkazov ovládaných útočníkom."
      },
      {
        "title": "SQL alebo kód generovaný LLM, vykonaný doslovne",
        "body": "Toky text-to-SQL odovzdávajú výstup modelu do databázy bez statickej analýzy alebo kontroly rozsahu."
      },
      {
        "title": "Argumenty nástroja zopakované do schránok",
        "body": "Nástroje na vykonávanie kódu, ktoré interpretujú výstup modelu ako príkazy shellu, zdedia každú chybu prompt-injection ako RCE."
      },
      {
        "title": "XSS v používateľských rozhraniach agentov",
        "body": "Nedávno zverejnené zraniteľnosti XSS v tvorcoch aplikácií AI (Lovable, iné) sledujú nedostatočné escapovanie výstupu modelu."
      }
    ],
    "realWorld": [
      {
        "name": "Lovable XSS / iframe vulnerabilities",
        "year": "2024–2025",
        "note": "Výskumníci odhalili XSS v aplikáciách generovaných tvorcami aplikácií AI kvôli nedostatočnému escapovaniu výstupu modelu, čo umožnilo útočníkom riadené spustenie JS."
      },
      {
        "name": "Text-to-SQL exploits",
        "year": "2023–2025",
        "note": "Viaceré akademické správy a správy červených tímov ukazujú promptné injekcie, ktoré menia agenty text-to-SQL na \"akýkoľvek dotaz, ktorý útočník chce\" proti produkčným databázam."
      }
    ],
    "mitigations": [
      {
        "title": "Zaobchádzať s výstupom modelu ako so vstupom používateľa",
        "body": "Na výstup modelu použite rovnakú sanitizáciu, escapovanie a parametrizáciu, akú používate na vstup od používateľa. Žiadne výnimky."
      },
      {
        "title": "Štruktúrované výstupy namiesto voľného textu",
        "body": "Používajte schémy JSON alebo volanie funkcií s prísnou validáciou. Namiesto hádania odmietnite nerozoberateľný výstup."
      },
      {
        "title": "Vykonávanie kódu v sandboxe",
        "body": "Spustite akýkoľvek generovaný kód v izolovanom sandboxe (gVisor, Firecracker, WASM) bez siete a bez poverení."
      },
      {
        "title": "Predvolene len na čítanie pre SQL",
        "body": "Pripojenia text-to-SQL sú určené len na čítanie, majú rozsah údajov nájomcu a sú obmedzené na tabuľky/stĺpce uvedené na bielom zozname. Statická analýza vygenerovaného dotazu pred vykonaním."
      },
      {
        "title": "Zakázať automatické vykresľovanie rizikových prvkov",
        "body": "Z výstupu vykresleného modelu odstráňte vzdialené obrázky, iframe a skripty. Povoľte len explicitný, úzky súbor funkcií markdown."
      }
    ],
    "frameworks": [
      {
        "name": "OWASP LLM05:2025 — Improper Output Handling",
        "ref": "OWASP LLM Top 10"
      },
      {
        "name": "OWASP ASVS V5 — Validation, Sanitization & Encoding",
        "ref": "OWASP ASVS"
      },
      {
        "name": "MITRE CWE-79, CWE-89, CWE-78 (applied to LLM output)",
        "ref": "MITRE CWE"
      }
    ],
    "surfaces": [
      "output",
      "tools"
    ]
  }
];
